// Problem-specific detectors for classic wrong approaches. Checked only when a submission is wrong.
// re: regex tested against the learner's SQL (comments stripped). absent: true → fires when the regex does NOT match.
// R(re, category, message, concept, absent?) — compact rule builder.
const R = (re, cat, msg, concept, absent = false) => ({ re, cat, msg, concept, ...(absent ? { absent: true } : {}) });

export const MISTAKE_RULES = {
  P101: [{ re: '\\*\\s*0?\\.18\\b', cat: 'Logic', msg: 'Computed only the tax, not price plus tax', concept: 'Price including 18% = price × 1.18.' }],
  P102: [{ re: 'distance_km\\s*/\\s*fare', cat: 'Logic', msg: 'Divided the wrong way round', concept: '"Per kilometre" means ÷ kilometres: fare / distance_km.' }],
  P109: [{ re: "'desserts'", absent: true, cat: 'Logic', msg: 'Left out one of the requested values', concept: 'List every value the question names inside IN (…).' }],
  P117: [{ re: 'lower\\s*\\(', absent: true, cat: 'Logic', msg: 'Did not convert the name to lowercase', concept: 'LOWER(text); functions can be nested inside REPLACE.' }],
  P118: [{ re: 'is\\s+not\\s+null', absent: true, cat: 'NULL handling', msg: 'Customers without an email were not excluded', concept: 'Text || NULL is NULL; filter with WHERE email IS NOT NULL.' }],
  P120: [{ re: '100', absent: true, cat: 'Logic', msg: 'Forgot to multiply by 100 for a percentage', concept: 'Percentage = 100.0 × part / whole.' }],
  P123: [{ re: '<=\\s*1[169]\\b', cat: 'Edge cases', msg: 'Boundary hour placed in the wrong slot', concept: '"Before 11:00" is hour < 11; 11:00 itself belongs to lunch.' }],
  P124: [{ re: "status\\s*=\\s*'success'", cat: 'Logic', msg: 'Filtered out the failed attempts', concept: 'The question asks for every attempt; one order has many rows in payments.' }],
  P126: [{ re: 'quantity\\s*\\+\\s*unit_price|unit_price\\s*\\+\\s*quantity', cat: 'Logic', msg: 'Added quantity and price instead of multiplying', concept: 'Line total = quantity × unit_price.' }],
  P203: [{ re: 'count\\s*\\(\\s*delivered_at', cat: 'Aggregation', msg: 'COUNT(column) skipped cancelled orders', concept: 'COUNT(col) ignores NULLs; cancelled orders have NULL delivered_at. Use COUNT(*) for all orders.' }],
  P204: [{ re: 'group\\s+by\\s+ordered_at\\s*,|group\\s+by\\s+ordered_at\\s*$', cat: 'Dates/time', msg: 'Grouped by the full timestamp instead of the date', concept: 'Convert to a date (ordered_at::date) so all orders on one day share a group.' }],
  P205: [{ re: 'dept_id\\s+is\\s+not\\s+null', cat: 'NULL handling', msg: 'Removed employees with no department', concept: 'GROUP BY keeps NULL as its own group — don\'t filter it out when the question includes it.' }],
  P209: [{ re: 'tip\\s*=\\s*0|tip\\s*<=\\s*0|coalesce', absent: true, cat: 'NULL handling', msg: 'A ₹0 tip was not counted as "no tip"', concept: 'NULL and 0 are different values; "no tip" here means either.' }],
  P210: [{ re: 'rating\\s*=\\s*2\\b', cat: 'Edge cases', msg: 'Counted only 2-star ratings as low', concept: '"2 stars or fewer" is rating <= 2.' }],
  P005: [{ re: 'extract\\s*\\(\\s*dow\\b[\\s\\S]*in\\s*\\(\\s*6\\s*,\\s*7|extract\\s*\\(\\s*isodow\\b[\\s\\S]*in\\s*\\(\\s*0\\s*,\\s*6', cat: 'Dates/time', msg: 'Mixed up DOW (0=Sun…6=Sat) and ISODOW (1=Mon…7=Sun)', concept: 'DOW: Sunday = 0. ISODOW: Sunday = 7. Pick one scheme and check both weekend days.' }],
  P010: [{ re: 'count\\s*\\(\\s*\\*\\s*\\)', cat: 'Aggregation', msg: 'COUNT(*) after a join counted line items, not orders', concept: 'After joining a child table, count the parent with COUNT(DISTINCT parent_key).' }],
  P014: [{ re: 'count\\s*\\(\\s*\\*\\s*\\)', cat: 'NULL handling', msg: 'COUNT(*) used where COUNT(column) was needed', concept: 'COUNT(*) counts rows; COUNT(col) counts non-NULL values.' }],
  P025: [{ re: 'count\\s*\\(\\s*d\\.driver_id\\s*\\)', cat: 'Joins', msg: 'Counted drivers without DISTINCT after joining trips', concept: 'A driver repeats once per trip after the join — count DISTINCT driver_id.' }],
  P030: [{ re: 'avg\\s*\\(\\s*price\\s*\\)\\s*from\\s+products\\s*\\)', cat: 'Logic', msg: 'Benchmark average computed on a different population', concept: 'Compare like with like: the average must use the same filter (active products).' }],
  P031: [{ re: '\\(\\s*select\\s+avg\\s*\\(\\s*salary\\s*\\)\\s+from\\s+employees\\s*\\)', cat: 'Logic', msg: 'Compared with the company average instead of the department average', concept: 'Correlate the benchmark with the row\'s group (WHERE x.dept_id = e.dept_id) or pre-aggregate by department.' }],
  P034: [{ re: 'union\\s+all', cat: 'Logic', msg: 'UNION ALL kept duplicate cities', concept: 'UNION removes duplicates; UNION ALL keeps them.' }],
  P050: [{ re: 'row_number', cat: 'Window functions', msg: 'ROW_NUMBER ignores ties', concept: '"Accounting for ties" → DENSE_RANK (second distinct value) or RANK.' },
         { re: '\\brank\\s*\\(', cat: 'Window functions', msg: 'RANK leaves a gap after ties at the top', concept: 'RANK gives 1,1,3 — there may be no rank 2. DENSE_RANK gives 1,1,2.' }],
  P051: [{ re: 'row_number', cat: 'Window functions', msg: 'ROW_NUMBER dropped tied products', concept: 'Use RANK/DENSE_RANK = 1 when ties must be kept.' }],
  P054: [{ re: '\\(\\s*select\\s+sum[\\s\\S]*from\\s+order_items\\s*\\)', cat: 'Business logic', msg: 'Denominator includes non-completed orders', concept: 'Numerator and denominator must come from the same filtered population; SUM(SUM(x)) OVER () guarantees it.' }],
  P056: [{ re: 'distinct', absent: true, cat: 'Edge cases', msg: 'Did not deduplicate activity dates before finding islands', concept: 'Duplicates advance ROW_NUMBER without advancing the date, breaking the island key.' }],
  P060: [{ re: '::\\s*date|date_trunc|cast\\s*\\([^)]*as\\s+date', cat: 'Dates/time', msg: 'Grouped by calendar date for a time-window rule', concept: 'Windows like "within 2 minutes" cross midnight; compare timestamps with LAG or a self-join.' }],
  P062: [{ re: 'percentile_disc', cat: 'Aggregation', msg: 'Used discrete instead of continuous percentiles', concept: 'PERCENTILE_CONT interpolates; PERCENTILE_DISC returns an existing value.' },
         { re: 'avg\\s*\\(', cat: 'Aggregation', msg: 'Used the mean as the "typical" value', concept: 'Median = PERCENTILE_CONT(0.5); means are pulled by outliers.' }],
  P063: [{ re: 'coalesce', absent: true, cat: 'NULL handling', msg: 'Missing device values not mapped to "unknown"', concept: "->> returns NULL for a missing key, a JSON null or a NULL document; COALESCE(… , 'unknown')." }],
  P064: [{ re: 'count\\s*\\(\\s*(?!distinct)[\\w.]*category', cat: 'Aggregation', msg: 'Counted category rows instead of distinct categories', concept: 'COUNT(DISTINCT category).' },
         { re: 'string_agg\\s*\\([^)]*order\\s+by', absent: true, cat: 'Logic', msg: 'STRING_AGG without an ORDER BY', concept: 'Concatenation order is undefined unless you order inside the aggregate.' }],
  P065: [{ re: 'lateral|partition\\s+by', absent: true, cat: 'Window functions', msg: 'LIMIT applied to the whole result instead of per customer', concept: 'Top-N per group needs ROW_NUMBER() OVER (PARTITION BY …) or LATERAL … LIMIT.' }],
  P070: [{ re: 'event_time\\s*>=?|>=?\\s*\\w+\\.event_time|>=?\\s*\\w+\\.t\\b', absent: true, cat: 'Business logic', msg: 'Funnel steps not required to happen in order', concept: 'An ordered funnel compares each step\'s time with the previous step\'s time.' }],
  P071: [{ re: "2026-0[45]|current_date", absent: true, cat: 'Business logic', msg: 'Immature cohort months reported instead of censored', concept: 'Months after the observation window are unknown (NULL), not 0%.' }],
  P072: [{ re: 'end_date\\s*(<|between)', cat: 'Business logic', msg: 'Measured churn as subscriptions ending (plan changes counted as churn)', concept: 'Customer churn compares the set of active customers at two dates.' }],
  P074: [{ re: 'sum\\s*\\([^)]*\\)\\s*over', cat: 'Aggregation', msg: 'Summed daily distinct users to get a rolling distinct count', concept: 'Distinct counts are not additive. Join each day to its window and COUNT(DISTINCT).' }],
  P075: [{ re: "champion[\\s\\S]*at_risk", cat: 'Business logic', msg: 'Segment rules evaluated in the wrong order', concept: 'CASE stops at the first match — encode the stated precedence exactly.' }],
  P076: [{ re: '1\\s+preceding', absent: true, cat: 'Window functions', msg: 'Baseline window includes the current transaction', concept: 'End the frame at 1 PRECEDING so a spike cannot dilute its own baseline.' }],
  P080: [{ re: "2026-05-01|2026-04-1[67]|interval\\s*'14\\s*days'[\\s\\S]*<=\\s*(timestamp|date)", absent: true, cat: 'Business logic', msg: 'Users with incomplete 14-day windows not excluded', concept: 'Censoring: only judge anchors whose full window has been observed.' }],
  // Level 2 — joins
  P300: [{ re: 'join\\s+orders', absent: true, cat: 'Business logic', msg: 'Order status was never checked', concept: 'A line item has no status; join to orders to keep only completed orders.' }],
  P301: [{ re: 'left\\s+join', cat: 'Joins', msg: 'LEFT JOIN kept departments that have no employees', concept: 'Only departments with staff were asked for: an INNER JOIN drops the rest (and COUNT(*) on a NULL-padded row would report 1).' }],
  P302: [{ re: 'd\\.city\\s*=\\s*t\\.city|t\\.city\\s*=\\s*d\\.city', cat: 'Joins', msg: 'Joined drivers on city instead of driver_id', concept: 'Join on the key the foreign key points to. City is shared by many drivers, so trips multiply.' }],
  P303: [{ re: 'p\\.price', cat: 'Business logic', msg: 'Revenue used the current list price, not the price charged', concept: 'order_items.unit_price is what the customer paid; products.price is today\'s list price.' }],
  P304: [{ re: 'between', cat: 'Joins', msg: 'BETWEEN is inclusive at both ends, so boundary grades matched two bands', concept: 'Use half-open ranges: grade >= min_grade AND grade < max_grade.' }],
  P305: [{ re: "status\\s*=\\s*'delivered'", absent: true, cat: 'Business logic', msg: 'Cancelled orders were counted as deliveries', concept: 'Filter status = \'delivered\' before aggregating.' }],
  P306: [{ re: 'count\\s*\\(\\s*distinct', absent: true, cat: 'Joins', msg: 'Payment attempts were counted as if they were orders', concept: 'One order can have several successful payments: COUNT(DISTINCT order_id) counts orders.' }],
  P310: [{ re: 'left\\s+(outer\\s+)?join', absent: true, cat: 'Joins', msg: 'Courses without an instructor disappeared', concept: 'INNER JOIN drops rows with no partner. Use LEFT JOIN from the table that must keep every row.' }],
  P311: [{ re: "\\bwhere\\s+o\\.status\\s*=\\s*'completed'\\s*group\\s+by", cat: 'Joins', msg: 'A WHERE on the outer-joined side removed products that never sold', concept: 'Filters on the optional side must go inside the join (or into a subquery), never after it.' },
         { re: "left\\s+join\\s+orders\\s+\\w+\\s+on[^;]*status\\s*=\\s*'completed'", cat: 'Joins', msg: 'The status filter in the second join does not remove the already-matched items', concept: 'order_items rows of cancelled orders still matched the first join. Restrict the set (items of completed orders) before LEFT JOINing it to products.' }],
  P312: [{ re: 'count\\s*\\(\\s*\\*\\s*\\)', cat: 'Joins', msg: 'COUNT(*) counted the empty-course row and repeated enrolments', concept: 'COUNT(DISTINCT e.student_id) is 0 for an unmatched course and counts each student once.' }],
  P313: [{ re: 'count\\s*\\(\\s*\\*\\s*\\)', cat: 'Joins', msg: 'COUNT(*) reports 1 subscription for users who never paid', concept: 'After a LEFT JOIN, count a column from the optional side: COUNT(s.sub_id) is 0 when nothing matched.' }],
  P314: [{ re: 'full\\s+(outer\\s+)?join', absent: true, cat: 'Joins', msg: 'A one-sided join cannot show rows that exist only in the other table', concept: 'To find unmatched rows in both directions use FULL OUTER JOIN and test each side for NULL.' }],
  P315: [{ re: 'group\\s+by', absent: true, cat: 'Fan-out', msg: 'Settlement lines were joined without being totalled per reference', concept: 'One ledger row matches several settlement lines. Aggregate lines to one row per ref before joining.' }],
  P316: [{ re: 'where[\\s\\S]*status', cat: 'Joins', msg: 'The WHERE on status removed students with no completed courses', concept: 'Put the status condition in the ON clause of the LEFT JOIN.' }],
  P317: [{ re: 'full\\s+(outer\\s+)?join', absent: true, cat: 'Joins', msg: 'This join shows orphans from one side only', concept: 'Empty departments AND unassigned employees both need to appear: FULL OUTER JOIN.' }],
  P320: [{ re: "status\\s*=\\s*'completed'", absent: true, cat: 'Business logic', msg: 'Customers with only cancelled/returned/pending orders were missed', concept: '"Never completed" needs the status inside the match condition (ON or NOT EXISTS), not just "has any order".' }],
  P321: [{ re: 'distinct|exists', absent: true, cat: 'Joins', msg: 'Customers are repeated once per matching line item', concept: 'Use EXISTS (a semi-join) or DISTINCT so each customer appears once.' }],
  P322: [{ re: 'status\\s*<>\\s*\'withdrawn\'|status\\s*!=\\s*\'withdrawn\'', cat: 'Logic', msg: 'Filtering to "not withdrawn" rows keeps students who did withdraw elsewhere', concept: 'Negate the existence (NOT EXISTS a withdrawn row), not the row filter.' }],
  P323: [{ re: 'term', absent: true, cat: 'Business logic', msg: 'The term 2026S was never applied', concept: 'The term is part of the match: LEFT JOIN … ON … AND e.term = \'2026S\' WHERE e.course_id IS NULL.' }],
  P324: [{ re: 'status\\s*<>\\s*\'completed\'', cat: 'Logic', msg: 'Selected drivers with any non-completed trip instead of no completed trip', concept: 'The opposite of "has a completed trip" is "has none": NOT EXISTS.' }],
  P325: [{ re: 'not\\s+in', cat: 'NULL handling', msg: 'NOT IN returns nothing when the subquery contains a NULL', concept: 'The CTO has manager_id NULL. Use NOT EXISTS, or filter NULLs out of the subquery.' }],
  P326: [{ re: 'event_name\\s*<>|event_name\\s*!=', cat: 'Logic', msg: 'Kept users who have any other event, including those who created a project', concept: 'Negate the existence of a create_project event, not the row filter.' }],
  P327: [{ re: 'having|exists[\\s\\S]*exists|intersect', absent: true, cat: 'Logic', msg: 'IN (…) finds students with either course, not both', concept: 'Require both: GROUP BY student HAVING COUNT(DISTINCT course_id) = 2, or two EXISTS.' }],
  P357: [{ re: 'not\\s+in', cat: 'NULL handling', msg: 'NOT IN returned nothing because settlements contain a NULL ref', concept: 'One NULL in the subquery makes NOT IN unknown for every row. Use NOT EXISTS.' }],
  P358: [{ re: 'rated_by', absent: true, cat: 'Logic', msg: 'A driver-side rating was treated as a rider rating', concept: 'Include rated_by = \'rider\' in the match before negating it.' }],
  P330: [{ re: '\\bc\\.customer_id\\s*=\\s*r\\.referred_by|\\br\\.referred_by\\s*=\\s*c\\.customer_id', cat: 'Joins', msg: 'The referrer/referred sides are swapped', concept: 'The row holding referred_by is the referred customer; it points to the referrer\'s customer_id.' }],
  P331: [{ re: 'left\\s+(outer\\s+)?join', absent: true, cat: 'Joins', msg: 'INNER JOINs drop everyone with a shorter reporting chain', concept: 'Use LEFT JOIN at every level so the top of the hierarchy is kept.' }],
  P332: [{ re: '<>|!=', cat: 'Joins', msg: 'Each pair appears twice, as (A,B) and (B,A)', concept: 'Use a strict inequality on the id (b.emp_id > a.emp_id) to keep one orientation.' }],
  P333: [{ re: 'trip_id\\s*(<>|!=)', cat: 'Joins', msg: 'Pairs are listed in both directions with no time order', concept: 'Require the second request to be later than the first so each pair appears once.' }],
  P334: [{ re: 'left\\s+(outer\\s+)?join', cat: 'Joins', msg: 'People with no reports were listed as managers', concept: 'Only managers were asked for: INNER JOIN drops employees nobody reports to.' }],
  P335: [{ re: 'prereq_id', absent: true, cat: 'Joins', msg: 'The prerequisite title was never joined through prereq_id', concept: 'Join courses once on course_id and a second time on prereq_id.' }],
  P336: [{ re: 'count\\s*\\(\\s*\\*\\s*\\)', cat: 'Joins', msg: 'COUNT(*) reports 1 referral for customers who referred nobody', concept: 'Count a column of the optional side: COUNT(r.customer_id).' }],
  P359: [{ re: '<>|!=', cat: 'NULL handling', msg: 'Employees without a department vanished: NULL <> 1 is unknown', concept: 'Use IS DISTINCT FROM to compare values that may be NULL.' }],
  P340: [{ re: 'cross\\s+join|,\\s*products', absent: true, cat: 'Joins', msg: 'Combinations with no sales are missing — no scaffold of all city × category pairs', concept: 'Zeros need a generated grid (CROSS JOIN of the dimensions) to LEFT JOIN the sales onto.' }],
  P341: [{ re: 'cross\\s+join|,\\s*courses', absent: true, cat: 'Joins', msg: 'Only courses that already have an enrolment row can be found', concept: 'A missing course has no row. Generate student × required-course pairs, then anti-join the passes.' }],
  P350: [{ re: 'sum\\s*\\(\\s*distinct', cat: 'Fan-out', msg: 'SUM(DISTINCT credits) merges different courses that share the same credit value', concept: 'Deduplicate (student, course) pairs first, then sum credits.' }],
  P351: [{ re: 'with\\s+\\w+\\s+as|\\(\\s*select[\\s\\S]*group\\s+by', absent: true, cat: 'Fan-out', msg: 'Events and subscriptions multiplied each other', concept: 'Aggregate each child table to one row per user before joining them to users.' }],
  P352: [{ re: 'count\\s*\\(\\s*distinct', absent: true, cat: 'Fan-out', msg: 'Orders and products were counted per line item', concept: 'After joining order_items use COUNT(DISTINCT order_id) and COUNT(DISTINCT product_id).' }],
  P353: [{ re: 'with\\s+\\w+\\s+as|\\(\\s*select[\\s\\S]*group\\s+by|count\\s*\\(\\s*distinct', absent: true, cat: 'Fan-out', msg: 'Courses were counted per enrolment row, so the average collapsed', concept: 'Pre-aggregate enrolments per course before joining to courses.' }],
  P354: [{ re: 'count\\s*\\(\\s*distinct', absent: true, cat: 'Fan-out', msg: 'Students taking two courses with the same instructor were counted twice', concept: 'Count people with COUNT(DISTINCT student_id), not enrolment rows.' }],
  P355: [{ re: '<>|!=', cat: 'Joins', msg: 'Each pair appears in both orders', concept: 'Use b.product_id > a.product_id to get each unordered pair once.' }],
  P356: [{ re: 'with\\s+\\w+\\s+as|from\\s*\\(\\s*select', absent: true, cat: 'Fan-out', msg: 'Averaged line items instead of orders', concept: 'Collapse to one row per order first, then take the average of those.' }],
  P360: [{ re: 'count\\s*\\(\\s*distinct', absent: true, cat: 'Fan-out', msg: 'Orders were counted per line item', concept: 'An order with several lines in one category is one order: COUNT(DISTINCT order_id).' }],
  P361: [{ re: 'with\\s+\\w+\\s+as|\\(\\s*select[\\s\\S]*group\\s+by|exists', absent: true, cat: 'Fan-out', msg: 'One row per payment attempt instead of per order', concept: 'Collapse payments to one row per order (did any succeed?) before joining.' }],
  P362: [{ re: 'left\\s+join\\s+order_items', absent: true, cat: 'Joins', msg: 'A later INNER JOIN turned the LEFT JOIN chain back into an inner join', concept: 'Every join after an outer join that depends on it must also be outer.' }],
  P363: [{ re: 'left\\s+join\\s+drivers', absent: true, cat: 'Joins', msg: 'Unassigned trips disappeared (NULL driver_id never matches)', concept: 'Driver is optional: LEFT JOIN drivers and COALESCE the name.' }],
  P364: [{ re: 'left\\s+join\\s+grade_bands', absent: true, cat: 'Joins', msg: 'Enrolments without a grade were dropped by the band join', concept: 'Ungraded rows match no band; the range join must be a LEFT JOIN.' },
         { re: 'left\\s+join\\s+instructors', absent: true, cat: 'Joins', msg: 'Courses without an instructor were dropped', concept: 'Instructor is optional: LEFT JOIN instructors.' }],
  P365: [{ re: "end_date\\s*>\\s*(date|')", cat: 'Edge cases', msg: 'End date treated as exclusive, and open-ended subscriptions (NULL) were dropped', concept: 'end_date is the last active day: end_date >= date OR end_date IS NULL.' }],
  P366: [{ re: 'with\\s+\\w+\\s+as|\\(\\s*select[\\s\\S]*group\\s+by', absent: true, cat: 'Fan-out', msg: 'Items and payment attempts multiplied each other', concept: 'Aggregate order_items and payments each to one row per order before joining.' },
         { re: "status\\s*=\\s*'success'", absent: true, cat: 'Business logic', msg: 'Failed payment attempts were counted as collected', concept: 'Only successful payments are money received.' }],
  P367: [{ re: 'with\\s+\\w+\\s+as|\\(\\s*select[\\s\\S]*group\\s+by', absent: true, cat: 'Fan-out', msg: 'The ledger amount was repeated once per settlement line', concept: 'Total settlements per ref first so each ledger row joins to exactly one row.' }],
  // Levels 3–4
  P400: [{ re: 'is_active', absent: true, cat: 'Business logic', msg: 'Benchmark average included inactive products', concept: 'The subquery needs the same population filter as the question.' }],
  P401: [{ re: 'avg\\s*\\(\\s*quantity', cat: 'Aggregation', msg: 'Benchmarked against the average line value, not the average customer spend', concept: 'Aggregate to customer grain first, then average those totals.' }],
  P402: [{ re: "status\\s*=\\s*'completed'", absent: true, cat: 'Business logic', msg: 'Orders that were not completed were included', concept: 'Add the completed filter inside the subquery.' }],
  P403: [{ re: "status\\s*=\\s*'delivered'[\\s\\S]*\\(\\s*select\\s+avg\\s*\\([^)]*\\)\\s+from\\s+deliveries\\s*\\)", cat: 'Business logic', msg: 'Benchmark average included cancelled orders', concept: 'Filter the subquery to delivered orders too.' }],
  P404: [{ re: 'offset', cat: 'Logic', msg: 'OFFSET 1 returns the second row, which is a tie of the top salary', concept: 'Use the max of values below the max, or DENSE_RANK.' }],
  P405: [{ re: 'withdrawn', absent: true, cat: 'Business logic', msg: 'Withdrawn enrolments were counted', concept: 'Exclude withdrawals in both the counts and the average.' }],
  P410: [{ re: '\\.city\\s*=', absent: true, cat: 'Logic', msg: 'Compared with the global average instead of the city average', concept: 'Correlate the subquery on city.' }],
  P411: [{ re: 'max\\s*\\(\\s*\\w*\\.?order_id', cat: 'Logic', msg: 'Used the highest order id as "latest"', concept: 'Latest means by date; ids need not follow time.' }],
  P412: [{ re: 'dept_id\\s*=', absent: true, cat: 'Logic', msg: 'Compared with the company-wide maximum', concept: 'Correlate the MAX on dept_id.' }],
  P413: [{ re: 'x\\.user_id|\\w+\\.user_id\\s*=\\s*e\\.user_id', absent: true, cat: 'Logic', msg: 'Took the earliest event overall instead of per user', concept: 'Correlate the MIN on user_id.' }],
  P414: [{ re: 'category\\s*=', absent: true, cat: 'Logic', msg: 'Compared with the overall average, not the category average', concept: 'Correlate on category.' }],
  P415: [{ re: 'abs\\s*\\(', absent: true, cat: 'Logic', msg: 'Signed amounts compared; debits are negative', concept: 'Compare absolute amounts, per account.' }],
  P420: [{ re: 'exists|distinct|\\bin\\s*\\(', absent: true, cat: 'Joins', msg: 'Customers repeat once per failed payment', concept: 'Use EXISTS (or IN / DISTINCT) so each customer appears once.' }],
  P421: [{ re: 'not\\s+in', cat: 'NULL handling', msg: 'NOT IN returns nothing because courses.instructor_id contains NULL', concept: 'Use NOT EXISTS or exclude NULLs.' }],
  P422: [{ re: 'withdrawn', absent: true, cat: 'Business logic', msg: 'Withdrawn enrolments were counted', concept: 'Exclude status = withdrawn inside the EXISTS.' }],
  P423: [{ re: 'not\\s+exists', absent: true, cat: 'Logic', msg: '"Nobody earns less" was approximated by "someone earns enough"', concept: 'Express "for all" as NOT EXISTS of a counter-example.' }],
  P424: [{ re: 'event_time\\s*<', absent: true, cat: 'Business logic', msg: 'The invite was not required to come before the upgrade', concept: 'Compare the invite time with the upgrade time inside the subquery.' }],
  P425: [{ re: 'not\\s+in', cat: 'NULL handling', msg: 'NOT IN returns nothing because referred_by contains NULL', concept: 'Use NOT EXISTS or exclude NULLs.' }],
  P430: [{ re: 'union\\s+all', cat: 'Logic', msg: 'UNION ALL kept duplicate cities', concept: 'UNION removes duplicates.' }],
  P431: [{ re: 'intersect|having|exists', absent: true, cat: 'Logic', msg: 'IN (…) finds customers with either category, not both', concept: 'Use INTERSECT, or require both with HAVING COUNT(DISTINCT category) = 2.' }],
  P432: [{ re: 'except|not\\s+exists|not\\s+in', absent: true, cat: 'Logic', msg: 'Customers who also have completed orders were kept', concept: 'Subtract customers with a completed order (EXCEPT / NOT EXISTS).' }],
  P433: [{ re: 'left\\s+join', absent: true, cat: 'NULL handling', msg: 'Employees without a department were left out of the per-department rows', concept: 'LEFT JOIN and label the NULL department.' }],
  P434: [{ re: 'union', absent: true, cat: 'Logic', msg: 'Only one direction of the difference was found', concept: '(A EXCEPT B) UNION (B EXCEPT A).' }],
  P440: [{ re: 'avg\\s*\\(\\s*quantity', cat: 'Aggregation', msg: 'Benchmark used the average line value, not the average customer spend', concept: 'Average the per-customer totals.' }],
  P441: [{ re: 'with\\s+\\w+\\s+as|distinct', absent: true, cat: 'Fan-out', msg: 'Several create_project events inflated the counts', concept: 'Reduce to one row per qualifying user before joining.' }],
  P442: [{ re: "status\\s*=\\s*'completed'", absent: true, cat: 'Business logic', msg: 'Trips of every status were counted', concept: 'Only completed trips count.' }],
  P443: [{ re: "status\\s*=\\s*'completed'", absent: true, cat: 'Business logic', msg: 'Revenue included non-completed orders', concept: 'Filter to completed orders.' }],
  P444: [{ re: 'avg\\s*\\(\\s*mins', cat: 'Aggregation', msg: 'Compared with the average of restaurant averages, not the average over orders', concept: 'Order-weighted and restaurant-weighted averages differ.' }],
  P445: [{ re: 'count\\s*\\(|having', absent: true, cat: 'Business logic', msg: 'Customers with a single order were included', concept: 'Keep customers with COUNT(*) >= 2.' }],
  P450: [{ re: 'recursive', absent: true, cat: 'Logic', msg: 'Only the first level was returned', concept: 'The hierarchy depth is unknown: use WITH RECURSIVE.' }],
  P451: [{ re: 'recursive', absent: true, cat: 'Logic', msg: 'Only the direct manager was found', concept: 'Keep following manager_id upwards with a recursive CTE.' }],
  P452: [{ re: 'recursive', absent: true, cat: 'Logic', msg: 'Used the direct referrer instead of the root of the chain', concept: 'Carry the root down a recursive CTE.' }],
  P453: [{ re: 'recursive', absent: true, cat: 'Logic', msg: 'Indirect prerequisites were missed', concept: 'Prerequisites of prerequisites need a recursive CTE.' }],
  P454: [{ re: 'recursive|generate_series', absent: true, cat: 'Joins', msg: 'Days with no trips are missing', concept: 'Generate the dates, then LEFT JOIN trips.' }],
  P455: [{ re: 'recursive', absent: true, cat: 'Logic', msg: 'Only direct reports were counted', concept: 'Build (ancestor, descendant) pairs recursively, then count.' }],
  P456: [R('in\\s*\\(\\s*\\d', 'Logic', 'Department ids were hard-coded', 'Use IN (SELECT dept_id FROM departments WHERE …) so the query follows the data.')],
  P457: [R('not\\s+exists|not\\s+in|except', 'Logic', 'Joining to non-cancelled rows keeps restaurants that also had cancellations', 'Negate the existence of a cancelled order.', true)],
  P458: [R('\\(\\s*select\\s+avg\\s*\\(\\s*value\\s*\\)\\s+from\\s+ov\\s*\\)', 'Logic', 'Compared with the global average instead of the customer\'s own', 'Correlate the benchmark on customer_id.')],
  P459: [R('event_time\\s*>', 'Business logic', 'The login was not required to come after the upgrade', 'Compare event times inside the EXISTS.', true)],
  P460: [R('except|not\\s+exists|not\\s+in', 'Logic', 'February buyers were not removed', 'Subtract February customers (EXCEPT / NOT EXISTS).', true)],
  P461: [R('avg\\s*\\(\\s*fare', 'Aggregation', 'Compared city totals with the average trip fare', 'Benchmark and compared values must be at the same grain.')],
  P462: [R('left\\s+join', 'Joins', 'Accounts missing credits or debits were dropped', 'Start from accounts and LEFT JOIN each CTE.', true)],
  P463: [R('recursive', 'Logic', 'Only a two-name path was built', 'Accumulate the path with a recursive CTE.', true)],
  P464: [R('recursive', 'Logic', 'Generations beyond the first were not followed', 'Track depth in a recursive CTE.', true)],
  P465: [R('avg\\s*\\(\\s*avg_salary', 'Aggregation', 'Compared with the average of department averages', 'The company-wide average is over employees.')],
  // Level 5
  P500: [R('row_number', 'Window functions', 'ROW_NUMBER gives tied salaries different ranks', 'Use RANK/DENSE_RANK when equal values should tie.')],
  P501: [R('row_number', 'Window functions', 'ROW_NUMBER cut tied employees at the boundary', 'Use RANK <= N to keep everyone tied within the top N.')],
  P502: [R('group\\s+by', 'Aggregation', 'Ranked single order lines instead of product revenue totals', 'Aggregate to product revenue first, then rank.', true)],
  P503: [R('\\brank\\s*\\(', 'Window functions', 'RANK leaves gaps after ties, so rank 3 may not exist', 'Use DENSE_RANK for the N-th distinct value.')],
  P504: [R('requested_at\\s*,\\s*trip_id\\s*\\)', 'Window functions', 'Sorted ascending, so this is the first trip, not the latest', 'ORDER BY … DESC for the latest row.')],
  P505: [R('order\\s+by\\s+order_id\\s*\\)', 'Logic', 'Ordered by id, not by date', 'Ids need not follow time; order by order_date first.')],
  P506: [R('\\brank\\s*\\(', 'Window functions', 'RANK returns both rows when values tie', 'Add a tie-breaker and use ROW_NUMBER for exactly one row.')],
  P507: [R('row_number', 'Window functions', 'ROW_NUMBER dropped courses tied for the best grade', 'RANK = 1 keeps ties.')],
  P508: [R('event_time', 'Edge cases', 'Duplicate key too small: legitimate repeat events were removed', 'Partition by user, event name AND exact time.', true)],
  P509: [R('limit', 'Window functions', 'LIMIT 3 cuts tied customers', 'Rank, then keep rank <= 3.')],
  P510: [R('where', 'Business logic', 'Cancelled trips (NULL fares) were bucketed too', 'Filter before the window runs.', true)],
  P511: [R('row_number', 'Window functions', 'ROW_NUMBER = 2 can return a tied top earner', 'Use DENSE_RANK = 2.')],
  P512: [R('over\\s*\\(\\s*order\\s+by', 'Window functions', 'LAG without PARTITION BY compares across customers', 'PARTITION BY customer_id.')],
  P513: [R('over\\s*\\(\\s*order\\s+by', 'Window functions', 'LAG without PARTITION BY compares across users', 'PARTITION BY user_id.')],
  P514: [R('<\\s*30\\b', 'Edge cases', 'The 30-day boundary was excluded', '"30 days or fewer" is <= 30.')],
  P515: [R('lead\\s*\\(', 'Window functions', 'LEAD compares with the next day, not the previous one', 'Use LAG for "versus previous".')],
  P516: [R('where\\s+rating\\s+is\\s+not\\s+null', 'NULL handling', 'Unrated orders became the "previous rating"', 'Filter NULL ratings before LAG runs.', true)],
  P517: [R('exists', 'Business logic', 'Any later upgrade was accepted, not the immediately next event', 'LEAD(event_name) exposes the next event.')],
  P518: [R('over\\s*\\(\\s*order\\s+by', 'Window functions', 'LEAD without PARTITION BY crosses departments', 'PARTITION BY dept_id.')],
  P519: [R('over\\s*\\(\\s*order\\s+by', 'Window functions', 'LAG without PARTITION BY mixes users', 'PARTITION BY user_id.')],
  P520: [R('over\\s*\\(\\s*\\)', 'Window functions', 'No ORDER BY inside OVER: grand total on every row', 'ORDER BY inside OVER makes the sum running.')],
  P521: [R('over\\s*\\(\\s*\\)', 'Window functions', 'Share of the grand total instead of the customer total', 'PARTITION BY customer_id.')],
  P522: [R('over\\s*\\(\\s*\\)', 'Window functions', 'Company average used instead of department average', 'PARTITION BY dept_id.')],
  P523: [R('over\\s*\\(\\s*partition\\s+by\\s+driver_id\\s*\\)', 'Window functions', 'No ORDER BY: every row shows the driver\'s total', 'Add ORDER BY inside OVER for a running count.')],
  P524: [R('over\\s*\\(\\s*order\\s+by', 'Window functions', 'Running balance mixes accounts', 'PARTITION BY account_id.')],
  P525: [R('\\(\\s*select\\s+sum\\s*\\(\\s*order_value', 'Business logic', 'Denominator included cancelled orders', 'Use SUM(SUM(x)) OVER () so numerator and denominator match.')],
  P526: [R('over\\s*\\(\\s*\\)', 'Window functions', 'Share of the grand total instead of the category', 'PARTITION BY category.')],
  P527: [R('order\\s+by\\s+emp_id\\s*\\)', 'Window functions', 'Accumulated in id order, not hire-date order', 'ORDER BY hire_date inside OVER.')],
  P528: [R('over\\s*\\(\\s*order\\s+by', 'Window functions', 'Numbering ignores country', 'PARTITION BY country.')],
  P529: [R('rows\\s+between', 'Window functions', 'No frame: this is a running average, not 3 rows', 'ROWS BETWEEN 2 PRECEDING AND CURRENT ROW.', true)],
  P530: [R('following', 'Window functions', 'The window peeks into the next day', 'A trailing window ends at CURRENT ROW.')],
  P531: [R('last_value', 'Window functions', 'LAST_VALUE with the default frame returns the current row', 'Use FIRST_VALUE with DESC, or widen the frame.')],
  P532: [R('over\\s*\\(\\s*partition\\s+by\\s+restaurant_id\\s*\\)', 'Window functions', 'No ORDER BY: the overall maximum on every row', 'Add ORDER BY for a running maximum.')],
  P533: [R('signup_date', 'Business logic', '"New" was based on signup month, not first order', 'Number each customer\'s orders and treat #1 as new.')],
  P534: [R('rows\\s+between', 'Window functions', 'ROWS counts rows, not time', 'RANGE BETWEEN INTERVAL \'24 hours\' PRECEDING AND CURRENT ROW.')],
  P535: [R('order\\s+by\\s+salary\\s*,\\s*emp_id', 'Logic', 'Sorted ascending: this is the second-LOWEST paid', 'ORDER BY salary DESC.')],
  P536: [R('\\)\\s*/\\s*revenue', 'Logic', 'Divided by the new month instead of the previous one', 'Growth is relative to the previous value.')],
  P537: [R('distinct', 'Edge cases', 'Duplicate pings on one day broke the streaks', 'Reduce to distinct active days first.', true)],
  P538: [R('row_number', 'Logic', 'Active days were counted, not consecutive streaks', 'Build islands (date − row number), then take the max.', true)],
  P539: [R('row_number', 'Logic', '3 active days is not 3 consecutive days', 'Group into islands and test the island length.', true)],
  P540: [R('over\\s*\\(\\s*order\\s+by', 'Window functions', 'LEAD without PARTITION BY crosses users', 'PARTITION BY user_id.')],
  P541: [R('distinct', 'Edge cases', 'Two trips on one day broke the streaks', 'One row per rider-day before numbering.', true)],
  P542: [R('distinct', 'Edge cases', 'Two orders in one month broke the streaks', 'One row per customer-month before numbering.', true)],
  P543: [R('row_number', 'Logic', 'Debits were totalled, not split into runs', 'Subtract per-sign row number from the overall row number.', true)],
  P544: [R('over\\s*\\(\\s*order\\s+by', 'Window functions', 'LAG without PARTITION BY crosses users', 'PARTITION BY user_id.')],
  // Level 6
  P600: [R('date_trunc', 'Dates/time', 'Grouped by day, not by week', "date_trunc('week', d) maps every date to its Monday.", true)],
  P601: [R('current_date|now\\s*\\(', 'Dates/time', 'Used today\'s date, so the answer changes every day', 'Use the fixed as-of date given in the question.')],
  P602: [R('order\\s+by\\s+1', 'Dates/time', 'Weekday names sorted alphabetically', 'Sort by EXTRACT(isodow …) for calendar order.')],
  P603: [R('-\\s*30', 'Dates/time', 'A rolling 30 days was used instead of the previous calendar month', 'Use month boundaries with date_trunc.')],
  P604: [R('generate_series', 'Joins', 'Months with no signups are missing', 'Generate the months, then LEFT JOIN.', true)],
  P605: [R("where[^;]*status\\s*=\\s*'success'", 'Business logic', 'Failed attempts were not excluded before taking the first payment', 'Filter to successful payments first.', true)],
  P606: [R('between', 'Dates/time', 'BETWEEN 22 AND 6 is an empty range', 'A window that wraps midnight needs OR.')],
  P607: [R('extract\\s*\\(\\s*year\\s+from\\s+date', 'Dates/time', 'Subtracting year numbers counts calendar years, not completed years', 'Use age().')],
  P608: [R('between', 'Dates/time', 'BETWEEN … AND \'03-31\' drops most of 31 March', 'Use a half-open interval.')],
  P609: [R('extract\\s*\\(\\s*day', 'Dates/time', 'The last day of the month was hard-coded', 'Compute it from the next month\'s start.')],
  P610: [R('event_time\\s*;?\\s*$', 'Logic', 'Sorted ascending: this keeps the earliest login', 'ORDER BY … DESC for the latest.')],
  P611: [R('row_number', 'Logic', 'Any repeat counted as a duplicate, regardless of time gap', 'Duplicates are defined by time proximity: compare with LAG.')],
  P612: [R('having', 'Logic', 'Counted original rows as well as surplus copies', 'Surplus = total rows − distinct rows.')],
  P613: [R('max\\s*\\(\\s*driver_id', 'Logic', 'MAX(driver_id) is the largest id, not the most frequent driver', 'Count per rider-driver pair, then keep the top.')],
  P614: [R('distinct\\s+on', 'Logic', 'Kept the latest attempt (term text), not the best grade', 'Survivor rule is highest grade: MAX(grade).')],
  P615: [R('row_number', 'Logic', 'Every successful payment was kept, not just the first', 'Number payments within each order.', true)],
  P616: [R('avg\\s*\\(', 'Aggregation', 'The mean was used instead of the median', 'PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY …).')],
  P617: [R('percentile_disc', 'Aggregation', 'PERCENTILE_DISC returns an existing value, not the interpolated median', 'Use PERCENTILE_CONT for even counts.')],
  P618: [R('max\\s*\\(', 'Aggregation', 'MAX is not the 90th percentile', 'PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY fare).')],
  P619: [R('percentile_disc', 'Aggregation', 'PERCENTILE_DISC instead of the interpolated percentile', 'Use PERCENTILE_CONT.')],
  P620: [R('order\\s+by\\s+amount\\s*\\)', 'Logic', 'Percentile taken on signed amounts, ignoring large debits', 'Take ABS(amount) before the percentile.')],
  P621: [R('avg\\s*\\(', 'Aggregation', 'The mean was used instead of the median', 'PERCENTILE_CONT(0.5).')],
  P622: [R('is\\s+not\\s+null', 'NULL handling', 'Events with no properties at all were excluded', 'A NULL document also has no template.')],
  P623: [R("event_name\\s*=\\s*'upgrade'", 'Business logic', 'Other event types formed a NULL plan group', 'Filter to upgrade events first.', true)],
  P624: [R('distinct', 'Aggregation', 'Repeated categories appear several times', 'STRING_AGG(DISTINCT …).', true)],
  P625: [R('jsonb_object_keys', 'Logic', 'Keys were hard-coded instead of discovered', 'Explode keys with jsonb_object_keys.', true)],
  P626: [R('is\\s+not\\s+null', 'NULL handling', 'The latest event may have no device: filter missing values first', "WHERE properties->>'device' IS NOT NULL before picking the latest.", true)],
  P627: [R('order\\s+by\\s+o\\.order_date\\s*,\\s*o\\.order_id\\s+limit', 'Logic', 'Took the oldest two orders, not the latest', 'ORDER BY … DESC.')],
  P628: [R('left\\s+join\\s+lateral', 'Joins', 'Drivers without a completed trip disappeared', 'LEFT JOIN LATERAL … ON true keeps them.', true)],
  P629: [R('left\\s+join\\s+lateral', 'Joins', 'Departments with no employees disappeared', 'LEFT JOIN LATERAL … ON true keeps them.', true)],
  P630: [R('desc', 'Logic', 'Took the last two events, not the first two', 'ORDER BY event_time ascending.')],
  P631: [R("status\\s*=\\s*'completed'", 'NULL handling', 'Ungraded rows sorted first (NULL is the largest value)', 'Filter to completed rows before ORDER BY grade DESC.', true)],
  P632: [R('limit', 'Logic', 'The "3 most recent" restriction was ignored', 'Apply LIMIT 3 per restaurant before averaging (LATERAL).', true)],
  P633: [R('coalesce', 'NULL handling', 'Absent combinations are NULL, not 0', 'Wrap each conditional SUM in COALESCE(…, 0).', true)],
  P634: [R('filter|case', 'Logic', 'Both columns hold the same unconditional count', 'COUNT(*) FILTER (WHERE status = …).', true)],
  P635: [R("'tip'", 'Logic', 'The tip component was left out', 'Add every money column to the VALUES list.', true)],
  P636: [R("status\\s*=\\s*'completed'", 'Business logic', 'Cancelled trips were counted', 'Only completed trips.', true)],
  P637: [R('<=\\s*150000', 'Edge cases', '150000 was counted in the mid band', 'Half-open bands: >= low AND < high.')],
  P638: [R('distinct', 'Fan-out', 'Events were counted instead of distinct users', 'COUNT(DISTINCT user_id) FILTER (…).', true)],
  // Level 7
  P700: [R('count\\s*\\(\\s*\\*\\s*\\)', 'Aggregation', 'Events were counted instead of distinct users', 'A funnel counts people: COUNT(DISTINCT user_id).')],
  P701: [R('first_value', 'Logic', 'Divided by the first step, not the previous step', 'Step-to-step conversion uses LAG.')],
  P702: [R('with\\s+\\w+\\s+as|distinct', 'Fan-out', 'Joining raw events multiplied signups', 'Reduce upgrades to one row per user first.', true)],
  P703: [R('event_time\\s*>', 'Business logic', 'The invite was not required to come after the project within 7 days', 'Order and window both matter.', true)],
  P704: [R('with\\s+\\w+\\s+as', 'Fan-out', 'Segmented on every event instead of the signup event', 'Take the device from the signup event once per user.', true)],
  P705: [R('viewed_at\\s*>', 'Business logic', 'Page order was ignored', 'Require /signup after /pricing.', true)],
  P706: [R('<\\s*\\w+\\.?\\w*\\s*\\+\\s*interval', 'Edge cases', 'The 24-hour boundary was excluded', 'Use <= for an inclusive window.')],
  P710: [R('with\\s+\\w+\\s+as|distinct', 'Fan-out', 'Repeat logins inflated the cohort counts', 'Count users, not login events.', true)],
  P711: [R('distinct\\s+c\\.user_id\\)\\s+as\\s+users', 'Fan-out', 'Several events in the month counted a user several times', 'Count each retained user once (DISTINCT).')],
  P712: [R('customers\\s+cu', 'Business logic', 'Cohorts were based on signup month, not first order', 'Cohort = month of the first completed order.')],
  P713: [R("status\\s*=\\s*'completed'", 'Business logic', 'Cancelled orders counted as the first order', 'Only completed orders are purchases.', true)],
  P714: [R('distinct', 'Aggregation', 'Events were counted instead of distinct months', 'COUNT(DISTINCT month) per user, then count users.', true)],
  P715: [R('signup_date', 'Business logic', 'Cohorts were taken from signup month, not first order', 'The cohort is the first-order month.')],
  P716: [R('case\\s+when', 'Edge cases', 'Unobserved months were shown as 0 instead of empty', 'A not-yet-observed cell is NULL, not zero.', true)],
  P720: [R('where', 'Business logic', 'Every subscription row was counted, including ended ones', 'Active = started and not yet ended on that date.', true)],
  P721: [R('end_date\\s*>\\s*m', 'Edge cases', 'The end date was treated as exclusive', 'end_date is the last active day: use >=.')],
  P722: [R("date_trunc\\(\\s*'month'\\s*,\\s*s\\.end_date", 'Business logic', 'Plan changes were counted as churn', 'Churn = active at month start and not active at next month start.')],
  P723: [R('end_date\\s*\\+\\s*1', 'Business logic', 'Gaps (win-backs) were treated as plan changes', 'A plan change starts the day after the previous period ends.', true)],
  P724: [R('having', 'Logic', 'Any account with several periods was treated as a win-back', 'Measure the gap between one end and the next start.')],
  P725: [R('distinct\\s+on', 'Business logic', 'Every subscription start was counted as new business', 'Only each account\'s first subscription is new.', true)],
  P726: [R('coalesce', 'NULL handling', 'MAX(end_date) ignores NULL, so still-active accounts looked churned', 'Treat NULL end dates explicitly.', true)],
  P727: [R('signup_date', 'Business logic', 'Account age was used instead of time on the current plan', 'Measure from the subscription start.')],
  P730: [R('>=\\s*interval', 'Edge cases', 'A gap of exactly 30 minutes started a new session', 'Only MORE than 30 minutes starts a session.')],
  P731: [R('::date', 'Logic', 'Sessions were split by calendar day', 'Use the 30-minute inactivity rule.')],
  P732: [R('count\\s*\\(\\s*\\*\\s*\\)\\s+as\\s+sessions', 'Logic', 'Page views were counted as sessions', 'Sessionize first, then count distinct sessions.')],
  P733: [R('group\\s+by\\s+user_id\\s*,\\s*page', 'Logic', 'Pages seen once were treated as bounce sessions', 'Bounce = a session with one view.')],
  P734: [R('1\\s+as\\s+session_no\\s*,\\s*min', 'Logic', 'Sessions were not identified; whole days per user were compared', 'Sessionize, then compare each session\'s start and end dates.')],
  P735: [R('unbounded\\s+following', 'Window functions', 'LAST_VALUE with the default frame returns the current row', 'Widen the frame to UNBOUNDED FOLLOWING.', true)],
  P736: [R('lag\\s*\\(\\s*st', 'Logic', 'Gap measured start-to-start instead of end-to-start', 'Subtract the previous session\'s END.')],
  P740: [R('generate_series', 'Dates/time', 'Days without activity were missing, so the window skipped them', 'Build a date spine and count empty days as 0.', true)],
  P741: [R('rows\\s+between', 'Window functions', 'A row-count frame was used for a 7-day window', "RANGE BETWEEN INTERVAL '7 days' PRECEDING AND CURRENT ROW.")],
  P742: [R('\\)\\s*/\\s*trips', 'Logic', 'Growth divided by the current week', 'Divide by the previous week.')],
  P743: [R('rows\\s+between', 'Window functions', 'Sparse dates make a row-count window wrong', 'Use a RANGE window with an interval.')],
  P744: [R('over\\s*\\(\\s*order\\s+by', 'Window functions', 'The moving average mixed customers', 'PARTITION BY customer_id.')],
  P745: [R('avg\\s*\\(', 'Aggregation', 'Averaged only days that have activity', 'Divide total user-days by all 31 days.')],
  P750: [R('from\\s+customers\\s+c\\s+left\\s+join', 'Business logic', 'Zero-spend customers were included in the tiers', 'Tier only customers with spend.')],
  P751: [R('cum\\s*<=', 'Logic', 'The customer who crosses 80% was left out', 'Include customers while the share BEFORE them is below 80%.')],
  P752: [R('order\\s+by\\s+category\\s*\\)', 'Logic', 'Top category chosen alphabetically, not by spend', 'ORDER BY spend DESC first.')],
  P753: [R('count\\s*\\(\\s*\\*\\s*\\)\\s+as\\s+units', 'Logic', 'Line items were counted instead of units', 'SUM(quantity) is the number of units.')],
  P754: [R('left\\s+join', 'Joins', 'Dormant customers (including never-ordered) were dropped', 'LEFT JOIN the recent buyers and flag the rest.', true)],
  P755: [R("event_name\\s*<>", 'Business logic', 'The signup event was counted as activity', 'Exclude signup from the metric.', true)],
  P756: [R("when\\s+trips\\s*>=\\s*3\\s+then\\s+'silver'\\s+when", 'Business logic', 'Silver was tested before gold, so nobody is gold', 'Test the strictest tier first.')],
  P760: [R('over\\s*\\(\\s*\\)', 'Window functions', 'Mean and deviation were pooled across accounts', 'PARTITION BY account_id.')],
  P761: [R('rows\\s+between', 'Window functions', 'The previous 2 rows were used, ignoring how far apart they are', "RANGE BETWEEN INTERVAL '10 minutes' PRECEDING AND CURRENT ROW.")],
  P762: [R('avg\\s*\\(', 'Aggregation', 'The mean was used as baseline, inflated by the outliers', 'Use the median (PERCENTILE_CONT 0.5).')],
  P763: [R('having\\s+count\\s*\\(\\s*\\*\\s*\\)\\s*>=\\s*2', 'Logic', 'All attempts were counted, including the successful one', "COUNT(*) FILTER (WHERE status = 'failed').")],
  P764: [R("status\\s*=\\s*'success'", 'Business logic', 'Failed attempts were counted as paid', 'Only successful payments are money received.', true)],
  P765: [R('0\\.3', 'Logic', 'A hard-coded threshold was used', 'Derive the overall rate from the data.')],
  P770: [R('interval\\s*\'7\\s*days\'', 'Business logic', 'Clicks older than 7 days were allowed to claim the purchase', 'Apply the 7-day window.', true)],
  P771: [R('event_time\\s+desc', 'Logic', 'The LAST click was used instead of the first', 'First-click attribution orders ascending.')],
  P772: [R('<\\s*e\\.event_time\\s*\\+', 'Edge cases', 'The 7-day boundary was excluded', 'The window is inclusive.')],
  P773: [R('left\\s+join\\s+\\(', 'Fan-out', 'Revenue of every purchase by a clicker was credited to every campaign they clicked', 'Attribute each purchase to one campaign, then total.')],
  P774: [R('order\\s+by\\s+c\\.ct\\s*,', 'Logic', 'Measured from the first click rather than the attributed (last) click', 'Time from the attributed click.')],
  P775: [R('lc\\b|campaign_id\\s*<>', 'Logic', 'The last-click campaign was counted as an assist too', 'Assists exclude the credited campaign.', true)],
  P776: [R('count\\s*\\(\\s*distinct', 'Fan-out', 'Averaged line items, not order values', 'Collapse to order value first.')],
  P777: [R('<=\\s*date\\s*\'2026-04-30\'\\s*-\\s*30', 'Business logic', 'Users with incomplete windows were included and no 30-day limit applied', 'Censor users whose window is still open and limit upgrades to 30 days.', true)],
};
