// Pattern library: recognition first, syntax second.
export const PATTERNS = [
  { id: 'top_n_per_group', name: 'Top N per group', topics: ['w_ranking', 'x_lateral'],
    clues: ['"for each X, the top/best/latest N"', 'a ranking inside categories', '"including ties" or "pick one"'],
    thinking: 'Aggregate to the grain you rank (e.g. product revenue) → rank within the partition → filter rank in an outer query. Read the tie rule to choose ROW_NUMBER vs RANK vs DENSE_RANK.',
    technique: 'ROW_NUMBER/RANK/DENSE_RANK OVER (PARTITION BY group ORDER BY metric DESC) in a CTE, then WHERE rank <= N. Or LATERAL … LIMIT N.',
    example: `WITH r AS (SELECT *, RANK() OVER (PARTITION BY category ORDER BY revenue DESC) rk FROM product_revenue)
SELECT * FROM r WHERE rk = 1;`,
    mistakes: ['Filtering the rank in the same SELECT\'s WHERE', 'ROW_NUMBER when ties should be kept', 'Ranking raw rows instead of aggregated rows'] },
  { id: 'nth_highest', name: 'N-th highest value', topics: ['w_ranking'],
    clues: ['"second highest"', '"runner-up"', '"after accounting for ties"'],
    thinking: '"N-th highest" usually means N-th distinct value → DENSE_RANK. Confirm what should happen when there is no N-th value.',
    technique: 'DENSE_RANK() = N, or OFFSET N-1 on DISTINCT values (single group only).',
    example: `SELECT salary FROM (SELECT DISTINCT salary FROM employees) s ORDER BY salary DESC OFFSET 1 LIMIT 1;`,
    mistakes: ['RANK skips numbers after ties', 'LIMIT/OFFSET without DISTINCT'] },
  { id: 'dedup', name: 'Deduplication', topics: ['x_dedup'],
    clues: ['"duplicate"', '"keep the first/latest"', 'event streams with retries'],
    thinking: 'Define duplicate key (and time tolerance) → define survivor rule → number rows within the key and keep #1, or flag rows that are close to the previous one.',
    technique: 'ROW_NUMBER() OVER (PARTITION BY key ORDER BY survivor_rule) = 1; DISTINCT ON; LAG for time-window duplicates.',
    example: `SELECT DISTINCT ON (user_id) * FROM events ORDER BY user_id, event_time;`,
    mistakes: ['Grouping by calendar date for time-window duplicates', 'Non-deterministic survivor (no tie-break)'] },
  { id: 'running_total', name: 'Running totals', topics: ['w_aggregate'],
    clues: ['"cumulative"', '"to date"', '"running"'],
    thinking: 'Aggregate to the reporting grain first (one row per day) → SUM() OVER (ORDER BY day).',
    technique: 'SUM(x) OVER (PARTITION BY … ORDER BY t [ROWS UNBOUNDED PRECEDING])',
    example: `SELECT day, rev, SUM(rev) OVER (ORDER BY day) AS running FROM daily;`,
    mistakes: ['Running sum over unaggregated rows', 'RANGE frame merging equal sort keys'] },
  { id: 'rolling_avg', name: 'Rolling / moving metrics', topics: ['w_frames', 'an_rolling'],
    clues: ['"7-day"', '"moving average"', '"trailing"'],
    thinking: 'Is the window in rows or in calendar time? If calendar, build a date spine. Is the metric additive (sum) or not (distinct users)?',
    technique: 'Spine + ROWS BETWEEN n PRECEDING AND CURRENT ROW; non-additive metrics → join each day to its window.',
    example: `AVG(v) OVER (ORDER BY day ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)`,
    mistakes: ['Row frames over gappy dates', 'Summing distinct counts'] },
  { id: 'prev_next', name: 'Previous / next event', topics: ['w_offset'],
    clues: ['"since the previous"', '"time until next"', '"consecutive"'],
    thinking: 'Partition by the entity, order by time, read the neighbour with LAG/LEAD — compute on the full table, filter afterwards.',
    technique: 'LAG/LEAD(col) OVER (PARTITION BY entity ORDER BY time)',
    example: `SELECT *, LEAD(ts) OVER (PARTITION BY user_id ORDER BY ts) AS next_ts FROM events;`,
    mistakes: ['Missing PARTITION BY', 'Filtering before computing the window'] },
  { id: 'gaps_islands', name: 'Gaps & islands (consecutive runs)', topics: ['w_gaps'],
    clues: ['"consecutive days"', '"streak"', '"uninterrupted"'],
    thinking: 'Dedup → date − ROW_NUMBER() is constant inside a run → GROUP BY that key.',
    technique: 'activity_date - ROW_NUMBER() OVER (PARTITION BY user ORDER BY activity_date)::int',
    example: `SELECT user_id, MIN(d), MAX(d), COUNT(*) FROM (SELECT user_id, d, d - ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY d)::int AS g FROM t) x GROUP BY user_id, g;`,
    mistakes: ['Not deduplicating dates', 'Using RANK instead of ROW_NUMBER'] },
  { id: 'funnel', name: 'Funnels', topics: ['an_funnel', 'an_conversion'],
    clues: ['"step"', '"conversion"', '"drop-off"'],
    thinking: 'Define each step, ordering rule and denominator in words first → per-user step timestamps → counts per step.',
    technique: 'Per-user MIN(time) FILTER (WHERE step) or sequential CTEs with time conditions.',
    example: `SELECT COUNT(*) FILTER (WHERE project_at >= signup_at) FROM per_user;`,
    mistakes: ['Ignoring step order', 'Counting events instead of users', 'Wrong denominator'] },
  { id: 'cohort_retention', name: 'Cohort retention', topics: ['an_cohort'],
    clues: ['"retention"', '"cohort"', '"came back"'],
    thinking: 'Cohort = start period. Per user: cohort + activity flags per period → per cohort: share of users. Censor periods not yet observable.',
    technique: 'DATE_TRUNC + per-user flags (BOOL_OR) + COUNT FILTER / COUNT.',
    example: `COUNT(*) FILTER (WHERE retained_m1) * 100.0 / COUNT(*)`,
    mistakes: ['Immature cohorts shown as 0%', 'Counting activity events not users'] },
  { id: 'first_last_event', name: 'First / last event per entity', topics: ['w_frames', 'x_dedup'],
    clues: ['"first purchase"', '"most recent"', '"latest status"'],
    thinking: 'Pick one row per entity by ordered rule. Keep entities without events if the spec says "every".',
    technique: 'DISTINCT ON, ROW_NUMBER = 1, MIN/MAX for scalar values; LAST_VALUE needs a full frame.',
    example: `SELECT DISTINCT ON (user_id) user_id, event_name FROM events ORDER BY user_id, event_time DESC;`,
    mistakes: ['LAST_VALUE with default frame', 'Inner join dropping entities without events'] },
  { id: 'anti_join', name: 'Anti-join ("never did X")', topics: ['j_anti_semi', 's_exists'],
    clues: ['"never"', '"without any"', '"have not"'],
    thinking: 'Entities for which no qualifying row exists. Put all qualifying conditions inside the subquery.',
    technique: 'NOT EXISTS (correlated) or LEFT JOIN … WHERE right.key IS NULL. Avoid NOT IN on nullable columns.',
    example: `SELECT * FROM drivers d WHERE NOT EXISTS (SELECT 1 FROM trips t WHERE t.driver_id = d.driver_id);`,
    mistakes: ['NOT IN with NULLs', 'Condition placed outside the subquery'] },
  { id: 'percentiles', name: 'Percentiles & median', topics: ['x_percentile'],
    clues: ['"median"', '"p90"', '"typical"', 'skewed values'],
    thinking: 'Continuous (interpolated) or discrete (an actual value)? Which rows are in the population?',
    technique: 'PERCENTILE_CONT(p) / PERCENTILE_DISC(p) WITHIN GROUP (ORDER BY x)',
    example: `PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY fare)`,
    mistakes: ['Using AVG as "typical"', 'Rounding double precision without a cast'] },
  { id: 'sessionization', name: 'Sessionization', topics: ['an_session'],
    clues: ['"session"', '"inactivity timeout"', '"visits"'],
    thinking: 'Flag session starts with LAG gap > timeout → running SUM of flags = session id → aggregate.',
    technique: 'CASE WHEN gap > interval THEN 1 END + SUM() OVER (PARTITION BY user ORDER BY t)',
    example: `SUM(is_new) OVER (PARTITION BY user_id ORDER BY ts) AS session_id`,
    mistakes: ['> vs >= at the boundary', 'Splitting at midnight'] },
  { id: 'date_spine', name: 'Date spine (show zeros)', topics: ['x_dates', 'j_cross'],
    clues: ['"every day/month"', '"including zero"', 'charts with gaps'],
    thinking: 'Generate the complete calendar (× dimensions), LEFT JOIN facts, COUNT(column) for zeros.',
    technique: 'generate_series + CROSS JOIN + LEFT JOIN',
    example: `SELECT d::date FROM generate_series(DATE '2026-01-01', DATE '2026-01-31', INTERVAL '1 day') d;`,
    mistakes: ['Grouping facts alone (zeros disappear)', 'COUNT(*) counting the NULL row as 1'] },
  { id: 'conditional_agg', name: 'Conditional aggregation / pivot', topics: ['a_conditional', 'x_pivot'],
    clues: ['"rate"', '"by status as columns"', 'several subset counts in one row'],
    thinking: 'One GROUP BY; each column aggregates a different subset.',
    technique: 'COUNT(*) FILTER (WHERE …), SUM(CASE WHEN … THEN x END)',
    example: `COUNT(*) FILTER (WHERE status = 'completed') * 100.0 / COUNT(*)`,
    mistakes: ['Integer division', 'NULL instead of 0 for empty subsets'] },
  { id: 'fanout_guard', name: 'Pre-aggregate before joining (fan-out guard)', topics: ['j_fanout', 'j_multi'],
    clues: ['two child tables of one parent', 'sums that look too big', '"per order … and payments"'],
    thinking: 'Write down each table\'s grain. Aggregate every child to the parent grain before joining children together.',
    technique: 'CTE per child with GROUP BY parent_key, then join to the parent.',
    example: `WITH i AS (SELECT order_id, SUM(qty) q FROM items GROUP BY 1) SELECT … FROM orders JOIN i USING (order_id);`,
    mistakes: ['Joining two one-to-many tables at once', 'Using COUNT(DISTINCT) to hide inflated sums'] },
  { id: 'pct_of_total', name: 'Share of total', topics: ['w_aggregate'],
    clues: ['"% of total"', '"share"', '"contribution"'],
    thinking: 'Numerator and denominator must come from the same filtered population.',
    technique: 'x / SUM(x) OVER () or x / SUM(SUM(x)) OVER () after GROUP BY',
    example: `ROUND(100.0 * SUM(v) / SUM(SUM(v)) OVER (), 2)`,
    mistakes: ['Denominator from a different filter', 'Integer division'] },
  { id: 'hierarchy', name: 'Hierarchy traversal', topics: ['c_recursive'],
    clues: ['"manager chain"', '"root"', '"all descendants"', 'unknown depth'],
    thinking: 'Anchor at the root(s) → recursive step joins children to found rows → carry depth/path.',
    technique: 'WITH RECURSIVE … UNION ALL …',
    example: `WITH RECURSIVE t AS (SELECT … WHERE parent IS NULL UNION ALL SELECT … FROM x JOIN t ON x.parent = t.id) SELECT * FROM t;`,
    mistakes: ['Fixed number of self-joins', 'No termination on cyclic data'] },
  { id: 'segmentation', name: 'Rule-based segmentation', topics: ['an_segment'],
    clues: ['"segment"', '"bucket customers"', 'ordered business rules'],
    thinking: 'Per-entity features at a fixed as-of date → CASE in the stated precedence.',
    technique: 'LEFT JOIN + aggregates in a CTE, CASE WHEN in rule order.',
    example: `CASE WHEN orders = 0 THEN 'never' WHEN days_since > 45 THEN 'at_risk' … END`,
    mistakes: ['Wrong rule order', 'CURRENT_DATE instead of the as-of date'] },
  { id: 'baseline', name: 'Per-entity baseline (anomaly)', topics: ['an_anomaly'],
    clues: ['"unusual"', '"compared with their own history"', '"spike"'],
    thinking: 'Baseline from PRIOR rows only; require minimum history.',
    technique: 'AVG/COUNT OVER (… ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING)',
    example: `AVG(x) OVER (PARTITION BY acct ORDER BY t ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING)`,
    mistakes: ['Including the current row', 'Flagging with too little history'] },
];

export const PATTERN_BY_ID = Object.fromEntries(PATTERNS.map(p => [p.id, p]));

// Explain-it-back prompts: self-graded against key points.
export const EXPLAIN_PROMPTS = [
  { id: 'E01', topic: 'w_ranking', q: 'Explain the difference between ROW_NUMBER(), RANK() and DENSE_RANK(), and when you would choose each.',
    points: ['ROW_NUMBER gives unique sequential numbers even for ties', 'RANK gives ties the same number and leaves gaps after them', 'DENSE_RANK gives ties the same number with no gaps', 'The business tie rule decides which to use', 'Filter on the rank in an outer query'] },
  { id: 'E02', topic: 'a_having', q: 'Why can\'t you filter on COUNT(*) in WHERE? What is the difference between WHERE and HAVING?',
    points: ['WHERE filters rows before grouping', 'Aggregates do not exist yet when WHERE runs', 'HAVING filters groups after aggregation', 'Row filters should go in WHERE for efficiency'] },
  { id: 'E03', topic: 'j_left', q: 'You LEFT JOIN customers to orders and then add WHERE orders.status = \'completed\'. What happens and how do you fix it?',
    points: ['Customers without matching orders get NULL order columns', 'NULL = \'completed\' is not true, so WHERE removes them', 'The LEFT JOIN behaves like an INNER JOIN', 'Move the condition into the ON clause'] },
  { id: 'E04', topic: 'j_fanout', q: 'What is join fan-out and how do you prevent it when combining order items and payments?',
    points: ['Grain: one-to-many joins repeat the parent row', 'Joining two child tables multiplies their rows', 'Sums become inflated', 'Aggregate each child to the parent grain first, then join'] },
  { id: 'E05', topic: 's_exists', q: 'Why can NOT IN return no rows at all? What should you use instead?',
    points: ['x NOT IN (…) expands to x <> a AND x <> b …', 'Comparison with NULL yields NULL', 'The whole predicate is never TRUE', 'NOT EXISTS (or filtering NULLs) avoids it'] },
  { id: 'E06', topic: 'w_frames', q: 'Why does LAST_VALUE() often return the current row, and how do you fix it?',
    points: ['With ORDER BY, the default frame ends at the current row', 'So the "last" row in the frame is the current row', 'Specify ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING'] },
  { id: 'E07', topic: 'w_gaps', q: 'Explain how the date − ROW_NUMBER() trick finds consecutive-day streaks.',
    points: ['Within a run, dates and row numbers both increase by 1', 'So their difference stays constant inside a run', 'A gap changes the difference', 'Group by the difference', 'Duplicates must be removed first'] },
  { id: 'E08', topic: 'an_cohort', q: 'Why shouldn\'t a cohort table show 0% for months that haven\'t happened yet?',
    points: ['Those months are unobserved, not zero', '0% claims everyone churned', 'It biases averages and trends downward', 'Show NULL / blank for immature cells'] },
  { id: 'E09', topic: 'a_conditional', q: 'Why does 3 / 4 return 0 in PostgreSQL and how do you compute a percentage safely?',
    points: ['Integer / integer is integer division', 'Cast to numeric or multiply by 100.0 first', 'Guard zero denominators with NULLIF'] },
  { id: 'E10', topic: 'an_funnel', q: 'Before writing a funnel query, which definitions must you settle?',
    points: ['Exact event for each step', 'Whether steps must be in order', 'Users vs events (unit of analysis)', 'Denominator: start of funnel or previous step', 'Time window / eligibility'] },
  { id: 'E11', topic: 'c_cte', q: 'When do CTEs help and do they cost performance in PostgreSQL?',
    points: ['They name intermediate steps and make grain explicit', 'They allow reuse and testing step by step', 'Since PostgreSQL 12 non-recursive CTEs are usually inlined', 'MATERIALIZED forces evaluation once'] },
  { id: 'E12', topic: 'x_dates', q: 'Why use a date spine, and why COUNT(column) rather than COUNT(*) after the LEFT JOIN?',
    points: ['GROUP BY on facts cannot produce periods with no rows', 'The spine provides every period', 'Unmatched periods have one NULL-padded row', 'COUNT(*) would count it as 1; COUNT(column) counts 0'] },
];

export const PG_VS_MYSQL = [
  ['Case-insensitive match', "ILIKE", "LIKE (collation-dependent, usually case-insensitive)"],
  ['Conditional aggregate', "COUNT(*) FILTER (WHERE …)", "SUM(CASE WHEN … THEN 1 ELSE 0 END)"],
  ['Integer division', "5/2 = 2 (cast for decimals)", "5/2 = 2.5000; DIV for integer"],
  ['Date difference (days)', "date2 - date1", "DATEDIFF(date2, date1)"],
  ['Truncate to month', "DATE_TRUNC('month', d)", "DATE_FORMAT(d, '%Y-%m-01')"],
  ['Add interval', "d + INTERVAL '7 days'", "DATE_ADD(d, INTERVAL 7 DAY)"],
  ['Format date', "TO_CHAR(d, 'YYYY-MM')", "DATE_FORMAT(d, '%Y-%m')"],
  ['String concat', "a || b (NULL if any NULL)", "CONCAT(a, b) (|| is OR by default)"],
  ['Split string', "SPLIT_PART(s, ',', 2)", "SUBSTRING_INDEX(SUBSTRING_INDEX(s, ',', 2), ',', -1)"],
  ['String aggregation', "STRING_AGG(x, ', ' ORDER BY x)", "GROUP_CONCAT(x ORDER BY x SEPARATOR ', ')"],
  ['Median / percentile', "PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY x)", "No built-in; rank rows and pick the middle"],
  ['First row per group', "DISTINCT ON (key) … ORDER BY key, t", "ROW_NUMBER() in a subquery"],
  ['Series of dates', "generate_series(start, end, interval)", "Recursive CTE or a calendar table"],
  ['JSON field as text', "props ->> 'device'", "props ->> '$.device'"],
  ['Lateral subquery', "JOIN LATERAL (…) ON true", "LATERAL supported from 8.0.14"],
  ['Full outer join', "FULL OUTER JOIN", "Not supported; LEFT JOIN UNION RIGHT JOIN"],
  ['Non-grouped columns', "Error", "Allowed if ONLY_FULL_GROUP_BY is off (dangerous)"],
  ['Boolean type', "true/false, WHERE is_active", "TINYINT(1); WHERE is_active = 1"],
  ['Upsert', "INSERT … ON CONFLICT DO UPDATE", "INSERT … ON DUPLICATE KEY UPDATE"],
  ['Limit with offset', "LIMIT n OFFSET m", "LIMIT m, n (or LIMIT n OFFSET m)"],
];

export const PG_FUNCTIONS = [
  ['DATE_TRUNC(unit, ts)', 'Bucket timestamps (day, week, month).'],
  ['EXTRACT(field FROM ts)', 'Year, month, isodow, epoch …'],
  ['TO_CHAR(ts, fmt)', "Format: 'YYYY-MM', 'FMDay', 'HH24:MI'."],
  ['AGE(a, b) / a - b', 'Interval between timestamps; date − date is integer days.'],
  ['generate_series(a, b, step)', 'Number or date sequences.'],
  ['COALESCE / NULLIF', 'First non-NULL / NULL when equal (safe division).'],
  ['STRING_AGG / ARRAY_AGG', 'Concatenate / collect values in a group.'],
  ['UNNEST(array)', 'Expand an array into rows.'],
  ['->, ->>, #>>, @>', 'JSONB access and containment.'],
  ['PERCENTILE_CONT / _DISC', 'Ordered-set aggregates for percentiles.'],
  ['FILTER (WHERE …)', 'Restrict an aggregate to a subset.'],
  ['DISTINCT ON (…)', 'Keep the first row per key by ORDER BY.'],
  ['BOOL_OR / BOOL_AND', 'Any / all true within a group.'],
  ['GREATEST / LEAST', 'Row-wise max/min across columns.'],
];

export const INTERVIEW_TIPS = [
  'Restate the question and the output columns before writing SQL.',
  'Say the grain of each table out loud and after each join.',
  'Ask about duplicates, NULLs, ties and time boundaries — interviewers reward the questions.',
  'Build incrementally with CTEs and sanity-check row counts after each step.',
  'Name the edge cases your query handles and the ones it assumes away.',
  'If stuck, solve a smaller version (one user, one day) and generalise.',
  'Finish by walking through one row of the output and why it is correct.',
];
