// Level 7a — funnels (P700–706), cohorts (P710–716), churn (P720–727), sessions (P730–736).
import { Q } from './q.js';
const STEPS = `SELECT 1 AS n, 'signup' AS step, COUNT(DISTINCT user_id) AS users FROM events WHERE event_name = 'signup'
UNION ALL SELECT 2, 'create_project', COUNT(DISTINCT user_id) FROM events WHERE event_name = 'create_project'
UNION ALL SELECT 3, 'invite_teammate', COUNT(DISTINCT user_id) FROM events WHERE event_name = 'invite_teammate'
UNION ALL SELECT 4, 'upgrade', COUNT(DISTINCT user_id) FROM events WHERE event_name = 'upgrade'`;
const SESS = `WITH p AS (SELECT user_id, viewed_at, page, CASE WHEN viewed_at - LAG(viewed_at) OVER (PARTITION BY user_id ORDER BY viewed_at) > INTERVAL '30 minutes' THEN 1 ELSE 0 END AS new_s FROM page_views),
s AS (SELECT user_id, viewed_at, page, SUM(new_s) OVER (PARTITION BY user_id ORDER BY viewed_at) + 1 AS session_no FROM p)`;
const NEWUSER = `INSERT INTO users VALUES (13,'2026-03-25','IN','organic');`;
const SESSRULE = 'A new session starts when more than 30 minutes pass since the user\'s previous page view (exactly 30 minutes stays in the same session).';

export const PROBLEMS_J = [
  // ── Funnels ──
  Q('P700', 'Product funnel', 'saas', ['an_funnel'], 'Medium', 'Distinct users per step and % of signups',
    'Count the users who reached each step — signup, create_project, invite_teammate, upgrade (a user counts once per step, in any order) — and each step\'s percentage of signups (1 decimal). Return step, users, pct_of_signups in funnel order.', ['step', 'users', 'pct_of_signups'], true,
    `SELECT step, users, ROUND(100.0 * users / (SELECT COUNT(DISTINCT user_id) FROM events WHERE event_name = 'signup'), 1) AS pct_of_signups FROM (${STEPS}) t ORDER BY n;`,
    ['Duplicate upgrade events', 'Users count once per step.', `INSERT INTO events VALUES (46,1,'upgrade','2026-01-16 12:00','{}'),(47,1,'upgrade','2026-01-17 12:00','{}');`],
    ['One row per step.', 'Count users, not events.', 'COUNT(DISTINCT user_id) per event_name, stacked with UNION ALL'],
    'Funnels count people. Event counts are inflated by repeats such as the duplicate create_project rows.',
    `SELECT step, users, ROUND(100.0 * users / (SELECT COUNT(*) FROM events WHERE event_name = 'signup'), 1) AS pct_of_signups FROM (SELECT 1 AS n, 'signup' AS step, COUNT(*) AS users FROM events WHERE event_name = 'signup' UNION ALL SELECT 2, 'create_project', COUNT(*) FROM events WHERE event_name = 'create_project' UNION ALL SELECT 3, 'invite_teammate', COUNT(*) FROM events WHERE event_name = 'invite_teammate' UNION ALL SELECT 4, 'upgrade', COUNT(*) FROM events WHERE event_name = 'upgrade') t ORDER BY n;`, { patterns: ['funnel'] }),
  Q('P701', 'Step-to-step conversion', 'saas', ['an_funnel', 'w_offset'], 'Medium', 'Percent of the previous step with LAG',
    'For the same four funnel steps, show users at each step and the percentage of the PREVIOUS step\'s users that reached it (1 decimal; empty for signup). Return step, users, pct_of_prev in funnel order.', ['step', 'users', 'pct_of_prev'], true,
    `WITH steps AS (${STEPS}) SELECT step, users, ROUND(100.0 * users / LAG(users) OVER (ORDER BY n), 1) AS pct_of_prev FROM steps ORDER BY n;`,
    ['More upgrades', 'Rates follow the data.', `INSERT INTO events VALUES (46,2,'upgrade','2026-03-02 12:00','{}');`],
    ['Same step counts as before.', 'Divide by the row above.', 'users / LAG(users) OVER (ORDER BY n)'],
    'Step-to-step conversion divides by the previous step, not by the first step.',
    `WITH steps AS (${STEPS}) SELECT step, users, ROUND(100.0 * users / FIRST_VALUE(users) OVER (ORDER BY n), 1) AS pct_of_prev FROM steps ORDER BY n;`, { patterns: ['funnel'] }),
  Q('P702', 'Upgrade rate by channel', 'saas', ['an_funnel', 'j_left'], 'Medium', 'Conversion per segment without fan-out',
    'For each acquisition channel: signups, users who ever upgraded and the conversion percentage (1 decimal). Sort by channel.', ['channel', 'signups', 'upgraded', 'conversion_pct'], true,
    `WITH up AS (SELECT DISTINCT user_id FROM events WHERE event_name = 'upgrade') SELECT u.channel, COUNT(*) AS signups, COUNT(up.user_id) AS upgraded, ROUND(100.0 * COUNT(up.user_id) / COUNT(*), 1) AS conversion_pct FROM users u LEFT JOIN up ON up.user_id = u.user_id GROUP BY u.channel ORDER BY u.channel;`,
    ['A repeat upgrader', 'Several upgrade events are one converted user.', `INSERT INTO events VALUES (46,1,'upgrade','2026-02-16 12:00','{}');`],
    ['Joining events multiplies users.', 'Reduce upgrades to one row per user first.', 'WITH up AS (SELECT DISTINCT user_id …) LEFT JOIN up'],
    'Convert the many-side to a per-user flag before joining, so signups stay one row per user.',
    `SELECT u.channel, COUNT(*) AS signups, COUNT(*) FILTER (WHERE e.event_name = 'upgrade') AS upgraded, ROUND(100.0 * COUNT(*) FILTER (WHERE e.event_name = 'upgrade') / COUNT(*), 1) AS conversion_pct FROM users u LEFT JOIN events e ON e.user_id = u.user_id GROUP BY u.channel ORDER BY u.channel;`, { patterns: ['funnel', 'fanout_guard'] }),
  Q('P703', 'Stuck after creating a project', 'saas', ['an_funnel'], 'Hard', 'Ordered steps within a time window',
    'Which users created a project but did NOT invite a teammate within 7 days AFTER creating it? Return user id, sorted. (An invite before the project does not count.)', ['user_id'], true,
    `SELECT DISTINCT c.user_id FROM events c WHERE c.event_name = 'create_project' AND NOT EXISTS (SELECT 1 FROM events i WHERE i.user_id = c.user_id AND i.event_name = 'invite_teammate' AND i.event_time > c.event_time AND i.event_time <= c.event_time + INTERVAL '7 days') ORDER BY c.user_id;`,
    ['Invite on day 8', 'Outside the window it does not count.', `INSERT INTO events VALUES (46,1,'create_project','2026-03-10 10:00','{}');`],
    ['Order and window both matter.', 'Look for an invite after the project and within 7 days.', 'NOT EXISTS (… i.event_time > c.event_time AND i.event_time <= c.event_time + INTERVAL \'7 days\')'],
    'A funnel step is only completed if it happens after the previous one (and inside the window).',
    `SELECT DISTINCT c.user_id FROM events c WHERE c.event_name = 'create_project' AND NOT EXISTS (SELECT 1 FROM events i WHERE i.user_id = c.user_id AND i.event_name = 'invite_teammate') ORDER BY c.user_id;`, { patterns: ['funnel', 'anti_join'] }),
  Q('P704', 'Upgrade rate by signup device', 'saas', ['an_funnel'], 'Hard', 'Segment from the first event, count users once',
    'Using the device recorded on each user\'s signup event, report signups, users who upgraded and the percentage (1 decimal) per device. Sort by device.', ['device', 'signups', 'upgraded', 'pct'], true,
    `WITH su AS (SELECT user_id, properties->>'device' AS device FROM events WHERE event_name = 'signup'), up AS (SELECT DISTINCT user_id FROM events WHERE event_name = 'upgrade')
SELECT su.device, COUNT(*) AS signups, COUNT(up.user_id) AS upgraded, ROUND(100.0 * COUNT(up.user_id) / COUNT(*), 1) AS pct FROM su LEFT JOIN up ON up.user_id = su.user_id GROUP BY su.device ORDER BY su.device;`,
    ['A user with two upgrades', 'One user, one conversion.', `INSERT INTO events VALUES (46,3,'upgrade','2026-02-10 12:00','{}');`],
    ['The segment comes from one specific event.', 'Not from every event.', "properties->>'device' on the signup event only"],
    'Attribute each user to one segment (their signup device) and count them once.',
    `SELECT e.properties->>'device' AS device, COUNT(*) AS signups, COUNT(*) FILTER (WHERE e.event_name = 'upgrade') AS upgraded, ROUND(100.0 * COUNT(*) FILTER (WHERE e.event_name = 'upgrade') / COUNT(*), 1) AS pct FROM events e GROUP BY 1 ORDER BY 1;`, { patterns: ['funnel'] }),
  Q('P705', 'Pricing then signup', 'saas', ['an_funnel'], 'Medium', 'Ordered page-view sequence',
    'Which users viewed /pricing and LATER viewed /signup? Return user id, sorted.', ['user_id'], true,
    `SELECT DISTINCT p.user_id FROM page_views p JOIN page_views s ON s.user_id = p.user_id AND s.page = '/signup' AND s.viewed_at > p.viewed_at WHERE p.page = '/pricing' ORDER BY p.user_id;`,
    ['Signup page before pricing', 'Order matters.', `INSERT INTO page_views VALUES (3,'2026-02-10 08:00','/signup');`],
    ['Two pages, one after the other.', 'Self join with a time condition.', "s.page = '/signup' AND s.viewed_at > p.viewed_at"],
    'Viewing both pages is not the same as viewing them in order.',
    `SELECT user_id FROM page_views WHERE page IN ('/pricing', '/signup') GROUP BY user_id HAVING COUNT(DISTINCT page) = 2 ORDER BY user_id;`, { patterns: ['funnel'] }),
  Q('P706', 'Activation within a day', 'saas', ['an_funnel'], 'Hard', 'Conversion window anchored on the signup event',
    'By country: signups, users who created a project within 24 hours of their signup event (exactly 24 hours counts) and the percentage (1 decimal). Sort by country.', ['country', 'signups', 'activated', 'pct'], true,
    `WITH s AS (SELECT user_id, event_time AS t FROM events WHERE event_name = 'signup'), a AS (SELECT DISTINCT s.user_id FROM s JOIN events e ON e.user_id = s.user_id AND e.event_name = 'create_project' AND e.event_time >= s.t AND e.event_time <= s.t + INTERVAL '24 hours')
SELECT u.country, COUNT(*) AS signups, COUNT(a.user_id) AS activated, ROUND(100.0 * COUNT(a.user_id) / COUNT(*), 1) AS pct FROM users u LEFT JOIN a ON a.user_id = u.user_id GROUP BY u.country ORDER BY u.country;`,
    ['Exactly 24 hours', 'The boundary is inclusive.', `${NEWUSER} INSERT INTO events VALUES (46,13,'signup','2026-03-25 10:00','{}'),(47,13,'create_project','2026-03-26 10:00','{}');`],
    ['Measure from the signup event time.', 'Inclusive upper bound.', "e.event_time <= s.t + INTERVAL '24 hours'"],
    'Conversion windows should be explicit about both ends; here the 24-hour boundary is inclusive.',
    `WITH s AS (SELECT user_id, event_time AS t FROM events WHERE event_name = 'signup'), a AS (SELECT DISTINCT s.user_id FROM s JOIN events e ON e.user_id = s.user_id AND e.event_name = 'create_project' AND e.event_time >= s.t AND e.event_time < s.t + INTERVAL '24 hours') SELECT u.country, COUNT(*) AS signups, COUNT(a.user_id) AS activated, ROUND(100.0 * COUNT(a.user_id) / COUNT(*), 1) AS pct FROM users u LEFT JOIN a ON a.user_id = u.user_id GROUP BY u.country ORDER BY u.country;`, { patterns: ['funnel'] }),

  // ── Cohorts ──
  Q('P710', 'Signup cohorts', 'saas', ['an_cohort', 'j_left'], 'Medium', 'Cohort size and an ever-did flag',
    'Group users by signup month. For each cohort: its size and how many of its users ever logged in. Return cohort month (first-of-month date), users, ever_logged_in; sorted by month.', ['cohort_month', 'users', 'ever_logged_in'], true,
    `WITH lg AS (SELECT DISTINCT user_id FROM events WHERE event_name = 'login') SELECT date_trunc('month', u.signup_date)::date AS cohort_month, COUNT(*) AS users, COUNT(lg.user_id) AS ever_logged_in FROM users u LEFT JOIN lg ON lg.user_id = u.user_id GROUP BY 1 ORDER BY 1;`,
    ['A user with many logins', 'Repeat logins do not inflate cohorts.', `INSERT INTO events VALUES (46,1,'login','2026-03-10 08:00','{}'),(47,1,'login','2026-03-11 08:00','{}');`],
    ['Users, not events.', 'Reduce logins to one row per user first.', 'WITH lg AS (SELECT DISTINCT user_id …)'],
    'Cohort tables count users; joining raw events multiplies them.',
    `SELECT date_trunc('month', u.signup_date)::date AS cohort_month, COUNT(*) AS users, COUNT(e.user_id) AS ever_logged_in FROM users u LEFT JOIN events e ON e.user_id = u.user_id AND e.event_name = 'login' GROUP BY 1 ORDER BY 1;`, { patterns: ['cohort_retention'] }),
  Q('P711', 'Month-1 retention', 'saas', ['an_cohort'], 'Hard', 'Retained = any event in the next calendar month',
    'For each signup-month cohort: users, users with any event in the calendar month AFTER their signup month, and that percentage (1 decimal). Return cohort month, users, retained_m1, pct; sorted by month.', ['cohort_month', 'users', 'retained_m1', 'pct'], true,
    `WITH c AS (SELECT user_id, date_trunc('month', signup_date)::date AS cm FROM users), r AS (SELECT DISTINCT c.user_id FROM c JOIN events e ON e.user_id = c.user_id AND date_trunc('month', e.event_time)::date = (c.cm + INTERVAL '1 month')::date)
SELECT c.cm AS cohort_month, COUNT(*) AS users, COUNT(r.user_id) AS retained_m1, ROUND(100.0 * COUNT(r.user_id) / COUNT(*), 1) AS pct FROM c LEFT JOIN r ON r.user_id = c.user_id GROUP BY c.cm ORDER BY c.cm;`,
    ['A user with two events next month', 'A retained user counts once.', `INSERT INTO events VALUES (46,4,'login','2026-02-02 08:00','{}'),(47,4,'login','2026-02-03 08:00','{}');`],
    ['Month offset of the event versus the cohort month.', 'Distinct users.', "date_trunc('month', event_time) = cohort month + 1 month"],
    'Retention counts distinct users active in the target period, not events.',
    `WITH c AS (SELECT user_id, date_trunc('month', signup_date)::date AS cm FROM users) SELECT c.cm AS cohort_month, COUNT(DISTINCT c.user_id) AS users, COUNT(e.user_id) AS retained_m1, ROUND(100.0 * COUNT(e.user_id) / COUNT(DISTINCT c.user_id), 1) AS pct FROM c LEFT JOIN events e ON e.user_id = c.user_id AND date_trunc('month', e.event_time)::date = (c.cm + INTERVAL '1 month')::date GROUP BY c.cm ORDER BY c.cm;`, { patterns: ['cohort_retention'] }),
  Q('P712', 'First-order cohorts', 'shop', ['an_cohort'], 'Hard', 'Cohort by first purchase, not signup',
    'Group customers by the month of their FIRST completed order. For each cohort: customers and how many placed at least two completed orders. Return cohort month, customers, repeat_customers; sorted by month.', ['cohort_month', 'customers', 'repeat_customers'], true,
    `WITH o AS (SELECT customer_id, date_trunc('month', order_date)::date AS m, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date, order_id) AS rn FROM orders WHERE status = 'completed'),
f AS (SELECT customer_id, m AS cohort_month FROM o WHERE rn = 1), n AS (SELECT customer_id, COUNT(*) AS c FROM o GROUP BY customer_id)
SELECT f.cohort_month, COUNT(*) AS customers, COUNT(*) FILTER (WHERE n.c >= 2) AS repeat_customers FROM f JOIN n ON n.customer_id = f.customer_id GROUP BY f.cohort_month ORDER BY f.cohort_month;`,
    ['A customer whose first order is long after signup', 'The cohort is the first order month.', `INSERT INTO orders VALUES (1018,10,'2026-04-12','completed',NULL);`],
    ['Find each customer\'s first completed order.', 'Then count their orders.', 'ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date)'],
    'A cohort is defined by the event of interest (first purchase), not by when the account was created.',
    `WITH o AS (SELECT o.customer_id, COUNT(*) AS c FROM orders o WHERE o.status = 'completed' GROUP BY o.customer_id) SELECT date_trunc('month', cu.signup_date)::date AS cohort_month, COUNT(*) AS customers, COUNT(*) FILTER (WHERE o.c >= 2) AS repeat_customers FROM customers cu JOIN o ON o.customer_id = cu.customer_id GROUP BY 1 ORDER BY 1;`, { patterns: ['cohort_retention'] }),
  Q('P713', 'Time to first order', 'shop', ['an_cohort'], 'Medium', 'Bucketing a lag',
    'For customers with a completed order: how many days passed between signup and their first completed order? Count customers in buckets "0-7 days", "8-30 days" and "31+ days". Return bucket and customers, in that order.', ['bucket', 'customers'], true,
    `WITH f AS (SELECT c.customer_id, MIN(o.order_date) - c.signup_date AS d FROM customers c JOIN orders o ON o.customer_id = c.customer_id AND o.status = 'completed' GROUP BY c.customer_id, c.signup_date)
SELECT CASE WHEN d <= 7 THEN '0-7 days' WHEN d <= 30 THEN '8-30 days' ELSE '31+ days' END AS bucket, COUNT(*) AS customers FROM f GROUP BY 1 ORDER BY MIN(d);`,
    ['Same-day purchase', 'Day 0 belongs in the first bucket.', `INSERT INTO customers VALUES (11,'Tara Sen','tara@mail.com','Pune','2026-04-01',NULL); INSERT INTO orders VALUES (1018,11,'2026-04-01','completed',NULL);`],
    ['First completed order only.', 'Subtract signup date.', 'MIN(order_date) - signup_date'],
    'Cancelled orders are not purchases; including them shortens time-to-first-order and adds customers who never bought.',
    `WITH f AS (SELECT c.customer_id, MIN(o.order_date) - c.signup_date AS d FROM customers c JOIN orders o ON o.customer_id = c.customer_id GROUP BY c.customer_id, c.signup_date) SELECT CASE WHEN d <= 7 THEN '0-7 days' WHEN d <= 30 THEN '8-30 days' ELSE '31+ days' END AS bucket, COUNT(*) AS customers FROM f GROUP BY 1 ORDER BY MIN(d);`, { patterns: ['cohort_retention'] }),
  Q('P714', 'Active months per user', 'saas', ['an_cohort', 'a_distinct'], 'Medium', 'Distribution of a distinct count',
    'For each user, count the distinct calendar months in which they had any event; then show how many users have 1, 2, 3 … active months. Return active_months and users, sorted by active_months.', ['active_months', 'users'], true,
    `WITH m AS (SELECT user_id, COUNT(DISTINCT date_trunc('month', event_time)) AS am FROM events GROUP BY user_id) SELECT am AS active_months, COUNT(*) AS users FROM m GROUP BY am ORDER BY am;`,
    ['A busy single-month user', 'Many events in one month is one active month.', `INSERT INTO events VALUES (46,4,'login','2026-01-21 08:00','{}'),(47,4,'login','2026-01-22 08:00','{}'),(48,4,'login','2026-01-23 08:00','{}');`],
    ['Months, not events.', 'Two levels of aggregation.', 'COUNT(DISTINCT date_trunc(\'month\', event_time)) per user, then count users per value'],
    'First compute a per-user metric, then aggregate that metric across users.',
    `WITH m AS (SELECT user_id, COUNT(*) AS am FROM events GROUP BY user_id) SELECT am AS active_months, COUNT(*) AS users FROM m GROUP BY am ORDER BY am;`),
  Q('P715', 'Revenue by months since first order', 'shop', ['an_cohort'], 'Very Hard', 'Cohort revenue with a month offset',
    'Group customers by the month of their first completed order. For each cohort and each month offset (0 = the first-order month, 1 = the next month …) report completed revenue (quantity × charged price). Return cohort month, month offset, revenue; sorted by cohort then offset.', ['cohort_month', 'month_offset', 'revenue'], true,
    `WITH f AS (SELECT customer_id, MIN(date_trunc('month', order_date))::date AS cm FROM orders WHERE status = 'completed' GROUP BY customer_id)
SELECT f.cm AS cohort_month, ((EXTRACT(year FROM o.order_date) - EXTRACT(year FROM f.cm)) * 12 + EXTRACT(month FROM o.order_date) - EXTRACT(month FROM f.cm))::int AS month_offset, SUM(oi.quantity * oi.unit_price) AS revenue
FROM orders o JOIN f ON f.customer_id = o.customer_id JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' GROUP BY 1, 2 ORDER BY 1, 2;`,
    ['A late repeat order', 'Offsets follow calendar months.', `INSERT INTO orders VALUES (1018,1,'2026-05-02','completed',NULL); INSERT INTO order_items VALUES (1018,106,1,899);`],
    ['The cohort is the first-order month.', 'Offset = months between order month and cohort month.', '(year diff × 12) + month diff'],
    'Month offsets need year and month arithmetic; offsetting from the signup month changes which cohort a row lands in.',
    `WITH f AS (SELECT customer_id, date_trunc('month', signup_date)::date AS cm FROM customers) SELECT f.cm AS cohort_month, ((EXTRACT(year FROM o.order_date) - EXTRACT(year FROM f.cm)) * 12 + EXTRACT(month FROM o.order_date) - EXTRACT(month FROM f.cm))::int AS month_offset, SUM(oi.quantity * oi.unit_price) AS revenue FROM orders o JOIN f ON f.customer_id = o.customer_id JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' GROUP BY 1, 2 ORDER BY 1, 2;`, { patterns: ['cohort_retention'] }),
  Q('P716', 'Retention matrix', 'saas', ['an_cohort', 'x_pivot'], 'Very Hard', 'Cohort matrix with unobserved cells left empty',
    'Build a retention matrix: one row per signup-month cohort with active users (any event) in month 0, month 1 and month 2 after signup. Data is observed through 2026-04-30, so a cell is EMPTY (not 0) when that calendar month has not started by 2026-04-01 or later months were not observed. Return cohort_month, m0, m1, m2; sorted by month.', ['cohort_month', 'm0', 'm1', 'm2'], true,
    `WITH c AS (SELECT user_id, date_trunc('month', signup_date)::date AS cm FROM users), a AS (SELECT DISTINCT user_id, date_trunc('month', event_time)::date AS am FROM events),
x AS (SELECT c.cm, c.user_id, ((EXTRACT(year FROM a.am) - EXTRACT(year FROM c.cm)) * 12 + EXTRACT(month FROM a.am) - EXTRACT(month FROM c.cm))::int AS k FROM c JOIN a ON a.user_id = c.user_id)
SELECT cm AS cohort_month, COUNT(DISTINCT user_id) FILTER (WHERE k = 0) AS m0,
  CASE WHEN cm + INTERVAL '1 month' <= DATE '2026-04-01' THEN COUNT(DISTINCT user_id) FILTER (WHERE k = 1) END AS m1,
  CASE WHEN cm + INTERVAL '2 months' <= DATE '2026-04-01' THEN COUNT(DISTINCT user_id) FILTER (WHERE k = 2) END AS m2
FROM x GROUP BY cm ORDER BY cm;`,
    ['A new April cohort', 'Its later months are unobserved, not zero.', `INSERT INTO users VALUES (13,'2026-04-02','IN','organic'); INSERT INTO events VALUES (46,13,'signup','2026-04-02 10:00','{}');`],
    ['Distinct users per cohort and offset.', 'Months after the observation window are unknown.', 'CASE WHEN cohort_month + k months <= DATE \'2026-04-01\' THEN … END'],
    'A missing cell and a zero cell mean different things; unobserved periods must be NULL.',
    `WITH c AS (SELECT user_id, date_trunc('month', signup_date)::date AS cm FROM users), a AS (SELECT DISTINCT user_id, date_trunc('month', event_time)::date AS am FROM events), x AS (SELECT c.cm, c.user_id, ((EXTRACT(year FROM a.am) - EXTRACT(year FROM c.cm)) * 12 + EXTRACT(month FROM a.am) - EXTRACT(month FROM c.cm))::int AS k FROM c JOIN a ON a.user_id = c.user_id) SELECT cm AS cohort_month, COUNT(DISTINCT user_id) FILTER (WHERE k = 0) AS m0, COUNT(DISTINCT user_id) FILTER (WHERE k = 1) AS m1, COUNT(DISTINCT user_id) FILTER (WHERE k = 2) AS m2 FROM x GROUP BY cm ORDER BY cm;`, { patterns: ['cohort_retention'] }),

  // ── Churn (billing) ──
  Q('P720', 'Active MRR today', 'billing', ['an_churn'], 'Easy', 'Point-in-time active subscriptions',
    'As of 2026-06-30, how many accounts have an active subscription and what is their total MRR? A subscription is active on a date when it has started and has no end date or ends on/after that date. Return one row: active_accounts, mrr.', ['active_accounts', 'mrr'], false,
    `SELECT COUNT(DISTINCT account_id) AS active_accounts, SUM(mrr) AS mrr FROM subs WHERE start_date <= DATE '2026-06-30' AND (end_date IS NULL OR end_date >= DATE '2026-06-30');`,
    ['A subscription ending exactly on the date', 'The end date is inclusive.', `INSERT INTO accounts VALUES (11,'Kilo','2026-05-01','IN'); INSERT INTO subs VALUES (13,11,'pro',50,'2026-05-01','2026-06-30');`],
    ['Which rows are active on that date?', 'Started, and not yet ended.', 'start_date <= d AND (end_date IS NULL OR end_date >= d)'],
    'Historic periods stay in the table, so "active" must be defined with dates, not by counting rows.',
    `SELECT COUNT(DISTINCT account_id) AS active_accounts, SUM(mrr) AS mrr FROM subs;`, { patterns: ['baseline'] }),
  Q('P721', 'Month-end MRR', 'billing', ['an_churn', 'x_dates'], 'Hard', 'MRR snapshots over a month spine',
    'MRR at the end of each month from January to June 2026 (a subscription counts when active on the last day of the month). Return month_end and mrr, sorted by month.', ['month_end', 'mrr'], true,
    `SELECT m.me AS month_end, COALESCE(SUM(s.mrr), 0) AS mrr FROM (SELECT (ms + INTERVAL '1 month - 1 day')::date AS me FROM generate_series(DATE '2026-01-01', DATE '2026-06-01', INTERVAL '1 month') ms) m
LEFT JOIN subs s ON s.start_date <= m.me AND (s.end_date IS NULL OR s.end_date >= m.me) GROUP BY m.me ORDER BY m.me;`,
    ['A subscription ending on a month end', 'It is still active that day.', `INSERT INTO accounts VALUES (11,'Kilo','2026-05-01','IN'); INSERT INTO subs VALUES (13,11,'pro',50,'2026-05-01','2026-05-31');`],
    ['Generate the month-end dates.', 'Join subscriptions active on each date.', 'subs s ON s.start_date <= me AND (s.end_date IS NULL OR s.end_date >= me)'],
    'Snapshot metrics join facts to a date spine with a range condition; the end date is inclusive.',
    `SELECT m.me AS month_end, COALESCE(SUM(s.mrr), 0) AS mrr FROM (SELECT (ms + INTERVAL '1 month - 1 day')::date AS me FROM generate_series(DATE '2026-01-01', DATE '2026-06-01', INTERVAL '1 month') ms) m LEFT JOIN subs s ON s.start_date <= m.me AND (s.end_date IS NULL OR s.end_date > m.me) GROUP BY m.me ORDER BY m.me;`, { patterns: ['date_spine'] }),
  Q('P722', 'Monthly logo churn', 'billing', ['an_churn'], 'Very Hard', 'Churn = active at month start, gone at next month start',
    'For February to June 2026: accounts active on the first day of the month, how many of them are NOT active on the first day of the next month (churned), and the churn percentage (1 decimal). Plan changes and renewals must not count as churn. Return month (first-of-month), active_start, churned, churn_pct; sorted by month.', ['month', 'active_start', 'churned', 'churn_pct'], true,
    `SELECT month, active_start, churned, ROUND(100.0 * churned / NULLIF(active_start, 0), 1) AS churn_pct FROM (
  SELECT m.ms AS month,
    (SELECT COUNT(DISTINCT s.account_id) FROM subs s WHERE s.start_date <= m.ms AND (s.end_date IS NULL OR s.end_date >= m.ms)) AS active_start,
    (SELECT COUNT(DISTINCT s.account_id) FROM subs s WHERE s.start_date <= m.ms AND (s.end_date IS NULL OR s.end_date >= m.ms)
       AND NOT EXISTS (SELECT 1 FROM subs t WHERE t.account_id = s.account_id AND t.start_date <= m.nms AND (t.end_date IS NULL OR t.end_date >= m.nms))) AS churned
  FROM (SELECT ms::date AS ms, (ms + INTERVAL '1 month')::date AS nms FROM generate_series(DATE '2026-02-01', DATE '2026-06-01', INTERVAL '1 month') ms) m
) q ORDER BY month;`,
    ['A cancellation in May', 'New churn shows up in the right month.', `INSERT INTO subs VALUES (13,9,'basic',20,'2026-02-03','2026-05-31'); DELETE FROM subs WHERE sub_id = 12;`],
    ['Compare two snapshots, per account.', 'A plan change has a new active row on the next day.', 'active on month start AND NOT active on next month start'],
    'Counting subscriptions that END in a month wrongly includes upgrades and downgrades; churn is an account no longer active.',
    `SELECT date_trunc('month', s.end_date)::date AS month, 0 AS active_start, COUNT(*) AS churned, 0 AS churn_pct FROM subs s WHERE s.end_date >= DATE '2026-02-01' AND s.end_date < DATE '2026-07-01' GROUP BY 1 ORDER BY 1;`, { patterns: ['baseline'] }),
  Q('P723', 'Upgrades and downgrades', 'billing', ['an_churn', 'w_offset'], 'Hard', 'Contiguous plan changes with LEAD',
    'Find plan changes: a subscription immediately followed by another for the same account (the next starts the day after the previous ends) with a different MRR. Return account id, from plan, to plan, MRR change and direction ("upgrade" or "downgrade"); sorted by account id.', ['account_id', 'from_plan', 'to_plan', 'mrr_change', 'direction'], true,
    `WITH x AS (SELECT account_id, plan AS from_plan, mrr, end_date, LEAD(plan) OVER w AS to_plan, LEAD(mrr) OVER w AS next_mrr, LEAD(start_date) OVER w AS next_start FROM subs WINDOW w AS (PARTITION BY account_id ORDER BY start_date))
SELECT account_id, from_plan, to_plan, next_mrr - mrr AS mrr_change, CASE WHEN next_mrr > mrr THEN 'upgrade' ELSE 'downgrade' END AS direction FROM x WHERE next_start = end_date + 1 AND next_mrr <> mrr ORDER BY account_id;`,
    ['A gap then a different plan', 'A gap means reactivation, not a plan change.', `INSERT INTO subs VALUES (13,2,'pro',50,'2026-05-01',NULL);`],
    ['Look at the next row per account.', 'It must start the day after this one ends.', 'LEAD(start_date) OVER (PARTITION BY account_id ORDER BY start_date) = end_date + 1'],
    'A returning customer (with a gap) is reactivation, not an upgrade; contiguity separates the two.',
    `WITH x AS (SELECT account_id, plan AS from_plan, mrr, LEAD(plan) OVER w AS to_plan, LEAD(mrr) OVER w AS next_mrr FROM subs WINDOW w AS (PARTITION BY account_id ORDER BY start_date)) SELECT account_id, from_plan, to_plan, next_mrr - mrr AS mrr_change, CASE WHEN next_mrr >= mrr THEN 'upgrade' ELSE 'downgrade' END AS direction FROM x WHERE to_plan IS NOT NULL ORDER BY account_id;`, { patterns: ['prev_next'] }),
  Q('P724', 'Win-backs', 'billing', ['an_churn'], 'Hard', 'Detecting a gap between periods',
    'Which accounts churned and later came back? Return account id and the number of days they were without a subscription (days strictly between the end of one period and the start of the next). Contiguous periods are not win-backs. Sorted by account id.', ['account_id', 'gap_days'], true,
    `WITH x AS (SELECT account_id, end_date, LEAD(start_date) OVER (PARTITION BY account_id ORDER BY start_date) AS next_start FROM subs) SELECT account_id, next_start - end_date - 1 AS gap_days FROM x WHERE next_start - end_date > 1 ORDER BY account_id;`,
    ['Another win-back', 'Gaps are measured per account.', `INSERT INTO subs VALUES (13,2,'basic',20,'2026-06-10',NULL); UPDATE subs SET end_date = '2026-05-31' WHERE sub_id = 3;`],
    ['Compare each period\'s end with the next start.', 'A gap needs more than one day.', 'next_start - end_date > 1'],
    'Having several subscription rows is not the same as churning: plan changes are contiguous.',
    `SELECT account_id, COUNT(*) - 1 AS gap_days FROM subs GROUP BY account_id HAVING COUNT(*) > 1 ORDER BY account_id;`, { patterns: ['prev_next'] }),
  Q('P725', 'New MRR by month', 'billing', ['an_churn', 'x_dedup'], 'Medium', 'First subscription per account',
    'New business by month: for each month, the accounts whose FIRST subscription started then and the MRR of that first subscription. Return month (first-of-month), new_accounts, new_mrr; sorted by month.', ['month', 'new_accounts', 'new_mrr'], true,
    `WITH f AS (SELECT DISTINCT ON (account_id) account_id, start_date, mrr FROM subs ORDER BY account_id, start_date) SELECT date_trunc('month', start_date)::date AS month, COUNT(*) AS new_accounts, SUM(mrr) AS new_mrr FROM f GROUP BY 1 ORDER BY 1;`,
    ['A later plan change', 'Plan changes are not new business.', `INSERT INTO subs VALUES (13,3,'team',100,'2026-06-01',NULL); UPDATE subs SET end_date = '2026-05-31' WHERE sub_id = 4;`],
    ['Only the first subscription per account.', 'DISTINCT ON keeps one.', 'DISTINCT ON (account_id) … ORDER BY account_id, start_date'],
    'Counting every subscription start treats upgrades and win-backs as new customers.',
    `SELECT date_trunc('month', start_date)::date AS month, COUNT(*) AS new_accounts, SUM(mrr) AS new_mrr FROM subs GROUP BY 1 ORDER BY 1;`, { patterns: ['dedup'] }),
  Q('P726', 'Lifetime of churned accounts', 'billing', ['an_churn'], 'Hard', 'Open-ended periods and censoring',
    'For accounts that have churned (they have subscriptions but none is active on 2026-06-30), report their lifetime in days: from their first subscription start to the last end date, both days counted. Return account id and lifetime_days, sorted by account id.', ['account_id', 'lifetime_days'], true,
    `WITH s AS (SELECT account_id, MIN(start_date) AS first_start, MAX(COALESCE(end_date, DATE '9999-12-31')) AS last_end FROM subs GROUP BY account_id) SELECT account_id, last_end - first_start + 1 AS lifetime_days FROM s WHERE last_end < DATE '2026-06-30' ORDER BY account_id;`,
    ['A still-active account with a past end date', 'Active accounts are not churned, whatever the earlier rows say.', `INSERT INTO subs VALUES (13,2,'basic',20,'2026-06-01',NULL);`],
    ['A NULL end date means still active.', 'MAX() ignores NULLs, which hides active accounts.', "MAX(COALESCE(end_date, DATE '9999-12-31'))"],
    'Treat NULL end dates explicitly; otherwise an account with an open subscription looks like it ended on its last real end date.',
    `SELECT account_id, MAX(end_date) - MIN(start_date) + 1 AS lifetime_days FROM subs WHERE end_date IS NOT NULL GROUP BY account_id HAVING MAX(end_date) < DATE '2026-06-30' ORDER BY account_id;`, { patterns: ['baseline'] }),
  Q('P727', 'Long-time basic plans', 'billing', ['an_churn'], 'Medium', 'Tenure on the current plan',
    'Which currently active BASIC subscriptions have been on that plan for more than 90 days as of 2026-06-30 (measured from the subscription start)? Return account id and days on plan; sorted by account id.', ['account_id', 'days_on_plan'], true,
    `SELECT account_id, DATE '2026-06-30' - start_date AS days_on_plan FROM subs WHERE plan = 'basic' AND end_date IS NULL AND DATE '2026-06-30' - start_date > 90 ORDER BY account_id;`,
    ['Plan started exactly 90 days ago', 'More than 90 is strict.', `INSERT INTO accounts VALUES (11,'Kilo','2026-04-01','IN'); INSERT INTO subs VALUES (13,11,'basic',20,'2026-04-01',NULL);`],
    ['Tenure on this plan, not on the account.', 'Use the subscription start.', "DATE '2026-06-30' - start_date"],
    'A win-back or plan change restarts the plan clock; the account signup date overstates tenure.',
    `SELECT a.account_id, DATE '2026-06-30' - a.signup_date AS days_on_plan FROM accounts a JOIN subs s ON s.account_id = a.account_id WHERE s.plan = 'basic' AND s.end_date IS NULL AND DATE '2026-06-30' - a.signup_date > 90 ORDER BY a.account_id;`),

  // ── Sessions ──
  Q('P730', 'Number the sessions', 'saas', ['an_session', 'w_offset'], 'Hard', 'Sessionization with a 30-minute gap',
    `Assign every page view a session number per user. ${SESSRULE} Return user id, view time, page and session number; sorted by user then time.`, ['user_id', 'viewed_at', 'page', 'session_no'], true,
    `${SESS} SELECT user_id, viewed_at, page, session_no FROM s ORDER BY user_id, viewed_at;`,
    ['Exactly 30 minutes later', 'The 30-minute boundary stays in the same session.', `INSERT INTO page_views VALUES (5,'2026-02-11 00:40','/pricing');`],
    ['Flag a new session when the gap is big.', 'Then number sessions with a running sum of the flags.', 'SUM(new_session_flag) OVER (PARTITION BY user_id ORDER BY viewed_at) + 1'],
    'Gap-based sessionization = LAG + flag + running SUM. The comparison is strictly "more than 30 minutes".',
    `WITH p AS (SELECT user_id, viewed_at, page, CASE WHEN viewed_at - LAG(viewed_at) OVER (PARTITION BY user_id ORDER BY viewed_at) >= INTERVAL '30 minutes' THEN 1 ELSE 0 END AS new_s FROM page_views), s AS (SELECT user_id, viewed_at, page, SUM(new_s) OVER (PARTITION BY user_id ORDER BY viewed_at) + 1 AS session_no FROM p) SELECT user_id, viewed_at, page, session_no FROM s ORDER BY user_id, viewed_at;`, { patterns: ['sessionization'] }),
  Q('P731', 'Session summary', 'saas', ['an_session'], 'Hard', 'Aggregate sessions',
    `Summarise each session. ${SESSRULE} Return user id, session number, start time, end time, number of page views and duration in minutes (rounded); sorted by user then session.`, ['user_id', 'session_no', 'start_time', 'end_time', 'views', 'minutes'], true,
    `${SESS} SELECT user_id, session_no, MIN(viewed_at) AS start_time, MAX(viewed_at) AS end_time, COUNT(*) AS views, ROUND(EXTRACT(EPOCH FROM MAX(viewed_at) - MIN(viewed_at)) / 60) AS minutes FROM s GROUP BY user_id, session_no ORDER BY user_id, session_no;`,
    ['A single-view session', 'Duration is 0 for one view.', `INSERT INTO page_views VALUES (5,'2026-02-12 12:00','/home');`],
    ['Session numbering first.', 'Then GROUP BY user and session.', 'GROUP BY user_id, session_no'],
    'Once rows carry a session id, session metrics are ordinary aggregations.',
    `SELECT user_id, DENSE_RANK() OVER (PARTITION BY user_id ORDER BY viewed_at::date) AS session_no, MIN(viewed_at) AS start_time, MAX(viewed_at) AS end_time, COUNT(*) AS views, ROUND(EXTRACT(EPOCH FROM MAX(viewed_at) - MIN(viewed_at)) / 60) AS minutes FROM page_views GROUP BY user_id, viewed_at::date ORDER BY user_id, session_no;`, { patterns: ['sessionization'] }),
  Q('P732', 'Sessions per user', 'saas', ['an_session'], 'Medium', 'Sessions and views per session',
    `For each user with page views: number of sessions and average page views per session (2 decimals). ${SESSRULE} Return user id, sessions, avg_views; sorted by user.`, ['user_id', 'sessions', 'avg_views'], true,
    `${SESS} SELECT user_id, COUNT(DISTINCT session_no) AS sessions, ROUND(COUNT(*)::numeric / COUNT(DISTINCT session_no), 2) AS avg_views FROM s GROUP BY user_id ORDER BY user_id;`,
    ['A long gap creates another session', 'Sessions grow with gaps.', `INSERT INTO page_views VALUES (5,'2026-02-12 12:00','/home');`],
    ['Sessions are not rows.', 'Count distinct session numbers.', 'COUNT(DISTINCT session_no)'],
    'Average views per session = views / sessions, both derived from the sessionized rows.',
    `SELECT user_id, COUNT(*) AS sessions, ROUND(COUNT(*)::numeric, 2) AS avg_views FROM page_views GROUP BY user_id ORDER BY user_id;`, { patterns: ['sessionization'] }),
  Q('P733', 'Bounce sessions', 'saas', ['an_session'], 'Medium', 'Sessions with exactly one view',
    `Count each user's bounce sessions: sessions with exactly one page view. ${SESSRULE} Return user id and bounce_sessions for users with at least one; sorted by user.`, ['user_id', 'bounce_sessions'], true,
    `${SESS} SELECT user_id, COUNT(*) AS bounce_sessions FROM (SELECT user_id, session_no FROM s GROUP BY user_id, session_no HAVING COUNT(*) = 1) b GROUP BY user_id ORDER BY user_id;`,
    ['A second lonely visit', 'Counts follow the sessions.', `INSERT INTO page_views VALUES (5,'2026-02-12 12:00','/home');`],
    ['Sessionize first.', 'Keep sessions with one row.', 'GROUP BY user_id, session_no HAVING COUNT(*) = 1'],
    'Bounce is a property of a session, so it needs session ids before it can be computed.',
    `SELECT user_id, COUNT(*) AS bounce_sessions FROM (SELECT user_id, page FROM page_views GROUP BY user_id, page HAVING COUNT(*) = 1) b GROUP BY user_id ORDER BY user_id;`, { patterns: ['sessionization'] }),
  Q('P734', 'Sessions across midnight', 'saas', ['an_session'], 'Hard', 'Sessions that span two dates',
    `Which sessions start on one calendar date and end on the next? ${SESSRULE} Return user id, session number, start and end time.`, ['user_id', 'session_no', 'start_time', 'end_time'], false,
    `${SESS} SELECT user_id, session_no, MIN(viewed_at) AS start_time, MAX(viewed_at) AS end_time FROM s GROUP BY user_id, session_no HAVING MIN(viewed_at)::date <> MAX(viewed_at)::date;`,
    ['A session ending after midnight', 'Splitting by calendar day would cut it.', `INSERT INTO page_views VALUES (3,'2026-02-10 23:55','/home'),(3,'2026-02-11 00:05','/docs');`],
    ['Sessionize, then compare start and end dates.', 'Use HAVING on the min and max.', 'HAVING MIN(viewed_at)::date <> MAX(viewed_at)::date'],
    'Sessions ignore calendar boundaries. Grouping by day would break this session in two.',
    `SELECT user_id, 1 AS session_no, MIN(viewed_at) AS start_time, MAX(viewed_at) AS end_time FROM page_views GROUP BY user_id HAVING MIN(viewed_at)::date <> MAX(viewed_at)::date;`, { patterns: ['sessionization'] }),
  Q('P735', 'Entry and exit pages', 'saas', ['an_session', 'w_frames'], 'Hard', 'FIRST_VALUE / LAST_VALUE over a session',
    `For each session give the entry page (first view) and the exit page (last view). ${SESSRULE} Return user id, session number, entry_page, exit_page; sorted by user then session.`, ['user_id', 'session_no', 'entry_page', 'exit_page'], true,
    `${SESS} SELECT DISTINCT user_id, session_no, FIRST_VALUE(page) OVER w AS entry_page, LAST_VALUE(page) OVER w AS exit_page FROM s WINDOW w AS (PARTITION BY user_id, session_no ORDER BY viewed_at ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) ORDER BY user_id, session_no;`,
    ['A session ending on a new page', 'The exit page is the last view.', `INSERT INTO page_views VALUES (1,'2026-02-11 08:10','/pricing');`],
    ['First and last row of each session.', 'LAST_VALUE needs a full frame.', 'ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING'],
    'With the default frame LAST_VALUE stops at the current row, so you must widen the frame.',
    `${SESS} SELECT DISTINCT user_id, session_no, FIRST_VALUE(page) OVER w AS entry_page, LAST_VALUE(page) OVER w AS exit_page FROM s WINDOW w AS (PARTITION BY user_id, session_no ORDER BY viewed_at) ORDER BY user_id, session_no;`, { patterns: ['sessionization', 'first_last_event'] }),
  Q('P736', 'Return gaps', 'saas', ['an_session', 'w_offset'], 'Hard', 'Time between sessions',
    `For each session after a user's first, how many minutes passed since the END of their previous session? ${SESSRULE} Return user id, session number and minutes (rounded) for sessions that have a previous session; sorted by user then session.`, ['user_id', 'session_no', 'minutes_since_prev_session'], true,
    `${SESS}, ss AS (SELECT user_id, session_no, MIN(viewed_at) AS st, MAX(viewed_at) AS en FROM s GROUP BY user_id, session_no)
SELECT user_id, session_no, minutes_since_prev_session FROM (SELECT user_id, session_no, ROUND(EXTRACT(EPOCH FROM st - LAG(en) OVER (PARTITION BY user_id ORDER BY session_no)) / 60) AS minutes_since_prev_session FROM ss) t WHERE minutes_since_prev_session IS NOT NULL ORDER BY user_id, session_no;`,
    ['A new later session', 'Gaps are measured end-to-start.', `INSERT INTO page_views VALUES (5,'2026-02-12 12:00','/home');`],
    ['Per-session start and end first.', 'Compare with the previous session\'s end.', 'st - LAG(en) OVER (PARTITION BY user_id ORDER BY session_no)'],
    'The gap between sessions runs from the previous end to the next start, not start to start.',
    `${SESS}, ss AS (SELECT user_id, session_no, MIN(viewed_at) AS st, MAX(viewed_at) AS en FROM s GROUP BY user_id, session_no) SELECT user_id, session_no, minutes_since_prev_session FROM (SELECT user_id, session_no, ROUND(EXTRACT(EPOCH FROM st - LAG(st) OVER (PARTITION BY user_id ORDER BY session_no)) / 60) AS minutes_since_prev_session FROM ss) t WHERE minutes_since_prev_session IS NOT NULL ORDER BY user_id, session_no;`, { patterns: ['sessionization'] }),
];
