// Level 1 — aggregation, built on the food-delivery, HR and rides data.
const P = (o) => ({ v: 1, timeTarget: 7, difficulty: 'Easy', patterns: [], ...o });

export const PROBLEMS_D = [
  P({ id: 'P200', title: 'Delivery KPIs', dataset: 'food', topics: ['a_basic'], skills: 'COUNT, SUM, AVG, MAX', domain: 'Food delivery',
    prompt: 'One row of headline numbers for delivered orders: how many there were, their total order value, the average order value (2 decimals) and the largest order value.',
    output: ['delivered_orders', 'total_value', 'avg_value', 'max_value'], orderMatters: false,
    solution: `SELECT COUNT(*) AS delivered_orders, SUM(order_value) AS total_value, ROUND(AVG(order_value), 2) AS avg_value, MAX(order_value) AS max_value
FROM deliveries WHERE status = 'delivered';`,
    tests: [{ name: 'Huge cancelled order', category: 'Business logic', why: 'Cancelled orders are not part of delivered KPIs.', patch: `INSERT INTO deliveries VALUES (21,6,113,'2026-03-10 20:00',NULL,'cancelled',5000,0,NULL,6.0,NULL);` }],
    hints: ['Filter first, then summarise everything into one row.', 'COUNT(*), SUM(…), AVG(…), MAX(…) with a WHERE on status.', "SELECT COUNT(*), SUM(order_value), ROUND(AVG(order_value),2), MAX(order_value) FROM deliveries WHERE status = 'delivered'"],
    explain: 'Aggregates without GROUP BY collapse all remaining rows into one.',
    trap: `SELECT COUNT(*) AS delivered_orders, SUM(order_value) AS total_value, ROUND(AVG(order_value), 2) AS avg_value, MAX(order_value) AS max_value FROM deliveries;` }),
  P({ id: 'P201', title: 'Rating coverage', dataset: 'food', topics: ['a_basic', 'f_null'], skills: 'COUNT(*) vs COUNT(col), AVG and NULL', domain: 'Food delivery',
    prompt: 'For delivered orders: how many there were, how many were rated, and the average rating among rated orders (2 decimals).',
    output: ['delivered', 'rated', 'avg_rating'], orderMatters: false,
    solution: `SELECT COUNT(*) AS delivered, COUNT(rating) AS rated, ROUND(AVG(rating), 2) AS avg_rating FROM deliveries WHERE status = 'delivered';`,
    tests: [{ name: 'More unrated orders', category: 'NULL handling', why: 'Unrated orders must not count as zero stars.', patch: `INSERT INTO deliveries VALUES (21,3,113,'2026-03-10 12:00','2026-03-10 12:30','delivered',300,25,NULL,2.0,NULL);` }],
    hints: ['COUNT(*) and COUNT(column) differ when the column has NULLs.', 'AVG ignores NULLs automatically — which is what "among rated orders" means.', 'COUNT(*), COUNT(rating), ROUND(AVG(rating), 2)'],
    explain: 'COUNT(rating) counts non-NULL values; AVG(rating) averages only those.',
    trap: `SELECT COUNT(*) AS delivered, COUNT(*) AS rated, ROUND(AVG(COALESCE(rating, 0)), 2) AS avg_rating FROM deliveries WHERE status = 'delivered';`,
    mistakes: [{ re: 'avg\\s*\\(\\s*coalesce', cat: 'NULL handling', msg: 'Counted unrated orders as 0 stars', concept: 'AVG ignores NULLs; COALESCE(x, 0) changes the metric.' }] }),
  P({ id: 'P202', title: 'Two kinds of average tip', dataset: 'food', topics: ['a_basic', 'f_null'], skills: 'Defining the denominator', domain: 'Food delivery', difficulty: 'Medium', timeTarget: 9,
    prompt: 'Product wants two numbers for delivered orders (2 decimals each):\n1. `avg_tip_all` — average tip across ALL delivered orders, treating "no tip recorded" as ₹0.\n2. `avg_tip_when_tipped` — average tip across orders where the tip was greater than ₹0.',
    output: ['avg_tip_all', 'avg_tip_when_tipped'], orderMatters: false,
    solution: `SELECT ROUND(AVG(COALESCE(tip, 0)), 2) AS avg_tip_all,
       ROUND(AVG(tip) FILTER (WHERE tip > 0), 2) AS avg_tip_when_tipped
FROM deliveries WHERE status = 'delivered';`,
    tests: [{ name: 'A ₹0 tip', category: 'Business logic', why: 'A recorded ₹0 is not "tipped".', patch: `INSERT INTO deliveries VALUES (21,3,113,'2026-03-10 12:00','2026-03-10 12:30','delivered',300,25,0,2.0,4);` }],
    hints: ['Same column, two different denominators.', 'For the first, missing means 0. For the second, only tips above 0 count — CASE or FILTER can restrict an aggregate.', 'AVG(COALESCE(tip,0)) and AVG(CASE WHEN tip > 0 THEN tip END)'],
    explain: 'Both are "average tip", but with different populations. Always say which one you report.',
    trap: `SELECT ROUND(AVG(tip), 2) AS avg_tip_all, ROUND(AVG(tip), 2) AS avg_tip_when_tipped FROM deliveries WHERE status = 'delivered';`,
    reasoning: [{ q: 'Order 7 has a tip of ₹0 recorded. Is it in the denominator of avg_tip_when_tipped?', options: ['Yes', 'No'], answer: 1, why: 'Only tips greater than 0 count as "tipped".' }] }),
  P({ id: 'P203', title: 'Orders per restaurant', dataset: 'food', topics: ['a_groupby'], skills: 'GROUP BY + COUNT', domain: 'Food delivery',
    prompt: 'How many orders (any status) did each restaurant receive? Most orders first; ties by restaurant_id.',
    output: ['restaurant_id', 'orders'], orderMatters: true,
    solution: `SELECT restaurant_id, COUNT(*) AS orders FROM deliveries GROUP BY restaurant_id ORDER BY orders DESC, restaurant_id;`,
    tests: [{ name: 'Cancelled orders count too', category: 'Aggregation', why: '"Any status" includes cancellations.', patch: `INSERT INTO deliveries VALUES (21,2,113,'2026-03-10 08:00',NULL,'cancelled',150,0,NULL,1.0,NULL);` }],
    hints: ['One output row per restaurant.', 'GROUP BY restaurant_id with COUNT(*).', 'SELECT restaurant_id, COUNT(*) AS orders FROM deliveries GROUP BY restaurant_id ORDER BY orders DESC, restaurant_id'],
    explain: 'GROUP BY makes one row per distinct value; aggregates summarise each group.',
    trap: `SELECT restaurant_id, COUNT(delivered_at) AS orders FROM deliveries GROUP BY restaurant_id ORDER BY orders DESC, restaurant_id;` }),
  P({ id: 'P204', title: 'Daily order book', dataset: 'food', topics: ['a_groupby', 'f_dates'], skills: 'GROUP BY two columns, date bucketing', domain: 'Food delivery', difficulty: 'Medium', timeTarget: 9,
    prompt: 'For each order date and status, report the number of orders and their total value. Sort by date, then status.',
    output: ['order_date', 'status', 'orders', 'total_value'], orderMatters: true,
    solution: `SELECT ordered_at::date AS order_date, status, COUNT(*) AS orders, SUM(order_value) AS total_value
FROM deliveries GROUP BY ordered_at::date, status ORDER BY order_date, status;`,
    tests: [{ name: 'Two orders same day, different times', category: 'Dates/time', why: 'Group by the date, not the timestamp.', patch: `INSERT INTO deliveries VALUES (21,3,113,'2026-03-01 21:30','2026-03-01 22:00','delivered',300,25,NULL,2.0,4);` }],
    hints: ['ordered_at has a time. What do you need to group by?', 'Convert to a date with ::date and group by it plus status.', 'GROUP BY ordered_at::date, status'],
    explain: 'The output grain (date, status) is exactly the GROUP BY list.',
    trap: `SELECT ordered_at AS order_date, status, COUNT(*) AS orders, SUM(order_value) AS total_value FROM deliveries GROUP BY ordered_at, status ORDER BY order_date, status;` }),
  P({ id: 'P205', title: 'Headcount and payroll', dataset: 'hr', topics: ['a_groupby', 'f_null'], skills: 'GROUP BY with a NULL group', domain: 'HR', difficulty: 'Medium', timeTarget: 8,
    prompt: 'For each dept_id — including employees with no department, shown as an empty dept_id — report headcount, total salary and average salary (2 decimals). Sort by dept_id with the empty group last.',
    output: ['dept_id', 'headcount', 'total_salary', 'avg_salary'], orderMatters: true,
    solution: `SELECT dept_id, COUNT(*) AS headcount, SUM(salary) AS total_salary, ROUND(AVG(salary), 2) AS avg_salary
FROM employees GROUP BY dept_id ORDER BY dept_id NULLS LAST;`,
    tests: [{ name: 'Another unassigned employee', category: 'NULL handling', why: 'GROUP BY puts all NULLs in one group.', patch: `INSERT INTO employees VALUES (17,'Advik',NULL,1,'Advisor',90000,'2025-01-01');` }],
    hints: ['GROUP BY treats NULL as its own group — do you need to do anything special?', 'Nothing special for grouping; just don\'t filter NULLs out. NULLS LAST controls sorting.', 'GROUP BY dept_id ORDER BY dept_id NULLS LAST'],
    explain: 'Unlike comparisons, GROUP BY puts all NULLs together into one group.',
    trap: `SELECT dept_id, COUNT(*) AS headcount, SUM(salary) AS total_salary, ROUND(AVG(salary), 2) AS avg_salary FROM employees WHERE dept_id IS NOT NULL GROUP BY dept_id ORDER BY dept_id;` }),
  P({ id: 'P206', title: 'Busy restaurants', dataset: 'food', topics: ['a_having'], skills: 'HAVING', domain: 'Food delivery',
    prompt: 'Which restaurants received at least 3 orders (any status)? Sort by restaurant_id.',
    output: ['restaurant_id', 'orders'], orderMatters: true,
    solution: `SELECT restaurant_id, COUNT(*) AS orders FROM deliveries GROUP BY restaurant_id HAVING COUNT(*) >= 3 ORDER BY restaurant_id;`,
    tests: [{ name: 'Restaurant reaching exactly 3', category: 'Edge cases', why: '"At least 3" includes 3.', patch: `INSERT INTO deliveries VALUES (21,2,113,'2026-03-10 08:00','2026-03-10 08:20','delivered',150,20,NULL,1.0,5);` }],
    hints: ['The condition is about a count per restaurant, not about individual rows.', 'Conditions on aggregates go in HAVING, after GROUP BY.', 'GROUP BY restaurant_id HAVING COUNT(*) >= 3'],
    explain: 'WHERE filters rows before grouping; HAVING filters groups after.',
    trap: `SELECT restaurant_id, COUNT(*) AS orders FROM deliveries GROUP BY restaurant_id HAVING COUNT(*) > 3 ORDER BY restaurant_id;`, techniques: ['having'] }),
  P({ id: 'P207', title: 'Valuable regulars', dataset: 'food', topics: ['a_having'], skills: 'WHERE + GROUP BY + HAVING with two conditions', domain: 'Food delivery', difficulty: 'Medium', timeTarget: 9,
    prompt: 'Find customers with at least 2 delivered orders whose delivered orders add up to ₹1,000 or more. Show the number of delivered orders and the total. Sort by total, highest first.',
    output: ['customer_id', 'orders', 'total_value'], orderMatters: true,
    solution: `SELECT customer_id, COUNT(*) AS orders, SUM(order_value) AS total_value
FROM deliveries WHERE status = 'delivered'
GROUP BY customer_id HAVING COUNT(*) >= 2 AND SUM(order_value) >= 1000
ORDER BY total_value DESC;`,
    tests: [{ name: 'Big spender with only cancelled extras', category: 'Business logic', why: 'Cancelled orders must not count toward either condition.', patch: `INSERT INTO deliveries VALUES (21,6,104,'2026-03-10 20:00',NULL,'cancelled',2000,0,NULL,6.0,NULL);` }],
    hints: ['Which condition is about rows and which about groups?', 'status goes in WHERE; both thresholds go in HAVING.', "WHERE status = 'delivered' GROUP BY customer_id HAVING COUNT(*) >= 2 AND SUM(order_value) >= 1000"],
    explain: 'Filter the population first (WHERE), then test group-level thresholds (HAVING).',
    trap: `SELECT customer_id, COUNT(*) AS orders, SUM(order_value) AS total_value FROM deliveries GROUP BY customer_id HAVING COUNT(*) >= 2 AND SUM(order_value) >= 1000 ORDER BY total_value DESC;` }),
  P({ id: 'P208', title: 'Cancellation rate', dataset: 'food', topics: ['a_conditional'], skills: 'Conditional count + rate', domain: 'Food delivery', difficulty: 'Medium', timeTarget: 9,
    prompt: 'For each restaurant with orders: total orders, cancelled orders and the cancellation rate as a percentage (1 decimal). Highest rate first, then restaurant_id.',
    output: ['restaurant_id', 'orders', 'cancelled', 'cancel_rate_pct'], orderMatters: true,
    solution: `SELECT restaurant_id, COUNT(*) AS orders,
       COUNT(*) FILTER (WHERE status = 'cancelled') AS cancelled,
       ROUND(100.0 * COUNT(*) FILTER (WHERE status = 'cancelled') / COUNT(*), 1) AS cancel_rate_pct
FROM deliveries GROUP BY restaurant_id ORDER BY cancel_rate_pct DESC, restaurant_id;`,
    tests: [{ name: 'Another cancellation', category: 'Aggregation', why: 'Rates must update with the data.', patch: `INSERT INTO deliveries VALUES (21,3,113,'2026-03-10 12:00',NULL,'cancelled',300,0,NULL,2.0,NULL);` }],
    hints: ['You need a count of a subset next to the total, per restaurant.', 'COUNT(*) FILTER (WHERE …) or SUM(CASE WHEN … THEN 1 ELSE 0 END). Beware integer division.', "ROUND(100.0 * COUNT(*) FILTER (WHERE status='cancelled') / COUNT(*), 1)"],
    explain: 'Conditional aggregation computes subset counts and totals in one pass; 100.0 forces decimal division.',
    trap: `SELECT restaurant_id, COUNT(*) AS orders, SUM(CASE WHEN status='cancelled' THEN 1 ELSE 0 END) AS cancelled, ROUND(SUM(CASE WHEN status='cancelled' THEN 1 ELSE 0 END) / COUNT(*) * 100, 1) AS cancel_rate_pct FROM deliveries GROUP BY restaurant_id ORDER BY cancel_rate_pct DESC, restaurant_id;`,
    techniques: ['filter\\s*\\(\\s*where|sum\\s*\\(\\s*case|count\\s*\\(\\s*case'], patterns: ['conditional_agg'] }),
  P({ id: 'P209', title: 'Who tips', dataset: 'food', topics: ['a_conditional', 'f_null'], skills: 'Conditional counts with NULL and 0', domain: 'Food delivery', difficulty: 'Medium', timeTarget: 9,
    prompt: 'For delivered orders, one row: the number of orders, the number with a tip above ₹0, the number without a tip (missing OR ₹0), and the share tipped as a percentage (1 decimal).',
    output: ['delivered', 'tipped', 'not_tipped', 'tipped_pct'], orderMatters: false,
    solution: `SELECT COUNT(*) AS delivered,
       COUNT(*) FILTER (WHERE tip > 0) AS tipped,
       COUNT(*) FILTER (WHERE tip IS NULL OR tip = 0) AS not_tipped,
       ROUND(100.0 * COUNT(*) FILTER (WHERE tip > 0) / COUNT(*), 1) AS tipped_pct
FROM deliveries WHERE status = 'delivered';`,
    tests: [{ name: 'Another ₹0 tip', category: 'NULL handling', why: '₹0 belongs with "not tipped".', patch: `INSERT INTO deliveries VALUES (21,3,113,'2026-03-10 12:00','2026-03-10 12:30','delivered',300,25,0,2.0,4);` }],
    hints: ['tipped + not_tipped should equal delivered. Check that.', 'NULL fails "tip > 0" and also fails "tip = 0" — handle it explicitly.', 'FILTER (WHERE tip > 0) and FILTER (WHERE tip IS NULL OR tip = 0)'],
    explain: 'A quick sanity check — do the parts add up to the whole? — catches NULL mistakes.',
    trap: `SELECT COUNT(*) AS delivered, COUNT(*) FILTER (WHERE tip > 0) AS tipped, COUNT(*) FILTER (WHERE tip IS NULL) AS not_tipped, ROUND(100.0 * COUNT(*) FILTER (WHERE tip > 0) / COUNT(*), 1) AS tipped_pct FROM deliveries WHERE status = 'delivered';` }),
  P({ id: 'P210', title: 'Rating scorecard', dataset: 'food', topics: ['a_conditional', 'a_groupby'], skills: 'Several conditional counts per group', domain: 'Food delivery', difficulty: 'Medium', timeTarget: 10,
    prompt: 'For each restaurant with delivered orders: delivered orders, 5-star ratings, low ratings (2 stars or fewer) and unrated deliveries. Sort by restaurant_id.',
    output: ['restaurant_id', 'delivered', 'five_star', 'low_rated', 'unrated'], orderMatters: true,
    solution: `SELECT restaurant_id, COUNT(*) AS delivered,
       COUNT(*) FILTER (WHERE rating = 5) AS five_star,
       COUNT(*) FILTER (WHERE rating <= 2) AS low_rated,
       COUNT(*) FILTER (WHERE rating IS NULL) AS unrated
FROM deliveries WHERE status = 'delivered' GROUP BY restaurant_id ORDER BY restaurant_id;`,
    tests: [{ name: 'One-star delivery', category: 'Edge cases', why: 'Low ratings include 1 star.', patch: `INSERT INTO deliveries VALUES (21,7,113,'2026-03-10 17:00','2026-03-10 17:30','delivered',300,25,NULL,2.0,1);` }],
    hints: ['One row per restaurant, four counts of different subsets.', 'Each count gets its own condition.', 'COUNT(*) FILTER (WHERE rating = 5), … (WHERE rating <= 2), … (WHERE rating IS NULL)'],
    explain: 'Conditional aggregation turns "rows by rating" into a scorecard with one column per bucket.',
    trap: `SELECT restaurant_id, COUNT(*) AS delivered, COUNT(*) FILTER (WHERE rating = 5) AS five_star, COUNT(*) FILTER (WHERE rating = 2) AS low_rated, COUNT(*) FILTER (WHERE rating IS NULL) AS unrated FROM deliveries WHERE status = 'delivered' GROUP BY restaurant_id ORDER BY restaurant_id;`,
    patterns: ['conditional_agg'] }),
  P({ id: 'P211', title: 'Unique customers', dataset: 'food', topics: ['a_distinct'], skills: 'COUNT(DISTINCT)', domain: 'Food delivery',
    prompt: 'One row: the number of distinct customers who placed any order, and the number of distinct customers with at least one delivered order.',
    output: ['customers', 'customers_delivered'], orderMatters: false,
    solution: `SELECT COUNT(DISTINCT customer_id) AS customers,
       COUNT(DISTINCT customer_id) FILTER (WHERE status = 'delivered') AS customers_delivered
FROM deliveries;`,
    tests: [{ name: 'Customer whose only order was cancelled', category: 'Business logic', why: 'They placed an order but received none.', patch: `INSERT INTO deliveries VALUES (21,3,199,'2026-03-10 12:00',NULL,'cancelled',300,0,NULL,2.0,NULL);` }],
    hints: ['Orders ≠ customers: one customer can order many times.', 'COUNT(DISTINCT …), optionally restricted with FILTER or CASE.', "COUNT(DISTINCT customer_id), COUNT(DISTINCT customer_id) FILTER (WHERE status = 'delivered')"],
    explain: 'COUNT(DISTINCT) counts entities in event-grain data. COUNT(DISTINCT CASE WHEN … THEN customer_id END) is the portable form.',
    trap: `SELECT COUNT(customer_id) AS customers, COUNT(customer_id) FILTER (WHERE status = 'delivered') AS customers_delivered FROM deliveries;`, techniques: ['count\\s*\\(\\s*distinct'] }),
  P({ id: 'P212', title: 'Repeat customers per restaurant', dataset: 'food', topics: ['a_distinct', 'a_groupby'], skills: 'COUNT(DISTINCT) per group + ratio', domain: 'Food delivery', difficulty: 'Medium', timeTarget: 9,
    prompt: 'For each restaurant, using delivered orders: number of orders, number of unique customers, and orders per customer (2 decimals). Sort by restaurant_id.',
    output: ['restaurant_id', 'orders', 'unique_customers', 'orders_per_customer'], orderMatters: true,
    solution: `SELECT restaurant_id, COUNT(*) AS orders, COUNT(DISTINCT customer_id) AS unique_customers,
       ROUND(COUNT(*)::numeric / COUNT(DISTINCT customer_id), 2) AS orders_per_customer
FROM deliveries WHERE status = 'delivered' GROUP BY restaurant_id ORDER BY restaurant_id;`,
    tests: [{ name: 'Regular orders again', category: 'Aggregation', why: 'Repeat orders raise orders, not unique customers.', patch: `INSERT INTO deliveries VALUES (21,6,105,'2026-03-10 20:00','2026-03-10 20:40','delivered',900,50,NULL,6.0,5);` }],
    hints: ['Two counts: rows and distinct people.', 'COUNT(DISTINCT customer_id) for people. Cast before dividing two integers.', 'ROUND(COUNT(*)::numeric / COUNT(DISTINCT customer_id), 2)'],
    explain: 'COUNT(*) / COUNT(DISTINCT …) is integer division in PostgreSQL; cast one side to numeric.',
    trap: `SELECT restaurant_id, COUNT(*) AS orders, COUNT(customer_id) AS unique_customers, ROUND(COUNT(*)::numeric / COUNT(customer_id), 2) AS orders_per_customer FROM deliveries WHERE status = 'delivered' GROUP BY restaurant_id ORDER BY restaurant_id;` }),
];
