// Level 7b — rolling metrics (P740–745), segmentation (P750–756), anomalies (P760–765), attribution & conversion (P770–777).
import { Q } from './q.js';
const OVD = `SELECT o.order_id, o.customer_id, o.order_date, o.coupon_code, SUM(oi.quantity * oi.unit_price) AS value FROM orders o JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' GROUP BY o.order_id, o.customer_id, o.order_date, o.coupon_code`;
const SPEND = `SELECT customer_id, SUM(value) AS spend FROM (${OVD}) ov GROUP BY customer_id`;
const ATTR = `WITH p AS (SELECT event_id, user_id, event_time, revenue FROM ad_events WHERE event_type = 'purchase'),
c AS (SELECT DISTINCT user_id, campaign_id, event_time FROM ad_events WHERE event_type = 'click'),
a AS (SELECT p.event_id, p.revenue, p.event_time AS pt, l.campaign_id, l.event_time AS ct FROM p LEFT JOIN LATERAL (SELECT c.campaign_id, c.event_time FROM c WHERE c.user_id = p.user_id AND c.event_time <= p.event_time AND c.event_time >= p.event_time - INTERVAL '7 days' ORDER BY c.event_time DESC, c.campaign_id LIMIT 1) l ON true)`;
const WIN = 'A purchase is attributed to the user\'s most recent click made up to 7 days (inclusive) before it; with no such click it is "direct".';

export const PROBLEMS_K = [
  // ── Rolling metrics ──
  Q('P740', 'Daily actives with a 7-day average', 'saas', ['an_rolling', 'x_dates'], 'Hard', 'Spine so empty days count as zero',
    'For every date from 2026-03-01 to 2026-03-10, the number of distinct active users (user_activity) and the average of the last 7 days\' counts including today (2 decimals; early days average what exists). Days with no activity count as 0. Return day, dau, dau_7d_avg; sorted by day.', ['day', 'dau', 'dau_7d_avg'], true,
    `WITH d AS (SELECT g::date AS day FROM generate_series(DATE '2026-03-01', DATE '2026-03-10', INTERVAL '1 day') g), a AS (SELECT d.day, COUNT(DISTINCT u.user_id) AS dau FROM d LEFT JOIN user_activity u ON u.activity_date = d.day GROUP BY d.day)
SELECT day, dau, ROUND(AVG(dau) OVER (ORDER BY day ROWS BETWEEN 6 PRECEDING AND CURRENT ROW), 2) AS dau_7d_avg FROM a ORDER BY day;`,
    ['Activity on the missing day', 'Every date must stay in the series.', `INSERT INTO user_activity VALUES (3,'2026-03-09');`],
    ['03-09 has no rows at all.', 'Build the calendar first.', 'generate_series … LEFT JOIN user_activity, then AVG(dau) OVER (… ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)'],
    'A ROWS frame counts rows, not days: missing dates must exist as rows (value 0) for the window to mean "7 days".',
    `WITH a AS (SELECT activity_date AS day, COUNT(DISTINCT user_id) AS dau FROM user_activity GROUP BY activity_date) SELECT day, dau, ROUND(AVG(dau) OVER (ORDER BY day ROWS BETWEEN 6 PRECEDING AND CURRENT ROW), 2) AS dau_7d_avg FROM a ORDER BY day;`, { patterns: ['rolling_avg', 'date_spine'] }),
  Q('P741', 'Spend in the last 7 days', 'bank', ['an_rolling'], 'Hard', 'RANGE window in time units',
    'For every debit (negative transaction), the account\'s total debit spend (as a positive number) in the 7 days up to and including that debit. Return txn id, account id, spend_7d; sorted by txn id.', ['txn_id', 'account_id', 'spend_7d'], true,
    `SELECT txn_id, account_id, spend_7d FROM (SELECT txn_id, account_id, amount, SUM(CASE WHEN amount < 0 THEN -amount ELSE 0 END) OVER (PARTITION BY account_id ORDER BY txn_time RANGE BETWEEN INTERVAL '7 days' PRECEDING AND CURRENT ROW) AS spend_7d FROM transactions) t WHERE amount < 0 ORDER BY txn_id;`,
    ['A debit eight days later', 'It falls outside the earlier window.', `INSERT INTO transactions VALUES (19,'A1','2026-01-23 10:00',-100,'card','Cafe');`],
    ['The window is 7 days, not 7 rows.', 'RANGE can use an interval on timestamps.', "RANGE BETWEEN INTERVAL '7 days' PRECEDING AND CURRENT ROW"],
    'Irregular event times need a RANGE frame; a ROWS frame would span a varying number of days.',
    `SELECT txn_id, account_id, spend_7d FROM (SELECT txn_id, account_id, amount, SUM(CASE WHEN amount < 0 THEN -amount ELSE 0 END) OVER (PARTITION BY account_id ORDER BY txn_time ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS spend_7d FROM transactions) t WHERE amount < 0 ORDER BY txn_id;`, { patterns: ['rolling_avg'] }),
  Q('P742', 'Week-over-week trips', 'rides', ['an_rolling', 'w_offset'], 'Medium', 'Growth versus the previous period',
    'Trip requests per ISO week (week starts Monday) with the percentage change versus the previous week (1 decimal; empty for the first). Return week start, trips, wow_pct; sorted by week.', ['week_start', 'trips', 'wow_pct'], true,
    `WITH w AS (SELECT date_trunc('week', requested_at)::date AS week_start, COUNT(*) AS trips FROM trips GROUP BY 1) SELECT week_start, trips, ROUND(100.0 * (trips - LAG(trips) OVER (ORDER BY week_start)) / LAG(trips) OVER (ORDER BY week_start), 1) AS wow_pct FROM w ORDER BY week_start;`,
    ['A third week', 'Each week compares with the one before.', `INSERT INTO trips VALUES (521,7,16,'Mumbai','2026-02-10 09:00','completed',100,3.0),(522,7,16,'Mumbai','2026-02-11 09:00','completed',100,3.0);`],
    ['Weekly totals first.', 'Compare with the previous week.', '(trips − LAG(trips)) / LAG(trips)'],
    'Growth is relative to the earlier period.',
    `WITH w AS (SELECT date_trunc('week', requested_at)::date AS week_start, COUNT(*) AS trips FROM trips GROUP BY 1) SELECT week_start, trips, ROUND(100.0 * (trips - LAG(trips) OVER (ORDER BY week_start)) / trips, 1) AS wow_pct FROM w ORDER BY week_start;`, { patterns: ['prev_next'] }),
  Q('P743', 'Signups: cumulative and trailing week', 'saas', ['an_rolling'], 'Hard', 'Running total and a date-range window together',
    'For each date with signups: signups that day, the cumulative number of signups so far and the signups in the trailing 7 days (that day and the 6 before). Return signup_date, signups, cum_signups, trailing_7d; sorted by date.', ['signup_date', 'signups', 'cum_signups', 'trailing_7d'], true,
    `WITH d AS (SELECT signup_date, COUNT(*) AS signups FROM users GROUP BY signup_date) SELECT signup_date, signups, SUM(signups) OVER (ORDER BY signup_date) AS cum_signups, SUM(signups) OVER (ORDER BY signup_date RANGE BETWEEN INTERVAL '6 days' PRECEDING AND CURRENT ROW) AS trailing_7d FROM d ORDER BY signup_date;`,
    ['Two signups on one new day', 'Daily totals feed the windows.', `INSERT INTO users VALUES (13,'2026-03-19','IN','organic'),(14,'2026-03-19','US','organic');`],
    ['Signups per date first.', 'Dates are sparse, so the trailing window is a date range.', "RANGE BETWEEN INTERVAL '6 days' PRECEDING AND CURRENT ROW"],
    'Sparse dates break ROWS windows; RANGE with an interval works on the actual calendar.',
    `WITH d AS (SELECT signup_date, COUNT(*) AS signups FROM users GROUP BY signup_date) SELECT signup_date, signups, SUM(signups) OVER (ORDER BY signup_date) AS cum_signups, SUM(signups) OVER (ORDER BY signup_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS trailing_7d FROM d ORDER BY signup_date;`, { patterns: ['rolling_avg', 'running_total'] }),
  Q('P744', 'Average of the last three orders', 'shop', ['an_rolling'], 'Medium', 'Per-customer moving average',
    'For each completed order, the average value of that order and the customer\'s previous two completed orders (2 decimals; fewer orders use what exists). Return order id, customer id, value, avg_last3; sorted by order id.', ['order_id', 'customer_id', 'value', 'avg_last3'], true,
    `WITH ov AS (${OVD}) SELECT order_id, customer_id, value, ROUND(AVG(value) OVER (PARTITION BY customer_id ORDER BY order_date, order_id ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 2) AS avg_last3 FROM ov ORDER BY order_id;`,
    ['A fifth order', 'The window slides per customer.', `INSERT INTO orders VALUES (1018,1,'2026-04-20','completed',NULL); INSERT INTO order_items VALUES (1018,105,1,2999);`],
    ['Order value per order first.', 'The window must stay inside one customer.', 'AVG(value) OVER (PARTITION BY customer_id ORDER BY order_date, order_id ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)'],
    'Without PARTITION BY the window would average other customers\' orders too.',
    `WITH ov AS (${OVD}) SELECT order_id, customer_id, value, ROUND(AVG(value) OVER (ORDER BY order_date, order_id ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 2) AS avg_last3 FROM ov ORDER BY order_id;`, { patterns: ['rolling_avg'] }),
  Q('P745', 'March stickiness', 'saas', ['an_rolling', 'a_distinct'], 'Hard', 'DAU/MAU with a fixed denominator',
    'For March 2026 using user_activity: the average daily active users across ALL 31 days of March (2 decimals), the monthly active users (distinct users active at least once) and stickiness = avg DAU ÷ MAU as a percentage (1 decimal). One row: avg_dau, mau, stickiness_pct.', ['avg_dau', 'mau', 'stickiness_pct'], false,
    `WITH d AS (SELECT activity_date, COUNT(DISTINCT user_id) AS dau FROM user_activity WHERE activity_date >= DATE '2026-03-01' AND activity_date < DATE '2026-04-01' GROUP BY activity_date),
m AS (SELECT COUNT(DISTINCT user_id) AS mau FROM user_activity WHERE activity_date >= DATE '2026-03-01' AND activity_date < DATE '2026-04-01')
SELECT ROUND(SUM(d.dau) / 31.0, 2) AS avg_dau, m.mau, ROUND(100.0 * SUM(d.dau) / 31.0 / m.mau, 1) AS stickiness_pct FROM d CROSS JOIN m GROUP BY m.mau;`,
    ['Activity on a new day', 'The 31-day denominator is fixed.', `INSERT INTO user_activity VALUES (2,'2026-03-20'),(3,'2026-03-20');`],
    ['Days without activity count as zero.', 'Divide total user-days by the number of days in the month.', 'SUM(dau) / 31.0'],
    'Averaging only over days that have rows overstates DAU; the denominator is the calendar length.',
    `WITH d AS (SELECT activity_date, COUNT(DISTINCT user_id) AS dau FROM user_activity WHERE activity_date >= DATE '2026-03-01' AND activity_date < DATE '2026-04-01' GROUP BY activity_date), m AS (SELECT COUNT(DISTINCT user_id) AS mau FROM user_activity WHERE activity_date >= DATE '2026-03-01' AND activity_date < DATE '2026-04-01') SELECT ROUND(AVG(d.dau), 2) AS avg_dau, m.mau, ROUND(100.0 * AVG(d.dau) / m.mau, 1) AS stickiness_pct FROM d CROSS JOIN m GROUP BY m.mau;`),

  // ── Segmentation ──
  Q('P750', 'Spend tiers', 'shop', ['an_segment', 'w_ranking'], 'Medium', 'NTILE tiers among buyers only',
    'Among customers with completed spend, split them into three equal tiers by spend: high (top third), medium, low (ties by customer id). Return customer id, spend and tier, sorted by spend desc then id.', ['customer_id', 'spend', 'tier'], true,
    `WITH s AS (${SPEND}) SELECT customer_id, spend, CASE NTILE(3) OVER (ORDER BY spend DESC, customer_id) WHEN 1 THEN 'high' WHEN 2 THEN 'medium' ELSE 'low' END AS tier FROM s ORDER BY spend DESC, customer_id;`,
    ['A new buyer', 'Tier sizes follow the buyer count.', `INSERT INTO orders VALUES (1018,10,'2026-04-12','completed',NULL); INSERT INTO order_items VALUES (1018,106,1,899);`],
    ['Who is in the population?', 'Customers who have not bought have no spend to tier.', 'NTILE(3) OVER (ORDER BY spend DESC, customer_id)'],
    'Tiering includes only the population you mean; adding zero-spend customers pushes real buyers into higher tiers.',
    `WITH s AS (SELECT c.customer_id, COALESCE(SUM(ov.value), 0) AS spend FROM customers c LEFT JOIN (${OVD}) ov ON ov.customer_id = c.customer_id GROUP BY c.customer_id) SELECT customer_id, spend, CASE NTILE(3) OVER (ORDER BY spend DESC, customer_id) WHEN 1 THEN 'high' WHEN 2 THEN 'medium' ELSE 'low' END AS tier FROM s ORDER BY spend DESC, customer_id;`, { patterns: ['segmentation'] }),
  Q('P751', 'The 80% customers', 'shop', ['an_segment', 'w_aggregate'], 'Hard', 'Pareto: customers up to 80% of revenue',
    'Sort customers by completed spend (highest first, ties by id). Return the customers needed to reach 80% of total revenue: include a customer if the share accumulated BEFORE them is below 80%. Return customer id, spend and cumulative percent (1 decimal), in that order.', ['customer_id', 'spend', 'cum_pct'], true,
    `WITH s AS (${SPEND}), c AS (SELECT customer_id, spend, SUM(spend) OVER (ORDER BY spend DESC, customer_id) AS cum, SUM(spend) OVER () AS total FROM s) SELECT customer_id, spend, ROUND(100.0 * cum / total, 1) AS cum_pct FROM c WHERE cum - spend < 0.8 * total ORDER BY spend DESC, customer_id;`,
    ['A whale customer', 'One big customer can reach 80% alone.', `INSERT INTO orders VALUES (1018,10,'2026-04-12','completed',NULL); INSERT INTO order_items VALUES (1018,105,200,2999);`],
    ['Running share of revenue.', 'The customer who crosses 80% is still needed.', 'cum - spend < 0.8 * total'],
    'Filtering on cumulative ≤ 80% leaves out the customer who actually crosses the line.',
    `WITH s AS (${SPEND}), c AS (SELECT customer_id, spend, SUM(spend) OVER (ORDER BY spend DESC, customer_id) AS cum, SUM(spend) OVER () AS total FROM s) SELECT customer_id, spend, ROUND(100.0 * cum / total, 1) AS cum_pct FROM c WHERE cum <= 0.8 * total ORDER BY spend DESC, customer_id;`, { patterns: ['pct_of_total', 'segmentation'] }),
  Q('P752', 'Favourite category', 'shop', ['an_segment', 'w_ranking'], 'Hard', 'Top category per customer by spend',
    'For each customer with completed orders: the category they spent the most on (ties: alphabetical) and that spend. Return customer id, top category, spend; sorted by customer id.', ['customer_id', 'top_category', 'spend'], true,
    `WITH cs AS (SELECT o.customer_id, p.category, SUM(oi.quantity * oi.unit_price) AS spend FROM orders o JOIN order_items oi ON oi.order_id = o.order_id JOIN products p ON p.product_id = oi.product_id WHERE o.status = 'completed' GROUP BY o.customer_id, p.category),
r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY spend DESC, category) AS rn FROM cs) SELECT customer_id, category AS top_category, spend FROM r WHERE rn = 1 ORDER BY customer_id;`,
    ['A tie between categories', 'Ties go to the alphabetically first category.', `INSERT INTO orders VALUES (1018,9,'2026-04-12','completed',NULL); INSERT INTO order_items VALUES (1018,104,1,1199);`],
    ['Spend per customer and category first.', 'Rank within the customer.', 'ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY spend DESC, category)'],
    'Order by the measure (spend), then a deterministic tie-breaker.',
    `WITH cs AS (SELECT o.customer_id, p.category, SUM(oi.quantity * oi.unit_price) AS spend FROM orders o JOIN order_items oi ON oi.order_id = o.order_id JOIN products p ON p.product_id = oi.product_id WHERE o.status = 'completed' GROUP BY o.customer_id, p.category), r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY category) AS rn FROM cs) SELECT customer_id, category AS top_category, spend FROM r WHERE rn = 1 ORDER BY customer_id;`, { patterns: ['segmentation', 'top_n_per_group'] }),
  Q('P753', 'Basket size mix', 'shop', ['an_segment'], 'Medium', 'Classify orders by units',
    'Classify completed orders by total units: small (1 unit), medium (2–3 units), large (4 or more). How many orders fall in each class? Return size_segment and orders, in the order small, medium, large (skip empty classes).', ['size_segment', 'orders'], true,
    `WITH u AS (SELECT o.order_id, SUM(oi.quantity) AS units FROM orders o JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' GROUP BY o.order_id)
SELECT CASE WHEN units = 1 THEN 'small' WHEN units <= 3 THEN 'medium' ELSE 'large' END AS size_segment, COUNT(*) AS orders FROM u GROUP BY 1 ORDER BY MIN(units);`,
    ['A bulk order', 'Units, not line items, define size.', `INSERT INTO orders VALUES (1018,9,'2026-04-12','completed',NULL); INSERT INTO order_items VALUES (1018,107,10,349);`],
    ['Size is about units.', 'Sum quantity per order first.', 'SUM(quantity) per order, then CASE'],
    'Counting line items measures variety, not size; 10 units of one product is one line.',
    `WITH u AS (SELECT o.order_id, COUNT(*) AS units FROM orders o JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' GROUP BY o.order_id) SELECT CASE WHEN units = 1 THEN 'small' WHEN units <= 3 THEN 'medium' ELSE 'large' END AS size_segment, COUNT(*) AS orders FROM u GROUP BY 1 ORDER BY MIN(units);`, { patterns: ['segmentation'] }),
  Q('P754', 'Active vs dormant by city', 'shop', ['an_segment', 'j_left'], 'Hard', 'Segment flag per customer, then pivot',
    'As of 2026-04-30, a customer is ACTIVE if they completed an order in the last 60 days (order date after 2026-03-01) and DORMANT otherwise (including customers who never ordered). For each known city: active customers, dormant customers and total. Sort by city.', ['city', 'active_customers', 'dormant_customers', 'total'], true,
    `WITH act AS (SELECT DISTINCT customer_id FROM orders WHERE status = 'completed' AND order_date > DATE '2026-04-30' - 60)
SELECT c.city, COUNT(*) FILTER (WHERE a.customer_id IS NOT NULL) AS active_customers, COUNT(*) FILTER (WHERE a.customer_id IS NULL) AS dormant_customers, COUNT(*) AS total
FROM customers c LEFT JOIN act a ON a.customer_id = c.customer_id WHERE c.city IS NOT NULL GROUP BY c.city ORDER BY c.city;`,
    ['An order exactly 60 days ago', 'The cut-off is strictly after 2026-03-01.', `INSERT INTO orders VALUES (1018,3,'2026-03-01','completed',NULL);`],
    ['Flag active customers once.', 'Keep customers with no orders.', 'LEFT JOIN a distinct list of recent buyers'],
    'Dormancy includes people with no orders at all, so the flag must come from a LEFT JOIN, not an inner join.',
    `WITH act AS (SELECT DISTINCT customer_id FROM orders WHERE status = 'completed' AND order_date > DATE '2026-04-30' - 60) SELECT c.city, COUNT(*) AS active_customers, 0 AS dormant_customers, COUNT(*) AS total FROM customers c JOIN act a ON a.customer_id = c.customer_id WHERE c.city IS NOT NULL GROUP BY c.city ORDER BY c.city;`, { patterns: ['segmentation'] }),
  Q('P755', 'Power users', 'saas', ['an_segment', 'w_ranking'], 'Hard', 'Top quartile by activity, excluding the signup event',
    'Count each user\'s events other than "signup". Among users with at least one such event, return the top quartile by count (highest first, ties by user id). Return user id and events.', ['user_id', 'events'], true,
    `WITH e AS (SELECT user_id, COUNT(*) AS events FROM events WHERE event_name <> 'signup' GROUP BY user_id), q AS (SELECT user_id, events, NTILE(4) OVER (ORDER BY events DESC, user_id) AS qt FROM e) SELECT user_id, events FROM q WHERE qt = 1 ORDER BY events DESC, user_id;`,
    ['A very active user', 'The quartile moves with the data.', `INSERT INTO users VALUES (13,'2026-03-25','IN','organic'); INSERT INTO events SELECT 100+g, 13, 'login', TIMESTAMP '2026-03-26 10:00' + g * INTERVAL '1 minute', '{}' FROM generate_series(1,12) g;`],
    ['Which events count?', 'Everyone in the population is ranked, then split.', 'NTILE(4) OVER (ORDER BY events DESC, user_id) = 1'],
    'Define the metric precisely (exclude the signup event) before bucketing users.',
    `WITH e AS (SELECT user_id, COUNT(*) AS events FROM events GROUP BY user_id), q AS (SELECT user_id, events, NTILE(4) OVER (ORDER BY events DESC, user_id) AS qt FROM e) SELECT user_id, events FROM q WHERE qt = 1 ORDER BY events DESC, user_id;`, { patterns: ['segmentation'] }),
  Q('P756', 'Driver tiers', 'rides', ['an_segment', 'j_left'], 'Hard', 'Rule precedence in CASE',
    'Tier every driver: "gold" if they completed 4+ trips AND their average rider rating is at least 4.5; otherwise "silver" if they completed 3+ trips; otherwise "bronze" (including drivers with no trips). Rider ratings are the ratings where rated_by = \'rider\'. Return driver id, name, completed trips and tier; sorted by driver id.', ['driver_id', 'name', 'trips', 'tier'], true,
    `WITH st AS (SELECT d.driver_id, d.name, COUNT(t.trip_id) AS trips, AVG(r.stars) AS avg_stars FROM drivers d LEFT JOIN trips t ON t.driver_id = d.driver_id AND t.status = 'completed' LEFT JOIN ratings r ON r.trip_id = t.trip_id AND r.rated_by = 'rider' GROUP BY d.driver_id, d.name)
SELECT driver_id, name, trips, CASE WHEN trips >= 4 AND avg_stars >= 4.5 THEN 'gold' WHEN trips >= 3 THEN 'silver' ELSE 'bronze' END AS tier FROM st ORDER BY driver_id;`,
    ['A driver with no rated trips', 'NULL ratings cannot make gold.', `INSERT INTO drivers VALUES (17,'Nikhil','Mumbai','2026-02-12','bike');`],
    ['Check the strictest tier first.', 'CASE stops at the first match.', 'WHEN trips >= 4 AND avg_stars >= 4.5 THEN \'gold\' … before silver'],
    'Gold drivers also satisfy the silver rule, so silver must be tested after gold.',
    `WITH st AS (SELECT d.driver_id, d.name, COUNT(t.trip_id) AS trips, AVG(r.stars) AS avg_stars FROM drivers d LEFT JOIN trips t ON t.driver_id = d.driver_id AND t.status = 'completed' LEFT JOIN ratings r ON r.trip_id = t.trip_id AND r.rated_by = 'rider' GROUP BY d.driver_id, d.name) SELECT driver_id, name, trips, CASE WHEN trips >= 3 THEN 'silver' WHEN trips >= 4 AND avg_stars >= 4.5 THEN 'gold' ELSE 'bronze' END AS tier FROM st ORDER BY driver_id;`, { patterns: ['segmentation'] }),

  // ── Anomalies & fraud signals ──
  Q('P760', 'Unusually large debits', 'bank', ['an_anomaly'], 'Hard', 'Z-score within each account',
    'For each account, compute the mean and sample standard deviation of its debit sizes (absolute values of negative amounts). Flag debits more than 1.4 standard deviations above the account\'s mean. Return txn id, account id and the z-score (2 decimals); sorted by txn id.', ['txn_id', 'account_id', 'z'], true,
    `WITH t AS (SELECT txn_id, account_id, ABS(amount) AS amt, AVG(ABS(amount)) OVER (PARTITION BY account_id) AS mu, STDDEV_SAMP(ABS(amount)) OVER (PARTITION BY account_id) AS sd FROM transactions WHERE amount < 0)
SELECT txn_id, account_id, ROUND(((amt - mu) / sd)::numeric, 2) AS z FROM t WHERE sd > 0 AND (amt - mu) / sd > 1.4 ORDER BY txn_id;`,
    ['A tiny account with one debit', 'No spread means no z-score.', `INSERT INTO transactions VALUES (19,'A4','2026-03-01 10:00',-100,'card','Cafe');`],
    ['Each account is judged against itself.', 'Window mean and stddev per account.', 'AVG(…) OVER (PARTITION BY account_id), STDDEV_SAMP(…) OVER (PARTITION BY account_id)'],
    'Pooling all accounts together would flag normal rent-sized debits on large accounts.',
    `WITH t AS (SELECT txn_id, account_id, ABS(amount) AS amt, AVG(ABS(amount)) OVER () AS mu, STDDEV_SAMP(ABS(amount)) OVER () AS sd FROM transactions WHERE amount < 0) SELECT txn_id, account_id, ROUND(((amt - mu) / sd)::numeric, 2) AS z FROM t WHERE sd > 0 AND (amt - mu) / sd > 1.4 ORDER BY txn_id;`, { patterns: ['baseline'] }),
  Q('P761', 'Rapid-fire transactions', 'bank', ['an_anomaly', 'w_frames'], 'Hard', 'Velocity check with a time-range window',
    'Flag transactions where the same account had 3 or more transactions within the 10 minutes up to and including it (the transaction itself counts). Return txn id, account id and the count; sorted by txn id.', ['txn_id', 'account_id', 'txns_10m'], true,
    `SELECT txn_id, account_id, n AS txns_10m FROM (SELECT txn_id, account_id, COUNT(*) OVER (PARTITION BY account_id ORDER BY txn_time RANGE BETWEEN INTERVAL '10 minutes' PRECEDING AND CURRENT ROW) AS n FROM transactions) t WHERE n >= 3 ORDER BY txn_id;`,
    ['A fourth quick transaction', 'The count keeps growing inside the window.', `INSERT INTO transactions VALUES (19,'A2','2026-01-04 00:08',-9000,'upi','Vendor');`],
    ['Time, not row count.', 'RANGE with an interval.', "COUNT(*) OVER (PARTITION BY account_id ORDER BY txn_time RANGE BETWEEN INTERVAL '10 minutes' PRECEDING AND CURRENT ROW)"],
    'Counting the previous 2 rows ignores how far apart they are; velocity rules are time windows.',
    `SELECT txn_id, account_id, n AS txns_10m FROM (SELECT txn_id, account_id, COUNT(*) OVER (PARTITION BY account_id ORDER BY txn_time ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS n FROM transactions) t WHERE n >= 3 ORDER BY txn_id;`, { patterns: ['baseline'] }),
  Q('P762', 'Debits far above the norm', 'bank', ['an_anomaly', 'x_percentile'], 'Hard', 'Compare with the account\'s median debit',
    'Return debits larger than 5 times the median debit of the same account (more than, not equal to). Return txn id, account id and the debit size; sorted by txn id.', ['txn_id', 'account_id', 'amount'], true,
    `WITH d AS (SELECT txn_id, account_id, -amount AS amt FROM transactions WHERE amount < 0), m AS (SELECT account_id, PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY amt) AS med FROM d GROUP BY account_id)
SELECT d.txn_id, d.account_id, d.amt AS amount FROM d JOIN m ON m.account_id = d.account_id WHERE d.amt > 5 * m.med ORDER BY d.txn_id;`,
    ['Exactly five times the median', 'Strictly more than 5×.', `INSERT INTO transactions VALUES (19,'A3','2026-01-25 10:00',-4000,'card','Cafe');`],
    ['A robust baseline resists the outlier itself.', 'The median, per account.', 'PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY amt) … amt > 5 * med'],
    'The mean is inflated by the very outliers you are hunting; a median baseline is more stable.',
    `WITH d AS (SELECT txn_id, account_id, -amount AS amt FROM transactions WHERE amount < 0), m AS (SELECT account_id, AVG(amt) AS med FROM d GROUP BY account_id) SELECT d.txn_id, d.account_id, d.amt AS amount FROM d JOIN m ON m.account_id = d.account_id WHERE d.amt > 5 * m.med ORDER BY d.txn_id;`, { patterns: ['baseline', 'percentiles'] }),
  Q('P763', 'Retry storms', 'shop', ['an_anomaly'], 'Medium', 'Orders with repeated failed payments before success',
    'Which orders had at least 2 failed payment attempts and eventually a successful one? Return order id and the number of failed attempts, sorted by order id.', ['order_id', 'failed_attempts'], true,
    `SELECT order_id, COUNT(*) FILTER (WHERE status = 'failed') AS failed_attempts FROM payments GROUP BY order_id HAVING COUNT(*) FILTER (WHERE status = 'failed') >= 2 AND COUNT(*) FILTER (WHERE status = 'success') >= 1 ORDER BY order_id;`,
    ['Failures with no success', 'No eventual success means not this pattern.', `INSERT INTO payments VALUES (18,1010,'upi',100,'2026-02-28 10:00','failed'),(19,1010,'upi',100,'2026-02-28 10:05','failed');`],
    ['Count failures and successes separately.', 'Both conditions in HAVING.', "COUNT(*) FILTER (WHERE status = 'failed') >= 2 AND COUNT(*) FILTER (WHERE status = 'success') >= 1"],
    'COUNT(*) alone counts successful rows as attempts too.',
    `SELECT order_id, COUNT(*) AS failed_attempts FROM payments GROUP BY order_id HAVING COUNT(*) >= 2 ORDER BY order_id;`),
  Q('P764', 'Billed versus paid', 'shop', ['an_anomaly', 'j_fanout'], 'Hard', 'Reconcile two child tables at order grain',
    'Find orders where the total of SUCCESSFUL payments differs from the billed amount (quantity × charged price). Return order id, billed, paid, difference (paid − billed) and whether a coupon was used (true/false); sorted by order id.', ['order_id', 'billed', 'paid', 'diff', 'coupon_used'], true,
    `WITH b AS (SELECT order_id, SUM(quantity * unit_price) AS billed FROM order_items GROUP BY order_id), p AS (SELECT order_id, SUM(amount) AS paid FROM payments WHERE status = 'success' GROUP BY order_id)
SELECT o.order_id, b.billed, p.paid, p.paid - b.billed AS diff, (o.coupon_code IS NOT NULL) AS coupon_used FROM orders o JOIN b ON b.order_id = o.order_id JOIN p ON p.order_id = o.order_id WHERE p.paid <> b.billed ORDER BY o.order_id;`,
    ['Underpaid order without a coupon', 'Unexplained differences must appear with coupon_used = false.', `UPDATE payments SET amount = 2000 WHERE payment_id = 1;`],
    ['Aggregate each child to order grain.', 'Failed attempts are not money received.', 'SUM(amount) WHERE status = \'success\' per order'],
    'Reconciliation compares like with like: pre-aggregate both sides, and exclude failed attempts.',
    `WITH b AS (SELECT order_id, SUM(quantity * unit_price) AS billed FROM order_items GROUP BY order_id), p AS (SELECT order_id, SUM(amount) AS paid FROM payments GROUP BY order_id) SELECT o.order_id, b.billed, p.paid, p.paid - b.billed AS diff, (o.coupon_code IS NOT NULL) AS coupon_used FROM orders o JOIN b ON b.order_id = o.order_id JOIN p ON p.order_id = o.order_id WHERE p.paid <> b.billed ORDER BY o.order_id;`, { patterns: ['fanout_guard'] }),
  Q('P765', 'Bad cancellation days', 'rides', ['an_anomaly'], 'Medium', 'Daily rate versus the overall rate',
    'A day is a bad day when its cancellation rate (trips not completed ÷ trips requested) is above the overall rate across all days. Return day, trips, cancelled and rate percent (1 decimal), sorted by day.', ['day', 'trips', 'cancelled', 'rate_pct'], true,
    `WITH d AS (SELECT requested_at::date AS day, COUNT(*) AS trips, COUNT(*) FILTER (WHERE status <> 'completed') AS cancelled FROM trips GROUP BY 1)
SELECT day, trips, cancelled, ROUND(100.0 * cancelled / trips, 1) AS rate_pct FROM d WHERE cancelled::numeric / trips > (SELECT COUNT(*) FILTER (WHERE status <> 'completed')::numeric / COUNT(*) FROM trips) ORDER BY day;`,
    ['A day exactly at the overall rate', 'Strictly above only.', `INSERT INTO trips VALUES (521,7,16,'Mumbai','2026-02-09 09:00','completed',100,3.0),(522,7,16,'Mumbai','2026-02-09 10:00','completed',100,3.0);`],
    ['Compare rates, not counts.', 'Compute the overall rate in a subquery.', 'cancelled / trips > (overall cancelled / overall trips)'],
    'A hard-coded threshold goes stale; derive the baseline from the data.',
    `WITH d AS (SELECT requested_at::date AS day, COUNT(*) AS trips, COUNT(*) FILTER (WHERE status <> 'completed') AS cancelled FROM trips GROUP BY 1) SELECT day, trips, cancelled, ROUND(100.0 * cancelled / trips, 1) AS rate_pct FROM d WHERE cancelled::numeric / trips > 0.3 ORDER BY day;`, { patterns: ['baseline'] }),

  // ── Attribution & conversion ──
  Q('P770', 'Last-click attribution', 'ads', ['an_conversion'], 'Very Hard', 'Attribute purchases to the last click in a window',
    `Attribute every purchase's revenue to a campaign. ${WIN} Duplicate click rows must not matter. Return campaign name ("direct" for none), purchases and revenue; biggest revenue first, ties by name.`, ['campaign', 'purchases', 'revenue'], true,
    `${ATTR} SELECT COALESCE(cp.name, 'direct') AS campaign, COUNT(*) AS purchases, SUM(a.revenue) AS revenue FROM a LEFT JOIN campaigns cp ON cp.campaign_id = a.campaign_id GROUP BY 1 ORDER BY revenue DESC, campaign;`,
    ['A click eight days earlier', 'Clicks older than the window do not count.', `INSERT INTO ad_events VALUES (22,8,2,'click','2026-03-03 09:00',NULL);`],
    ['For each purchase find the latest earlier click inside 7 days.', 'LEFT JOIN LATERAL … LIMIT 1 keeps direct purchases.', 'ORDER BY click_time DESC LIMIT 1 with a >= purchase − 7 days filter'],
    'Without the window, an old click would claim a purchase two weeks later.',
    `WITH p AS (SELECT event_id, user_id, event_time, revenue FROM ad_events WHERE event_type = 'purchase'), c AS (SELECT DISTINCT user_id, campaign_id, event_time FROM ad_events WHERE event_type = 'click'), a AS (SELECT p.event_id, p.revenue, l.campaign_id FROM p LEFT JOIN LATERAL (SELECT c.campaign_id FROM c WHERE c.user_id = p.user_id AND c.event_time <= p.event_time ORDER BY c.event_time DESC, c.campaign_id LIMIT 1) l ON true) SELECT COALESCE(cp.name, 'direct') AS campaign, COUNT(*) AS purchases, SUM(a.revenue) AS revenue FROM a LEFT JOIN campaigns cp ON cp.campaign_id = a.campaign_id GROUP BY 1 ORDER BY revenue DESC, campaign;`, { patterns: ['funnel'] }),
  Q('P771', 'First-click attribution', 'ads', ['an_conversion'], 'Very Hard', 'Same journeys, different credit rule',
    'Attribute every purchase to the FIRST click inside the 7 days up to and including the purchase (earliest click in that window; ties by campaign id); with no click it is "direct". Duplicate click rows must not matter. Return campaign name, purchases and revenue; biggest revenue first, ties by name.', ['campaign', 'purchases', 'revenue'], true,
    `WITH p AS (SELECT event_id, user_id, event_time, revenue FROM ad_events WHERE event_type = 'purchase'), c AS (SELECT DISTINCT user_id, campaign_id, event_time FROM ad_events WHERE event_type = 'click'),
a AS (SELECT p.event_id, p.revenue, l.campaign_id FROM p LEFT JOIN LATERAL (SELECT c.campaign_id FROM c WHERE c.user_id = p.user_id AND c.event_time <= p.event_time AND c.event_time >= p.event_time - INTERVAL '7 days' ORDER BY c.event_time, c.campaign_id LIMIT 1) l ON true)
SELECT COALESCE(cp.name, 'direct') AS campaign, COUNT(*) AS purchases, SUM(a.revenue) AS revenue FROM a LEFT JOIN campaigns cp ON cp.campaign_id = a.campaign_id GROUP BY 1 ORDER BY revenue DESC, campaign;`,
    ['A click on a different campaign earlier', 'The first click wins.', `INSERT INTO ad_events VALUES (22,8,4,'click','2026-03-10 09:00',NULL);`],
    ['Same journey, opposite ordering.', 'Earliest click inside the window.', 'ORDER BY c.event_time (ascending) LIMIT 1'],
    'Attribution models only differ in which touch gets credit; the window logic stays the same.',
    `WITH p AS (SELECT event_id, user_id, event_time, revenue FROM ad_events WHERE event_type = 'purchase'), c AS (SELECT DISTINCT user_id, campaign_id, event_time FROM ad_events WHERE event_type = 'click'), a AS (SELECT p.event_id, p.revenue, l.campaign_id FROM p LEFT JOIN LATERAL (SELECT c.campaign_id FROM c WHERE c.user_id = p.user_id AND c.event_time <= p.event_time AND c.event_time >= p.event_time - INTERVAL '7 days' ORDER BY c.event_time DESC, c.campaign_id LIMIT 1) l ON true) SELECT COALESCE(cp.name, 'direct') AS campaign, COUNT(*) AS purchases, SUM(a.revenue) AS revenue FROM a LEFT JOIN campaigns cp ON cp.campaign_id = a.campaign_id GROUP BY 1 ORDER BY revenue DESC, campaign;`, { patterns: ['funnel'] }),
  Q('P772', 'Click-to-purchase rate', 'ads', ['an_conversion'], 'Hard', 'Conversion with a forward window per user and campaign',
    'For each campaign: users who clicked, users who purchased within 7 days (inclusive) AFTER one of their clicks on that campaign, and the percentage (1 decimal). Count users, not clicks. Return campaign name, clickers, converters, pct; sorted by name.', ['campaign', 'clickers', 'converters', 'pct'], true,
    `WITH uc AS (SELECT e.user_id, e.campaign_id, BOOL_OR(EXISTS (SELECT 1 FROM ad_events p WHERE p.user_id = e.user_id AND p.event_type = 'purchase' AND p.event_time >= e.event_time AND p.event_time <= e.event_time + INTERVAL '7 days')) AS conv FROM ad_events e WHERE e.event_type = 'click' GROUP BY e.user_id, e.campaign_id)
SELECT cp.name AS campaign, COUNT(*) AS clickers, COUNT(*) FILTER (WHERE uc.conv) AS converters, ROUND(100.0 * COUNT(*) FILTER (WHERE uc.conv) / COUNT(*), 1) AS pct FROM uc JOIN campaigns cp ON cp.campaign_id = uc.campaign_id GROUP BY cp.name ORDER BY cp.name;`,
    ['Purchase before the click', 'Only purchases after a click count.', `INSERT INTO ad_events VALUES (22,7,3,'purchase','2026-03-01 10:00',10);`],
    ['One row per user and campaign first.', 'Purchase after the click, within 7 days.', 'p.event_time >= click AND p.event_time <= click + INTERVAL \'7 days\''],
    'Duplicate clicks and repeat purchases must not inflate users; the window is forward-looking and inclusive.',
    `WITH uc AS (SELECT e.user_id, e.campaign_id, BOOL_OR(EXISTS (SELECT 1 FROM ad_events p WHERE p.user_id = e.user_id AND p.event_type = 'purchase' AND p.event_time >= e.event_time AND p.event_time < e.event_time + INTERVAL '7 days')) AS conv FROM ad_events e WHERE e.event_type = 'click' GROUP BY e.user_id, e.campaign_id) SELECT cp.name AS campaign, COUNT(*) AS clickers, COUNT(*) FILTER (WHERE uc.conv) AS converters, ROUND(100.0 * COUNT(*) FILTER (WHERE uc.conv) / COUNT(*), 1) AS pct FROM uc JOIN campaigns cp ON cp.campaign_id = uc.campaign_id GROUP BY cp.name ORDER BY cp.name;`, { patterns: ['funnel'] }),
  Q('P773', 'Return on ad spend', 'ads', ['an_conversion', 'j_left'], 'Very Hard', 'Spend vs last-click revenue, every campaign listed',
    `For every campaign: its spend, the revenue attributed to it by last-click attribution and ROAS = revenue ÷ spend (2 decimals). ${WIN} Campaigns with no attributed revenue show 0. Return campaign name, spend, revenue, roas; sorted by campaign id.`, ['campaign', 'spend', 'revenue', 'roas'], true,
    `${ATTR} SELECT cp.name AS campaign, cp.spend, COALESCE(SUM(a.revenue), 0) AS revenue, ROUND(COALESCE(SUM(a.revenue), 0) / cp.spend, 2) AS roas FROM campaigns cp LEFT JOIN a ON a.campaign_id = cp.campaign_id GROUP BY cp.campaign_id, cp.name, cp.spend ORDER BY cp.campaign_id;`,
    ['A campaign with no clicks', 'It still appears with 0 revenue.', `INSERT INTO campaigns VALUES (5,'Podcast','audio',100);`],
    ['Attribute first, then roll up.', 'Start from campaigns so empty ones stay.', 'campaigns LEFT JOIN attributed purchases'],
    'Revenue of every purchase by anyone who clicked would count the same purchase for several campaigns.',
    `SELECT cp.name AS campaign, cp.spend, COALESCE(SUM(p.revenue), 0) AS revenue, ROUND(COALESCE(SUM(p.revenue), 0) / cp.spend, 2) AS roas FROM campaigns cp LEFT JOIN (SELECT DISTINCT campaign_id, user_id FROM ad_events WHERE event_type = 'click') k ON k.campaign_id = cp.campaign_id LEFT JOIN ad_events p ON p.user_id = k.user_id AND p.event_type = 'purchase' GROUP BY cp.campaign_id, cp.name, cp.spend ORDER BY cp.campaign_id;`, { patterns: ['fanout_guard'] }),
  Q('P774', 'Hours from click to purchase', 'ads', ['an_conversion'], 'Very Hard', 'Time to convert for attributed purchases',
    `For purchases attributed to a campaign (not direct) by last click, the average hours between that click and the purchase, per campaign (1 decimal). ${WIN} Return campaign name and avg_hours; sorted by name.`, ['campaign', 'avg_hours'], true,
    `${ATTR} SELECT cp.name AS campaign, ROUND(AVG(EXTRACT(EPOCH FROM a.pt - a.ct) / 3600)::numeric, 1) AS avg_hours FROM a JOIN campaigns cp ON cp.campaign_id = a.campaign_id GROUP BY cp.name ORDER BY cp.name;`,
    ['A slower conversion', 'Averages move with the data.', `INSERT INTO ad_events VALUES (22,8,1,'click','2026-03-08 09:00',NULL);`],
    ['Keep the click time of the attributed click.', 'Convert the interval to hours.', 'EXTRACT(EPOCH FROM purchase_time − click_time) / 3600'],
    'Time-to-convert must be measured from the attributed click, not from the first touch.',
    `WITH p AS (SELECT event_id, user_id, event_time AS pt FROM ad_events WHERE event_type = 'purchase'), c AS (SELECT DISTINCT user_id, campaign_id, event_time AS ct FROM ad_events WHERE event_type = 'click'), a AS (SELECT p.pt, l.campaign_id, l.ct FROM p JOIN LATERAL (SELECT c.campaign_id, c.ct FROM c WHERE c.user_id = p.user_id AND c.ct <= p.pt AND c.ct >= p.pt - INTERVAL '7 days' ORDER BY c.ct, c.campaign_id LIMIT 1) l ON true) SELECT cp.name AS campaign, ROUND(AVG(EXTRACT(EPOCH FROM a.pt - a.ct) / 3600)::numeric, 1) AS avg_hours FROM a JOIN campaigns cp ON cp.campaign_id = a.campaign_id GROUP BY cp.name ORDER BY cp.name;`, { patterns: ['funnel'] }),
  Q('P775', 'Assisted conversions', 'ads', ['an_conversion'], 'Very Hard', 'Touches that helped but did not get the credit',
    `For each purchase, the campaigns clicked within the 7-day window before it (up to and including the purchase) other than the last-click campaign are "assists". Count assists per campaign. Return campaign name and assists for campaigns with at least one; sorted by name.`, ['campaign', 'assists'], true,
    `WITH p AS (SELECT event_id, user_id, event_time FROM ad_events WHERE event_type = 'purchase'), c AS (SELECT DISTINCT user_id, campaign_id, event_time FROM ad_events WHERE event_type = 'click'),
t AS (SELECT DISTINCT p.event_id, c.campaign_id, c.event_time FROM p JOIN c ON c.user_id = p.user_id AND c.event_time <= p.event_time AND c.event_time >= p.event_time - INTERVAL '7 days'),
lc AS (SELECT DISTINCT ON (event_id) event_id, campaign_id FROM t ORDER BY event_id, event_time DESC, campaign_id)
SELECT cp.name AS campaign, COUNT(DISTINCT t.event_id) AS assists FROM t JOIN lc ON lc.event_id = t.event_id AND lc.campaign_id <> t.campaign_id JOIN campaigns cp ON cp.campaign_id = t.campaign_id GROUP BY cp.name ORDER BY cp.name;`,
    ['A third touch', 'Every non-last campaign in the window assists.', `INSERT INTO ad_events VALUES (22,3,4,'click','2026-03-03 20:00',NULL);`],
    ['Find the last click first.', 'Assists are all the other campaigns in the window.', 'campaign_id <> last-click campaign for the same purchase'],
    'Last-click credits one campaign; assists reveal the others on the path.',
    `WITH p AS (SELECT event_id, user_id, event_time FROM ad_events WHERE event_type = 'purchase'), c AS (SELECT DISTINCT user_id, campaign_id, event_time FROM ad_events WHERE event_type = 'click'), t AS (SELECT DISTINCT p.event_id, c.campaign_id FROM p JOIN c ON c.user_id = p.user_id AND c.event_time <= p.event_time AND c.event_time >= p.event_time - INTERVAL '7 days') SELECT cp.name AS campaign, COUNT(*) AS assists FROM t JOIN campaigns cp ON cp.campaign_id = t.campaign_id GROUP BY cp.name ORDER BY cp.name;`, { patterns: ['funnel'] }),
  Q('P776', 'Coupon orders', 'shop', ['an_conversion'], 'Medium', 'Compare two segments at order grain',
    'Compare completed orders with and without a coupon: for each group (used_coupon true/false) the number of orders and the average ORDER value (2 decimals). Return used_coupon, orders, avg_value; sorted with false first.', ['used_coupon', 'orders', 'avg_value'], true,
    `WITH ov AS (${OVD}) SELECT (coupon_code IS NOT NULL) AS used_coupon, COUNT(*) AS orders, ROUND(AVG(value), 2) AS avg_value FROM ov GROUP BY 1 ORDER BY 1;`,
    ['A large coupon order', 'Averages move with orders.', `INSERT INTO orders VALUES (1018,9,'2026-04-12','completed','NEW10'); INSERT INTO order_items VALUES (1018,105,3,2999);`],
    ['Order value first.', 'Then average per group.', 'AVG over order totals, not line items'],
    'Averaging line items gives the average line, not the average order.',
    `SELECT (o.coupon_code IS NOT NULL) AS used_coupon, COUNT(DISTINCT o.order_id) AS orders, ROUND(AVG(oi.quantity * oi.unit_price), 2) AS avg_value FROM orders o JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' GROUP BY 1 ORDER BY 1;`, { patterns: ['fanout_guard'] }),
  Q('P777', 'Thirty-day upgrade rate', 'saas', ['an_conversion'], 'Very Hard', 'Conversion window with censoring',
    'Measure the share of users who upgraded within 30 days of their signup date. Data is observed through 2026-04-30, so only users whose full 30-day window has passed (signup date on or before 2026-04-01) are eligible. Return one row: eligible users, converted users and the percentage (1 decimal).', ['eligible', 'converted', 'pct'], false,
    `WITH e AS (SELECT user_id, signup_date FROM users WHERE signup_date <= DATE '2026-04-30' - 30), c AS (SELECT DISTINCT e.user_id FROM e JOIN events x ON x.user_id = e.user_id AND x.event_name = 'upgrade' AND x.event_time::date <= e.signup_date + 30)
SELECT COUNT(*) AS eligible, COUNT(c.user_id) AS converted, ROUND(100.0 * COUNT(c.user_id) / COUNT(*), 1) AS pct FROM e LEFT JOIN c ON c.user_id = e.user_id;`,
    ['Recent signup and a late upgrade', 'Users with an incomplete window are excluded; a day-45 upgrade does not count.', `INSERT INTO users VALUES (13,'2026-04-20','IN','organic'),(14,'2026-03-01','IN','organic'); INSERT INTO events VALUES (46,14,'signup','2026-03-01 09:00','{}'),(47,14,'upgrade','2026-04-15 09:00','{"plan":"pro"}');`, 'Business logic'],
    ['Who has had a full 30 days?', 'Count only upgrades within the window.', 'signup_date <= 2026-04-30 − 30 and upgrade date <= signup_date + 30'],
    'Including users whose window is still open understates conversion (they might yet upgrade); ignoring the window overstates it.',
    `SELECT COUNT(*) AS eligible, COUNT(*) FILTER (WHERE EXISTS (SELECT 1 FROM events e WHERE e.user_id = u.user_id AND e.event_name = 'upgrade')) AS converted, ROUND(100.0 * COUNT(*) FILTER (WHERE EXISTS (SELECT 1 FROM events e WHERE e.user_id = u.user_id AND e.event_name = 'upgrade')) / COUNT(*), 1) AS pct FROM users u;`, { patterns: ['funnel'] }),
];
