// Level 6 — advanced SQL: dates (P600–609), dedup (P610–615), percentiles (P616–621), JSON (P622–626), LATERAL (P627–632), pivot (P633–638).
import { Q } from './q.js';
const TRIP = `INSERT INTO trips VALUES (521,7,16,'Mumbai','2026-02-08 09:00','completed',100,3.0);`;
const OV = `SELECT o.order_id, SUM(oi.quantity * oi.unit_price) AS value FROM orders o JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' GROUP BY o.order_id`;

export const PROBLEMS_I = [
  // ── Dates ──
  Q('P600', 'Weekly orders', 'shop', ['x_dates'], 'Easy', 'date_trunc to week',
    'How many completed orders were placed in each calendar week? Show the Monday that starts the week and the count, sorted by week.', ['week_start', 'orders'], true,
    `SELECT date_trunc('week', order_date)::date AS week_start, COUNT(*) AS orders FROM orders WHERE status = 'completed' GROUP BY 1 ORDER BY 1;`,
    ['A Sunday order', 'Weeks start on Monday, so Sunday belongs to the previous week.', `INSERT INTO orders VALUES (1018,10,'2026-04-12','completed',NULL);`],
    ['Bucket dates to the start of their week.', 'date_trunc handles it.', "date_trunc('week', order_date)::date"],
    'date_trunc maps every date in a period to the period start, giving a single group key.',
    `SELECT order_date AS week_start, COUNT(*) AS orders FROM orders WHERE status = 'completed' GROUP BY 1 ORDER BY 1;`),
  Q('P601', 'Days since signup', 'shop', ['x_dates'], 'Easy', 'Date arithmetic with a fixed reference date',
    'As of 30 April 2026, how many days ago did each customer sign up? Return customer id and days, sorted by id. (Use the fixed date, so the result never changes.)', ['customer_id', 'days_since_signup'], true,
    `SELECT customer_id, DATE '2026-04-30' - signup_date AS days_since_signup FROM customers ORDER BY customer_id;`,
    ['A new signup', 'The reference date is fixed.', `INSERT INTO customers VALUES (11,'Tara Sen','tara@mail.com','Pune','2026-04-30',NULL);`],
    ['Subtract two dates to get days.', 'Do not depend on today\'s date.', "DATE '2026-04-30' - signup_date"],
    'Analyses must be reproducible: use an explicit as-of date instead of CURRENT_DATE.',
    `SELECT customer_id, CURRENT_DATE - signup_date AS days_since_signup FROM customers ORDER BY customer_id;`),
  Q('P602', 'Trips by weekday', 'rides', ['x_dates'], 'Medium', 'Weekday names in calendar order',
    'Count trip requests (any status) per weekday, listed Monday to Sunday. Return the weekday name (e.g. Monday) and the count.', ['weekday', 'trips'], true,
    `SELECT to_char(requested_at, 'FMDay') AS weekday, COUNT(*) AS trips FROM trips GROUP BY 1, EXTRACT(isodow FROM requested_at) ORDER BY EXTRACT(isodow FROM requested_at);`,
    ['A Wednesday trip', 'Calendar order, not alphabetical.', `INSERT INTO trips VALUES (521,7,16,'Mumbai','2026-02-11 09:00','completed',100,3.0);`],
    ['Names sort alphabetically unless you tell SQL otherwise.', 'ISO day of week: Monday = 1.', "ORDER BY EXTRACT(isodow FROM requested_at)"],
    'Group by the label but sort by the numeric weekday.',
    `SELECT to_char(requested_at, 'FMDay') AS weekday, COUNT(*) AS trips FROM trips GROUP BY 1 ORDER BY 1;`),
  Q('P603', 'Last full month', 'shop', ['x_dates'], 'Medium', 'Month boundaries from an anchor date',
    'Today is 15 April 2026 (treat it as a fixed anchor). List all orders (any status) placed in the previous FULL calendar month. Return order id and date, sorted by id.', ['order_id', 'order_date'], true,
    `SELECT order_id, order_date FROM orders WHERE order_date >= date_trunc('month', DATE '2026-04-15' - INTERVAL '1 month') AND order_date < date_trunc('month', DATE '2026-04-15') ORDER BY order_id;`,
    ['Orders on March boundaries', 'First and last day of the month are included.', `INSERT INTO orders VALUES (1018,10,'2026-03-01','pending',NULL),(1019,10,'2026-04-01','pending',NULL);`],
    ['Start of this month and start of last month.', 'Half-open interval: >= first day, < next first day.', "order_date >= date_trunc('month', anchor - INTERVAL '1 month') AND order_date < date_trunc('month', anchor)"],
    '"Last 30 days" and "last calendar month" are different windows; month questions need month boundaries.',
    `SELECT order_id, order_date FROM orders WHERE order_date > DATE '2026-04-15' - 30 AND order_date <= DATE '2026-04-15' ORDER BY order_id;`),
  Q('P604', 'Signups per month, gaps included', 'saas', ['x_dates', 'j_cross'], 'Hard', 'Date spine with generate_series',
    'Number of signups per month for January–April 2026, including months with none. Months as first-of-month dates, sorted.', ['month', 'signups'], true,
    `SELECT m::date AS month, COUNT(u.user_id) AS signups FROM generate_series(DATE '2026-01-01', DATE '2026-04-01', INTERVAL '1 month') m LEFT JOIN users u ON date_trunc('month', u.signup_date) = m GROUP BY m ORDER BY m;`,
    ['A late April signup', 'The empty month fills in when data arrives.', `INSERT INTO users VALUES (13,'2026-04-20','IN','organic');`],
    ['A month with no signups has no rows to count.', 'Generate the months, then LEFT JOIN.', 'generate_series(…, INTERVAL \'1 month\') LEFT JOIN users'],
    'A generated spine guarantees every period appears; COUNT(right.key) gives 0 for empty ones.',
    `SELECT date_trunc('month', signup_date)::date AS month, COUNT(*) AS signups FROM users GROUP BY 1 ORDER BY 1;`, { patterns: ['date_spine'] }),
  Q('P605', 'Hours to first successful payment', 'shop', ['x_dates'], 'Hard', 'Interval maths on timestamps',
    'For each order with a successful payment, how many hours passed between the start of the order date (00:00) and its FIRST successful payment (1 decimal)? Return order id and hours, sorted by order id.', ['order_id', 'hours_to_pay'], true,
    `SELECT p.order_id, ROUND(EXTRACT(EPOCH FROM MIN(p.paid_at) - o.order_date::timestamp) / 3600, 1) AS hours_to_pay FROM payments p JOIN orders o ON o.order_id = p.order_id WHERE p.status = 'success' GROUP BY p.order_id, o.order_date ORDER BY p.order_id;`,
    ['Second success later', 'Only the first success counts.', `INSERT INTO payments VALUES (18,1001,'card',100.00,'2026-01-09 10:00','success');`],
    ['Failed attempts are not payments.', 'Take the earliest successful one.', 'MIN(paid_at) with WHERE status = \'success\''],
    'EXTRACT(EPOCH FROM interval)/3600 converts an interval to hours.',
    `SELECT p.order_id, ROUND(EXTRACT(EPOCH FROM MIN(p.paid_at) - o.order_date::timestamp) / 3600, 1) AS hours_to_pay FROM payments p JOIN orders o ON o.order_id = p.order_id GROUP BY p.order_id, o.order_date HAVING BOOL_OR(p.status = 'success') ORDER BY p.order_id;`),
  Q('P606', 'After-hours transactions', 'bank', ['x_dates'], 'Medium', 'Time-of-day window that wraps midnight',
    'List transactions made after hours: from 22:00 up to (not including) 06:00. Return txn id and time, sorted by id.', ['txn_id', 'txn_time'], true,
    `SELECT txn_id, txn_time FROM transactions WHERE EXTRACT(hour FROM txn_time) >= 22 OR EXTRACT(hour FROM txn_time) < 6 ORDER BY txn_id;`,
    ['Transaction at exactly 06:00 and 22:00', 'Boundaries: 06:00 is out, 22:00 is in.', `INSERT INTO transactions VALUES (19,'A1','2026-02-10 06:00',-10,'card','Cafe'),(20,'A1','2026-02-10 22:00',-10,'card','Cafe');`],
    ['A window that crosses midnight cannot be one BETWEEN.', 'Use OR.', 'hour >= 22 OR hour < 6'],
    'BETWEEN 22 AND 6 is an empty range; wrap-around windows need OR.',
    `SELECT txn_id, txn_time FROM transactions WHERE EXTRACT(hour FROM txn_time) BETWEEN 22 AND 6 ORDER BY txn_id;`),
  Q('P607', 'Completed years of service', 'hr', ['x_dates'], 'Medium', 'age() vs year subtraction',
    'As of 30 April 2026, how many COMPLETE years has each employee worked? Return emp id, name, years; sorted by emp id.', ['emp_id', 'name', 'tenure_years'], true,
    `SELECT emp_id, name, EXTRACT(year FROM age(DATE '2026-04-30', hire_date))::int AS tenure_years FROM employees ORDER BY emp_id;`,
    ['Hired just after the anniversary', 'A year is complete only on the anniversary.', `INSERT INTO employees VALUES (17,'Advik',1,1,'Engineer',100000,'2021-05-01');`],
    ['Subtracting year numbers is wrong for people hired later in the year.', 'age() works on full dates.', 'EXTRACT(year FROM age(date, hire_date))'],
    'Year(2026) − year(2021) counts calendar years, not completed ones.',
    `SELECT emp_id, name, (EXTRACT(year FROM DATE '2026-04-30') - EXTRACT(year FROM hire_date))::int AS tenure_years FROM employees ORDER BY emp_id;`),
  Q('P608', 'March orders', 'food', ['x_dates'], 'Medium', 'Month filter on timestamps',
    'List all orders placed in March 2026 (timestamps include the time of day). Return delivery id, sorted.', ['delivery_id'], true,
    `SELECT delivery_id FROM deliveries WHERE ordered_at >= '2026-03-01' AND ordered_at < '2026-04-01' ORDER BY delivery_id;`,
    ['Order on the evening of 31 March', 'The last day must be included in full.', `INSERT INTO deliveries VALUES (21,1,113,'2026-03-31 18:00','2026-03-31 18:40','delivered',300,25,NULL,3.0,4);`],
    ['Timestamps on the last day have a time part.', 'Use a half-open interval.', "ordered_at >= '2026-03-01' AND ordered_at < '2026-04-01'"],
    "BETWEEN '2026-03-01' AND '2026-03-31' means up to 31 March 00:00, dropping the rest of that day.",
    `SELECT delivery_id FROM deliveries WHERE ordered_at BETWEEN '2026-03-01' AND '2026-03-31' ORDER BY delivery_id;`),
  Q('P609', 'Month-end orders', 'shop', ['x_dates'], 'Medium', 'Last day of the month',
    'Which orders were placed on the last day of their month? Return order id and date, sorted by id.', ['order_id', 'order_date'], true,
    `SELECT order_id, order_date FROM orders WHERE order_date = (date_trunc('month', order_date) + INTERVAL '1 month - 1 day')::date ORDER BY order_id;`,
    ['Order on 28 February', 'Month lengths differ.', `INSERT INTO orders VALUES (1018,10,'2026-02-28','pending',NULL);`],
    ['Months have 28 to 31 days.', 'Compute the month\'s last day.', "date_trunc('month', d) + INTERVAL '1 month - 1 day'"],
    'Do not hard-code 30; derive the last day from the next month\'s start.',
    `SELECT order_id, order_date FROM orders WHERE EXTRACT(day FROM order_date) = 30 ORDER BY order_id;`),

  // ── Dedup ──
  Q('P610', 'Latest login per user', 'saas', ['x_dedup'], 'Medium', 'DISTINCT ON',
    'For each user who has logged in, when was their latest login? Return user id and time, sorted by user id.', ['user_id', 'event_time'], true,
    `SELECT DISTINCT ON (user_id) user_id, event_time FROM events WHERE event_name = 'login' ORDER BY user_id, event_time DESC;`,
    ['A newer login', 'Latest means newest.', `INSERT INTO events VALUES (46,1,'login','2026-04-20 08:00','{}');`],
    ['One row per user.', 'DISTINCT ON keeps the first row of each group in your ORDER BY.', 'DISTINCT ON (user_id) … ORDER BY user_id, event_time DESC'],
    'The ORDER BY after the DISTINCT ON key decides which row survives.',
    `SELECT DISTINCT ON (user_id) user_id, event_time FROM events WHERE event_name = 'login' ORDER BY user_id, event_time;`, { patterns: ['dedup'] }),
  Q('P611', 'Repeated card charges', 'bank', ['x_dedup', 'w_offset'], 'Hard', 'Time-window duplicates with LAG',
    'A charge is a duplicate when the same account, merchant and amount appeared less than or exactly 5 minutes earlier. Return the txn ids of the duplicate charges (not the originals), sorted.', ['txn_id'], true,
    `WITH x AS (SELECT txn_id, txn_time - LAG(txn_time) OVER (PARTITION BY account_id, merchant, amount ORDER BY txn_time, txn_id) AS gap FROM transactions) SELECT txn_id FROM x WHERE gap <= INTERVAL '5 minutes' ORDER BY txn_id;`,
    ['Exactly five minutes apart', 'The boundary is inclusive.', `INSERT INTO transactions VALUES (19,'A3','2026-01-25 10:00',-500,'card','Cafe'),(20,'A3','2026-01-25 10:05',-500,'card','Cafe');`],
    ['Same key, close in time.', 'Compare with the previous matching row.', 'LAG(txn_time) OVER (PARTITION BY account_id, merchant, amount ORDER BY txn_time)'],
    'Duplicates here are defined by time proximity, not by equal values alone.',
    `WITH x AS (SELECT txn_id, ROW_NUMBER() OVER (PARTITION BY account_id, merchant, amount ORDER BY txn_time, txn_id) AS rn FROM transactions) SELECT txn_id FROM x WHERE rn > 1 ORDER BY txn_id;`, { patterns: ['dedup'] }),
  Q('P612', 'How many extra copies', 'saas', ['x_dedup'], 'Medium', 'Counting surplus duplicate rows',
    'How many surplus rows are there in events — rows that repeat an earlier row with the same user, event name and time? Return one number.', ['extra_rows'], false,
    `SELECT COUNT(*) - COUNT(DISTINCT (user_id, event_name, event_time)) AS extra_rows FROM events;`,
    ['A triplicate', 'Three copies means two surplus rows.', `INSERT INTO events VALUES (46,1,'login','2026-03-02 08:00','{}'),(47,1,'login','2026-03-02 08:00','{}'),(48,1,'login','2026-03-02 08:00','{}');`],
    ['Total rows minus distinct rows.', 'A row of columns can be counted DISTINCT.', 'COUNT(*) - COUNT(DISTINCT (user_id, event_name, event_time))'],
    'Surplus = total − distinct. Counting every row in duplicate groups would include the originals.',
    `SELECT SUM(c) AS extra_rows FROM (SELECT COUNT(*) AS c FROM events GROUP BY user_id, event_name, event_time HAVING COUNT(*) > 1) t;`, { patterns: ['dedup'] }),
  Q('P613', 'Favourite driver', 'rides', ['x_dedup', 'w_ranking'], 'Hard', 'Most frequent value per group (mode)',
    'For each rider, which driver have they completed the most trips with (ties: lower driver id)? Return rider id, driver id and trips, sorted by rider.', ['rider_id', 'driver_id', 'trips'], true,
    `WITH c AS (SELECT rider_id, driver_id, COUNT(*) AS trips FROM trips WHERE status = 'completed' GROUP BY rider_id, driver_id), r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY rider_id ORDER BY trips DESC, driver_id) AS rn FROM c) SELECT rider_id, driver_id, trips FROM r WHERE rn = 1 ORDER BY rider_id;`,
    ['A tie between drivers', 'Ties go to the lower driver id.', `INSERT INTO trips VALUES (521,7,15,'Mumbai','2026-02-08 09:00','completed',100,3.0),(522,7,16,'Mumbai','2026-02-08 10:00','completed',100,3.0);`],
    ['Count per rider and driver first.', 'Then keep the top one per rider.', 'ROW_NUMBER() OVER (PARTITION BY rider_id ORDER BY trips DESC, driver_id)'],
    'MAX(driver_id) returns the largest id, not the most frequent one.',
    `SELECT rider_id, MAX(driver_id) AS driver_id, COUNT(*) AS trips FROM trips WHERE status = 'completed' GROUP BY rider_id ORDER BY rider_id;`, { patterns: ['top_n_per_group'] }),
  Q('P614', 'Best attempt per course', 'campus', ['x_dedup'], 'Medium', 'Keep the best of several attempts',
    'Students can retake courses. For each student and course they completed, return the best grade. Sorted by student id then course id.', ['student_id', 'course_id', 'best_grade'], true,
    `SELECT student_id, course_id, MAX(grade) AS best_grade FROM enrollments WHERE status = 'completed' GROUP BY student_id, course_id ORDER BY student_id, course_id;`,
    ['A worse retake', 'The best grade survives.', `INSERT INTO enrollments VALUES (1,'C101','2026S',5.0,'completed');`],
    ['One row per student-course.', 'Best means highest grade, not newest.', 'MAX(grade) GROUP BY student_id, course_id'],
    '"Latest attempt" and "best attempt" are different survivor rules; the question names the rule.',
    `SELECT DISTINCT ON (student_id, course_id) student_id, course_id, grade AS best_grade FROM enrollments WHERE status = 'completed' ORDER BY student_id, course_id, term DESC;`, { patterns: ['dedup'] }),
  Q('P615', 'First successful payment', 'shop', ['x_dedup'], 'Medium', 'Keep one payment per order',
    'Some orders have several successful payments. Return the payment id of the FIRST successful payment of each order (earliest time, ties by id), sorted.', ['payment_id'], true,
    `SELECT payment_id FROM (SELECT payment_id, ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY paid_at, payment_id) AS rn FROM payments WHERE status = 'success') t WHERE rn = 1 ORDER BY payment_id;`,
    ['Two successes on one order', 'Only the earliest survives.', `INSERT INTO payments VALUES (18,1001,'card',100.00,'2026-01-09 10:00','success');`],
    ['Number successful payments within each order.', 'Keep number 1.', 'ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY paid_at, payment_id)'],
    'Filter first (successes only), then number within each order.',
    `SELECT payment_id FROM payments WHERE status = 'success' ORDER BY payment_id;`, { patterns: ['dedup'] }),

  // ── Percentiles ──
  Q('P616', 'Median order value', 'food', ['x_percentile'], 'Easy', 'PERCENTILE_CONT(0.5)',
    'What is the median order value of delivered orders (2 decimals)?', ['median_value'], false,
    `SELECT ROUND((PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY order_value))::numeric, 2) AS median_value FROM deliveries WHERE status = 'delivered';`,
    ['A huge order', 'The median resists outliers.', `INSERT INTO deliveries VALUES (21,6,113,'2026-03-10 20:00','2026-03-10 20:50','delivered',50000,0,NULL,6.0,5);`],
    ['The middle value, not the mean.', 'Ordered-set aggregate.', 'PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY order_value)'],
    'The mean is dragged by outliers; the median is the 50th percentile.',
    `SELECT ROUND(AVG(order_value), 2) AS median_value FROM deliveries WHERE status = 'delivered';`),
  Q('P617', 'Median salary by department', 'hr', ['x_percentile'], 'Medium', 'Median per group, interpolated',
    'Median salary (2 decimals; average the two middle values when the count is even) for each department. Ignore employees without a department. Sort by dept id.', ['dept_id', 'median_salary'], true,
    `SELECT dept_id, ROUND((PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY salary))::numeric, 2) AS median_salary FROM employees WHERE dept_id IS NOT NULL GROUP BY dept_id ORDER BY dept_id;`,
    ['A new employee', 'Medians move with the data.', `INSERT INTO employees VALUES (17,'Advik',4,14,'Analyst',200000,'2026-04-01');`],
    ['An even count has no single middle row.', 'Use the continuous version.', 'PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY salary)'],
    'PERCENTILE_DISC returns an existing value; PERCENTILE_CONT interpolates between the two middle ones.',
    `SELECT dept_id, ROUND((PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY salary))::numeric, 2) AS median_salary FROM employees WHERE dept_id IS NOT NULL GROUP BY dept_id ORDER BY dept_id;`),
  Q('P618', '90th percentile fare', 'rides', ['x_percentile'], 'Medium', 'High percentile per group',
    'For each city, the 90th percentile fare of completed trips (2 decimals). Sort by city.', ['city', 'p90_fare'], true,
    `SELECT city, ROUND((PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY fare))::numeric, 2) AS p90_fare FROM trips WHERE status = 'completed' GROUP BY city ORDER BY city;`,
    ['One extreme fare', 'A percentile is less sensitive than MAX.', `INSERT INTO trips VALUES (521,1,11,'Bengaluru','2026-02-10 10:00','completed',9000,6.0);`],
    ['Not the maximum.', 'Ordered-set aggregate with 0.9.', 'PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY fare)'],
    'p90 is the value below which 90% of trips fall.',
    `SELECT city, ROUND(MAX(fare), 2) AS p90_fare FROM trips WHERE status = 'completed' GROUP BY city ORDER BY city;`),
  Q('P619', 'Delivery time p50 and p90', 'food', ['x_percentile'], 'Medium', 'Two percentiles in one row',
    'For delivered orders, the median and 90th-percentile delivery time in minutes (ordered → delivered), 1 decimal each, in one row.', ['p50_minutes', 'p90_minutes'], false,
    `SELECT ROUND((PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY m))::numeric, 1) AS p50_minutes, ROUND((PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY m))::numeric, 1) AS p90_minutes FROM (SELECT EXTRACT(EPOCH FROM delivered_at - ordered_at) / 60 AS m FROM deliveries WHERE status = 'delivered') t;`,
    ['A very slow delivery', 'The tail moves p90 more than p50.', `INSERT INTO deliveries VALUES (21,1,113,'2026-03-10 20:00','2026-03-10 23:00','delivered',300,25,NULL,3.0,1);`],
    ['Compute minutes first.', 'Then two ordered-set aggregates.', 'PERCENTILE_CONT(0.5) … , PERCENTILE_CONT(0.9) …'],
    'Interpolated percentiles give values between observations, which is usually what reports want.',
    `SELECT ROUND((PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY m))::numeric, 1) AS p50_minutes, ROUND((PERCENTILE_DISC(0.9) WITHIN GROUP (ORDER BY m))::numeric, 1) AS p90_minutes FROM (SELECT EXTRACT(EPOCH FROM delivered_at - ordered_at) / 60 AS m FROM deliveries WHERE status = 'delivered') t;`),
  Q('P620', 'Top-decile transactions', 'bank', ['x_percentile'], 'Hard', 'Filter by a percentile threshold on absolute size',
    'Which transactions are in the top 10% by SIZE (absolute amount; at or above the 90th percentile of absolute amounts)? Return txn id and size, sorted by txn id.', ['txn_id', 'size'], true,
    `SELECT txn_id, ABS(amount) AS size FROM transactions WHERE ABS(amount) >= (SELECT PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY ABS(amount)) FROM transactions) ORDER BY txn_id;`,
    ['One more big debit', 'Debits are large too.', `INSERT INTO transactions VALUES (19,'A4','2026-03-01 10:00',-80000,'transfer','Rent');`],
    ['Debits are negative.', 'Take sizes (ABS) before the percentile.', 'PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY ABS(amount))'],
    'The percentile of signed amounts ignores big debits; define the metric (size) first, then take its percentile.',
    `SELECT txn_id, ABS(amount) AS size FROM transactions WHERE amount >= (SELECT PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY amount) FROM transactions) ORDER BY txn_id;`),
  Q('P621', 'Median basket', 'shop', ['x_percentile'], 'Medium', 'Median of an aggregated metric',
    'The median completed order value (quantity × charged price), 2 decimals. One number.', ['median_order_value'], false,
    `WITH ov AS (${OV}) SELECT ROUND((PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY value))::numeric, 2) AS median_order_value FROM ov;`,
    ['A giant basket', 'Outliers do not move the median much.', `INSERT INTO orders VALUES (1018,10,'2026-04-12','completed',NULL); INSERT INTO order_items VALUES (1018,105,50,2999);`],
    ['Order value per order first.', 'Then the median of those values.', 'PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY value)'],
    'Compute the metric at the right grain (order) before taking its median.',
    `WITH ov AS (${OV}) SELECT ROUND(AVG(value), 2) AS median_order_value FROM ov;`),

  // ── JSON ──
  Q('P622', 'Projects without a template', 'saas', ['x_json'], 'Medium', 'Missing JSON keys and NULL documents',
    'Which create_project events have no "template" in their properties (key missing, empty object or no properties at all)? Return event id, sorted.', ['event_id'], true,
    `SELECT event_id FROM events WHERE event_name = 'create_project' AND properties->>'template' IS NULL ORDER BY event_id;`,
    ['A project with a template', 'Events with a template are excluded.', `INSERT INTO events VALUES (46,1,'create_project','2026-03-02 10:00','{"template":"blank"}');`],
    ['->> returns NULL when the key is missing.', 'It also returns NULL when the whole document is NULL.', "properties->>'template' IS NULL"],
    'Do not exclude NULL documents by testing properties IS NOT NULL — they also lack the key.',
    `SELECT event_id FROM events WHERE event_name = 'create_project' AND properties IS NOT NULL AND properties->>'template' IS NULL ORDER BY event_id;`),
  Q('P623', 'Upgrades by plan', 'saas', ['x_json'], 'Easy', 'Extract a JSON value and group by it',
    'How many upgrade events were there for each plan (taken from the event properties)? Return plan and count, sorted by plan.', ['plan', 'upgrades'], true,
    `SELECT properties->>'plan' AS plan, COUNT(*) AS upgrades FROM events WHERE event_name = 'upgrade' GROUP BY 1 ORDER BY 1;`,
    ['A new plan', 'New plan values appear as groups.', `INSERT INTO events VALUES (46,2,'upgrade','2026-03-02 10:00','{"plan":"enterprise"}');`],
    ['Which events carry a plan?', 'Filter to upgrades, then group on the extracted value.', "properties->>'plan'"],
    'Other event types have no plan key; without the filter they form a NULL group.',
    `SELECT properties->>'plan' AS plan, COUNT(*) AS upgrades FROM events GROUP BY 1 ORDER BY 1;`),
  Q('P624', 'Categories per customer', 'shop', ['x_json', 'a_distinct'], 'Medium', 'STRING_AGG with DISTINCT and ORDER',
    'For each customer with completed orders, the distinct product categories they bought as one alphabetical, comma-separated string (", "). Sort by customer id.', ['customer_id', 'categories'], true,
    `SELECT o.customer_id, STRING_AGG(DISTINCT p.category, ', ' ORDER BY p.category) AS categories FROM orders o JOIN order_items oi ON oi.order_id = o.order_id JOIN products p ON p.product_id = oi.product_id WHERE o.status = 'completed' GROUP BY o.customer_id ORDER BY o.customer_id;`,
    ['Same category twice', 'Each category appears once.', `INSERT INTO orders VALUES (1018,5,'2026-04-12','completed',NULL); INSERT INTO order_items VALUES (1018,106,1,899),(1018,107,1,349);`],
    ['Collapse rows into one string.', 'Duplicates and order matter.', "STRING_AGG(DISTINCT p.category, ', ' ORDER BY p.category)"],
    'Without DISTINCT a customer who bought two grocery items would list Grocery twice.',
    `SELECT o.customer_id, STRING_AGG(p.category, ', ' ORDER BY p.category) AS categories FROM orders o JOIN order_items oi ON oi.order_id = o.order_id JOIN products p ON p.product_id = oi.product_id WHERE o.status = 'completed' GROUP BY o.customer_id ORDER BY o.customer_id;`),
  Q('P625', 'Which property keys are used', 'saas', ['x_json'], 'Hard', 'Explode JSON keys',
    'Which property keys appear in the events table and in how many events does each appear? Return key and events, sorted by key.', ['key', 'events'], true,
    `SELECT k AS key, COUNT(*) AS events FROM events e CROSS JOIN LATERAL jsonb_object_keys(e.properties) k GROUP BY k ORDER BY k;`,
    ['A new key', 'Keys are discovered from the data.', `INSERT INTO events VALUES (46,2,'login','2026-03-02 10:00','{"browser":"safari"}');`],
    ['Turn each key of each document into a row.', 'A set-returning function can sit in a LATERAL join.', 'jsonb_object_keys(properties)'],
    'jsonb_object_keys explodes a document into one row per key; NULL or empty documents produce no rows.',
    `SELECT 'device' AS key, COUNT(*) AS events FROM events WHERE properties->>'device' IS NOT NULL;`),
  Q('P626', 'Latest known device', 'saas', ['x_json', 'x_dedup'], 'Hard', 'Latest non-missing value per user',
    'For each user, the device from their most recent event that actually has a device recorded. Return user id and device, sorted by user id.', ['user_id', 'latest_device'], true,
    `SELECT DISTINCT ON (user_id) user_id, properties->>'device' AS latest_device FROM events WHERE properties->>'device' IS NOT NULL ORDER BY user_id, event_time DESC, event_id DESC;`,
    ['Newest event has no device', 'Skip events without a device.', `INSERT INTO events VALUES (46,1,'login','2026-04-01 10:00','{}');`, 'NULL handling'],
    ['The very last event may have no device.', 'Filter first, then take the latest.', "WHERE properties->>'device' IS NOT NULL ORDER BY user_id, event_time DESC"],
    'Filter missing values before picking the latest row, otherwise the latest row can be the empty one.',
    `SELECT DISTINCT ON (user_id) user_id, properties->>'device' AS latest_device FROM events ORDER BY user_id, event_time DESC, event_id DESC;`, { patterns: ['dedup'] }),

  // ── LATERAL ──
  Q('P627', 'Last two orders per customer', 'shop', ['x_lateral'], 'Hard', 'LATERAL with ORDER BY … LIMIT',
    'For each customer, their two most recent completed orders. Return customer id, order id and date; sort by customer id, then newest first.', ['customer_id', 'order_id', 'order_date'], true,
    `SELECT c.customer_id, x.order_id, x.order_date FROM customers c CROSS JOIN LATERAL (SELECT o.order_id, o.order_date FROM orders o WHERE o.customer_id = c.customer_id AND o.status = 'completed' ORDER BY o.order_date DESC, o.order_id DESC LIMIT 2) x ORDER BY c.customer_id, x.order_date DESC, x.order_id DESC;`,
    ['A customer with three orders', 'Only the latest two remain.', `INSERT INTO orders VALUES (1018,4,'2026-04-12','completed',NULL);`],
    ['Per-customer LIMIT is the point.', 'A subquery that sees the outer row.', 'CROSS JOIN LATERAL (SELECT … WHERE o.customer_id = c.customer_id ORDER BY … LIMIT 2)'],
    'LATERAL lets the subquery refer to the outer row, so LIMIT applies per customer.',
    `SELECT c.customer_id, x.order_id, x.order_date FROM customers c CROSS JOIN LATERAL (SELECT o.order_id, o.order_date FROM orders o WHERE o.customer_id = c.customer_id AND o.status = 'completed' ORDER BY o.order_date, o.order_id LIMIT 2) x ORDER BY c.customer_id, x.order_date DESC, x.order_id DESC;`, { patterns: ['top_n_per_group'] }),
  Q('P628', 'Driver\'s most recent trip', 'rides', ['x_lateral', 'j_left'], 'Hard', 'LEFT JOIN LATERAL keeps rows with no match',
    'For every driver, their most recent completed trip id and fare; drivers with none show empty values. Return driver id, name, last trip, fare; sort by driver id.', ['driver_id', 'name', 'last_trip', 'fare'], true,
    `SELECT d.driver_id, d.name, t.trip_id AS last_trip, t.fare FROM drivers d LEFT JOIN LATERAL (SELECT trip_id, fare FROM trips WHERE driver_id = d.driver_id AND status = 'completed' ORDER BY requested_at DESC, trip_id DESC LIMIT 1) t ON true ORDER BY d.driver_id;`,
    ['Driver with only cancellations', 'They stay with empty values.', `INSERT INTO drivers VALUES (17,'Nikhil','Mumbai','2026-02-12','bike');`],
    ['Some drivers never completed a trip.', 'Which join keeps them?', 'LEFT JOIN LATERAL (…) t ON true'],
    'CROSS JOIN LATERAL drops outer rows whose subquery returns nothing; LEFT JOIN LATERAL … ON true keeps them.',
    `SELECT d.driver_id, d.name, t.trip_id AS last_trip, t.fare FROM drivers d CROSS JOIN LATERAL (SELECT trip_id, fare FROM trips WHERE driver_id = d.driver_id AND status = 'completed' ORDER BY requested_at DESC, trip_id DESC LIMIT 1) t ORDER BY d.driver_id;`),
  Q('P629', 'Top earner per department (all departments)', 'hr', ['x_lateral', 'j_left'], 'Hard', 'LATERAL top-1 including empty groups',
    'For every department, the highest-paid employee (ties: lower emp id); departments with no employees show an empty name. Return dept name and employee name; sort by dept id.', ['dept_name', 'top_earner'], true,
    `SELECT d.dept_name, t.name AS top_earner FROM departments d LEFT JOIN LATERAL (SELECT name FROM employees e WHERE e.dept_id = d.dept_id ORDER BY salary DESC, emp_id LIMIT 1) t ON true ORDER BY d.dept_id;`,
    ['Another empty department', 'Empty groups stay.', `INSERT INTO departments VALUES (6,'Research','Pune');`],
    ['Top 1 per department.', 'Departments can be empty.', 'LEFT JOIN LATERAL (… ORDER BY salary DESC LIMIT 1) t ON true'],
    'A LATERAL subquery with LIMIT 1 is a compact top-1-per-group; LEFT JOIN keeps empty groups.',
    `SELECT d.dept_name, t.name AS top_earner FROM departments d CROSS JOIN LATERAL (SELECT name FROM employees e WHERE e.dept_id = d.dept_id ORDER BY salary DESC, emp_id LIMIT 1) t ORDER BY d.dept_id;`),
  Q('P630', 'First two events', 'saas', ['x_lateral'], 'Medium', 'Earliest N rows per user',
    'For each user, their first two events (by time, ties by event id). Return user id, event name and time; sort by user id then time.', ['user_id', 'event_name', 'event_time'], true,
    `SELECT u.user_id, x.event_name, x.event_time FROM users u CROSS JOIN LATERAL (SELECT event_name, event_time FROM events e WHERE e.user_id = u.user_id ORDER BY event_time, event_id LIMIT 2) x ORDER BY u.user_id, x.event_time, x.event_name;`,
    ['A user with one event', 'They contribute only one row.', `INSERT INTO users VALUES (13,'2026-03-25','IN','organic'); INSERT INTO events VALUES (46,13,'signup','2026-03-25 10:00','{}');`],
    ['Earliest first.', 'LIMIT 2 per user.', 'ORDER BY event_time, event_id LIMIT 2 inside LATERAL'],
    'Sort direction decides first versus last.',
    `SELECT u.user_id, x.event_name, x.event_time FROM users u CROSS JOIN LATERAL (SELECT event_name, event_time FROM events e WHERE e.user_id = u.user_id ORDER BY event_time DESC, event_id DESC LIMIT 2) x ORDER BY u.user_id, x.event_time, x.event_name;`, { patterns: ['top_n_per_group'] }),
  Q('P631', 'Two best grades per student', 'campus', ['x_lateral'], 'Hard', 'LATERAL + NULL ordering trap',
    'For each student, their two highest completed grades with the course. Return student id, course id and grade; sort by student id, grade desc, course id.', ['student_id', 'course_id', 'grade'], true,
    `SELECT s.student_id, x.course_id, x.grade FROM students s CROSS JOIN LATERAL (SELECT course_id, grade FROM enrollments e WHERE e.student_id = s.student_id AND e.status = 'completed' ORDER BY grade DESC, course_id LIMIT 2) x ORDER BY s.student_id, x.grade DESC, x.course_id;`,
    ['In-progress rows', 'In-progress rows have no grade.', `INSERT INTO enrollments VALUES (3,'C301','2026S',NULL,'in_progress');`, 'NULL handling'],
    ['ORDER BY grade DESC puts NULLs first in PostgreSQL.', 'Restrict to completed rows.', "WHERE e.status = 'completed' ORDER BY grade DESC LIMIT 2"],
    'In PostgreSQL NULL sorts as the largest value, so DESC lists ungraded rows first unless you filter them.',
    `SELECT s.student_id, x.course_id, x.grade FROM students s CROSS JOIN LATERAL (SELECT course_id, grade FROM enrollments e WHERE e.student_id = s.student_id ORDER BY grade DESC, course_id LIMIT 2) x ORDER BY s.student_id, x.grade DESC, x.course_id;`),
  Q('P632', 'Recent order values', 'food', ['x_lateral'], 'Hard', 'Aggregate over a per-row top-N',
    'For each restaurant with delivered orders, the average order value of its 3 most recent delivered orders (2 decimals). Return restaurant id and the average; sort by restaurant id.', ['restaurant_id', 'avg_last3'], true,
    `SELECT r.restaurant_id, ROUND(a.v, 2) AS avg_last3 FROM restaurants r CROSS JOIN LATERAL (SELECT AVG(order_value) AS v FROM (SELECT order_value FROM deliveries d WHERE d.restaurant_id = r.restaurant_id AND d.status = 'delivered' ORDER BY ordered_at DESC, delivery_id DESC LIMIT 3) x) a WHERE a.v IS NOT NULL ORDER BY r.restaurant_id;`,
    ['More than three orders', 'Only the latest three count.', `INSERT INTO deliveries VALUES (21,1,113,'2026-03-10 12:00','2026-03-10 12:40','delivered',2000,30,NULL,3.0,4),(22,1,114,'2026-03-11 12:00','2026-03-11 12:40','delivered',2000,30,NULL,3.0,4),(23,1,115,'2026-03-12 12:00','2026-03-12 12:40','delivered',2000,30,NULL,3.0,4);`],
    ['Take the latest 3 per restaurant first.', 'Then average them.', 'LATERAL (SELECT AVG(…) FROM (SELECT … ORDER BY … LIMIT 3) x)'],
    'Averaging all orders ignores "most recent 3"; the LIMIT must be applied before AVG.',
    `SELECT d.restaurant_id, ROUND(AVG(d.order_value), 2) AS avg_last3 FROM deliveries d WHERE d.status = 'delivered' GROUP BY d.restaurant_id ORDER BY d.restaurant_id;`),

  // ── Pivot / unpivot ──
  Q('P633', 'Revenue by category per month', 'shop', ['x_pivot'], 'Medium', 'Pivot with FILTER and zeros',
    'One row per month with completed revenue split into four columns: electronics, fitness, grocery, home (0 when none). Months as first-of-month dates, sorted.', ['month', 'electronics', 'fitness', 'grocery', 'home'], true,
    `SELECT date_trunc('month', o.order_date)::date AS month,
  COALESCE(SUM(oi.quantity * oi.unit_price) FILTER (WHERE p.category = 'Electronics'), 0) AS electronics,
  COALESCE(SUM(oi.quantity * oi.unit_price) FILTER (WHERE p.category = 'Fitness'), 0) AS fitness,
  COALESCE(SUM(oi.quantity * oi.unit_price) FILTER (WHERE p.category = 'Grocery'), 0) AS grocery,
  COALESCE(SUM(oi.quantity * oi.unit_price) FILTER (WHERE p.category = 'Home'), 0) AS home
FROM orders o JOIN order_items oi ON oi.order_id = o.order_id JOIN products p ON p.product_id = oi.product_id WHERE o.status = 'completed' GROUP BY 1 ORDER BY 1;`,
    ['A Home sale', 'The home column fills in.', `INSERT INTO orders VALUES (1018,10,'2026-04-12','completed',NULL); INSERT INTO order_items VALUES (1018,108,1,1499);`],
    ['Categories become columns.', 'One conditional sum per category.', 'SUM(…) FILTER (WHERE p.category = \'Electronics\')'],
    'A SUM over no rows is NULL; wrap in COALESCE so absent combinations read 0.',
    `SELECT date_trunc('month', o.order_date)::date AS month, SUM(oi.quantity * oi.unit_price) FILTER (WHERE p.category = 'Electronics') AS electronics, SUM(oi.quantity * oi.unit_price) FILTER (WHERE p.category = 'Fitness') AS fitness, SUM(oi.quantity * oi.unit_price) FILTER (WHERE p.category = 'Grocery') AS grocery, SUM(oi.quantity * oi.unit_price) FILTER (WHERE p.category = 'Home') AS home FROM orders o JOIN order_items oi ON oi.order_id = o.order_id JOIN products p ON p.product_id = oi.product_id WHERE o.status = 'completed' GROUP BY 1 ORDER BY 1;`, { patterns: ['conditional_agg'] }),
  Q('P634', 'Delivered vs cancelled per restaurant', 'food', ['x_pivot'], 'Easy', 'COUNT FILTER pivot',
    'For each restaurant that has any orders: the number delivered and the number cancelled as two columns. Sort by restaurant id.', ['restaurant_id', 'delivered', 'cancelled'], true,
    `SELECT restaurant_id, COUNT(*) FILTER (WHERE status = 'delivered') AS delivered, COUNT(*) FILTER (WHERE status = 'cancelled') AS cancelled FROM deliveries GROUP BY restaurant_id ORDER BY restaurant_id;`,
    ['More cancellations', 'Counts follow the data.', `INSERT INTO deliveries VALUES (21,2,113,'2026-03-10 08:00',NULL,'cancelled',150,0,NULL,1.0,NULL);`],
    ['Two conditional counts.', 'FILTER or CASE.', "COUNT(*) FILTER (WHERE status = 'delivered')"],
    'COUNT(*) without a condition would put the same total in both columns.',
    `SELECT restaurant_id, COUNT(*) AS delivered, COUNT(*) AS cancelled FROM deliveries GROUP BY restaurant_id ORDER BY restaurant_id;`, { patterns: ['conditional_agg'] }),
  Q('P635', 'Where the money goes', 'food', ['x_pivot'], 'Hard', 'Unpivot columns into rows with LATERAL VALUES',
    'Turn the three money columns of delivered orders into rows: for each component (food, delivery_fee, tip) the total across delivered orders. Return component and total, sorted by component.', ['component', 'total'], true,
    `SELECT v.component, SUM(v.amount) AS total FROM deliveries d CROSS JOIN LATERAL (VALUES ('food', d.order_value), ('delivery_fee', d.delivery_fee), ('tip', d.tip)) AS v(component, amount) WHERE d.status = 'delivered' GROUP BY v.component ORDER BY v.component;`,
    ['A large tip', 'The tip row reflects it.', `INSERT INTO deliveries VALUES (21,1,113,'2026-03-10 20:00','2026-03-10 20:40','delivered',300,25,500,3.0,4);`],
    ['Columns to rows.', 'VALUES inside a lateral join builds one row per column.', "CROSS JOIN LATERAL (VALUES ('food', order_value), …) v(component, amount)"],
    'This is the standard unpivot: each source row fans out into one row per column.',
    `SELECT v.component, SUM(v.amount) AS total FROM deliveries d CROSS JOIN LATERAL (VALUES ('food', d.order_value), ('delivery_fee', d.delivery_fee)) AS v(component, amount) WHERE d.status = 'delivered' GROUP BY v.component ORDER BY v.component;`),
  Q('P636', 'City by vehicle matrix', 'rides', ['x_pivot'], 'Medium', 'Two-dimensional pivot',
    'A matrix of completed trips: one row per city, with columns sedan, auto and bike counting trips by the driver\'s vehicle type. Sort by city.', ['city', 'sedan', 'auto', 'bike'], true,
    `SELECT t.city, COUNT(*) FILTER (WHERE d.vehicle_type = 'sedan') AS sedan, COUNT(*) FILTER (WHERE d.vehicle_type = 'auto') AS auto, COUNT(*) FILTER (WHERE d.vehicle_type = 'bike') AS bike FROM trips t JOIN drivers d ON d.driver_id = t.driver_id WHERE t.status = 'completed' GROUP BY t.city ORDER BY t.city;`,
    ['A cancelled trip', 'Only completed trips count.', `INSERT INTO trips VALUES (521,7,16,'Mumbai','2026-02-08 09:00','cancelled_driver',NULL,NULL);`],
    ['Vehicle type lives on drivers.', 'One conditional count per type.', "COUNT(*) FILTER (WHERE d.vehicle_type = 'sedan')"],
    'Join to get the attribute, filter the population, then pivot with conditional counts.',
    `SELECT t.city, COUNT(*) FILTER (WHERE d.vehicle_type = 'sedan') AS sedan, COUNT(*) FILTER (WHERE d.vehicle_type = 'auto') AS auto, COUNT(*) FILTER (WHERE d.vehicle_type = 'bike') AS bike FROM trips t JOIN drivers d ON d.driver_id = t.driver_id GROUP BY t.city ORDER BY t.city;`, { patterns: ['conditional_agg'] }),
  Q('P637', 'Salary bands per department', 'hr', ['x_pivot'], 'Medium', 'Banded counts with exact boundaries',
    'For each department (ignore employees without one), count employees in three salary bands: under_100k (< 100000), mid (100000 up to but not including 150000) and high (150000 or more). Sort by dept id.', ['dept_id', 'under_100k', 'mid', 'high'], true,
    `SELECT dept_id, COUNT(*) FILTER (WHERE salary < 100000) AS under_100k, COUNT(*) FILTER (WHERE salary >= 100000 AND salary < 150000) AS mid, COUNT(*) FILTER (WHERE salary >= 150000) AS high FROM employees WHERE dept_id IS NOT NULL GROUP BY dept_id ORDER BY dept_id;`,
    ['Exactly 100000', 'Boundaries fall in the upper band.', `INSERT INTO employees VALUES (17,'Advik',3,11,'AE',100000,'2026-04-01');`],
    ['Three non-overlapping conditions.', 'Check each boundary.', 'salary >= 100000 AND salary < 150000'],
    'Half-open bands guarantee every salary lands in exactly one column.',
    `SELECT dept_id, COUNT(*) FILTER (WHERE salary < 100000) AS under_100k, COUNT(*) FILTER (WHERE salary >= 100000 AND salary <= 150000) AS mid, COUNT(*) FILTER (WHERE salary >= 150000) AS high FROM employees WHERE dept_id IS NOT NULL GROUP BY dept_id ORDER BY dept_id;`, { patterns: ['conditional_agg'] }),
  Q('P638', 'Channel funnel', 'saas', ['x_pivot', 'j_left'], 'Hard', 'Distinct users per step as columns',
    'For each acquisition channel: users who signed up, users who ever created a project and users who ever upgraded (count users, not events). Sort by channel.', ['channel', 'signups', 'created_project', 'upgraded'], true,
    `SELECT u.channel, COUNT(DISTINCT u.user_id) AS signups, COUNT(DISTINCT e.user_id) FILTER (WHERE e.event_name = 'create_project') AS created_project, COUNT(DISTINCT e.user_id) FILTER (WHERE e.event_name = 'upgrade') AS upgraded FROM users u LEFT JOIN events e ON e.user_id = u.user_id GROUP BY u.channel ORDER BY u.channel;`,
    ['Repeated project creation', 'Users count once however many events.', `INSERT INTO events VALUES (46,2,'create_project','2026-03-02 10:00','{}'),(47,2,'create_project','2026-03-03 10:00','{}');`],
    ['Users vs events.', 'DISTINCT inside FILTERed counts.', "COUNT(DISTINCT e.user_id) FILTER (WHERE e.event_name = 'upgrade')"],
    'Joining events multiplies users; count distinct user ids per step.',
    `SELECT u.channel, COUNT(*) AS signups, COUNT(*) FILTER (WHERE e.event_name = 'create_project') AS created_project, COUNT(*) FILTER (WHERE e.event_name = 'upgrade') AS upgraded FROM users u LEFT JOIN events e ON e.user_id = u.user_id GROUP BY u.channel ORDER BY u.channel;`, { patterns: ['funnel', 'conditional_agg'] }),
];
