// Level 5 — window functions and gaps & islands (P500–P544).
import { Q } from './q.js';
const OV = `SELECT o.order_id, o.customer_id, SUM(oi.quantity * oi.unit_price) AS value FROM orders o JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' GROUP BY o.order_id, o.customer_id`;
const NEWORD = `INSERT INTO orders VALUES (1018,9,'2026-04-12','completed',NULL); INSERT INTO order_items VALUES (1018,106,1,899);`;
const ISL = (u) => `WITH d AS (SELECT DISTINCT user_id, activity_date FROM user_activity), g AS (SELECT user_id, activity_date, activity_date - (ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY activity_date))::int AS grp FROM d)`;

export const PROBLEMS_H = [
  // ── Ranking ──
  Q('P500', 'Salary rank in department', 'hr', ['w_ranking'], 'Easy', 'RANK within a partition',
    'Rank employees by salary within their department (highest = 1; equal salaries share a rank). Ignore employees without a department. Return name, dept id, salary and rank, sorted by dept id, rank, name.', ['name', 'dept_id', 'salary', 'rnk'], true,
    `SELECT name, dept_id, salary, RANK() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rnk FROM employees WHERE dept_id IS NOT NULL ORDER BY dept_id, rnk, name;`,
    ['A tie in Sales', 'Ties share a rank.', `INSERT INTO employees VALUES (17,'Advik',3,11,'Account Executive',92000,'2026-04-01');`],
    ['Rank restarts per department.', 'Equal salaries must tie.', 'RANK() OVER (PARTITION BY dept_id ORDER BY salary DESC)'],
    'PARTITION BY restarts the ranking per group; RANK gives ties the same number.',
    `SELECT name, dept_id, salary, ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rnk FROM employees WHERE dept_id IS NOT NULL ORDER BY dept_id, rnk, name;`),
  Q('P501', 'Top two earners per department', 'hr', ['w_ranking'], 'Medium', 'Top-N per group keeping ties',
    'For each department return the employees with the two highest salary ranks (people tied for a rank are all included). Return dept id, name, salary, sorted by dept id, salary desc, name.', ['dept_id', 'name', 'salary'], true,
    `WITH r AS (SELECT dept_id, name, salary, RANK() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rk FROM employees WHERE dept_id IS NOT NULL) SELECT dept_id, name, salary FROM r WHERE rk <= 2 ORDER BY dept_id, salary DESC, name;`,
    ['Three-way tie for second', 'All tied people stay.', `INSERT INTO employees VALUES (17,'Advik',2,7,'PM',140000,'2026-04-01');`],
    ['Rank first, filter afterwards.', 'ROW_NUMBER would cut ties.', 'WITH r AS (SELECT …, RANK() OVER (…) rk …) SELECT … WHERE rk <= 2'],
    'Window results cannot be filtered in the same SELECT; wrap in a CTE, then filter on the rank.',
    `WITH r AS (SELECT dept_id, name, salary, ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rk FROM employees WHERE dept_id IS NOT NULL) SELECT dept_id, name, salary FROM r WHERE rk <= 2 ORDER BY dept_id, salary DESC, name;`, { patterns: ['top_n_per_group'] }),
  Q('P502', 'Best seller per category', 'shop', ['w_ranking'], 'Hard', 'Aggregate first, then rank',
    'Which product earns the most completed revenue (quantity × charged price) in each category? Include all products tied for first. Return category, product name and revenue, sorted by category then name.', ['category', 'name', 'revenue'], true,
    `WITH rev AS (SELECT p.category, p.name, SUM(oi.quantity * oi.unit_price) AS revenue FROM orders o JOIN order_items oi ON oi.order_id = o.order_id JOIN products p ON p.product_id = oi.product_id WHERE o.status = 'completed' GROUP BY p.category, p.name),
r AS (SELECT *, RANK() OVER (PARTITION BY category ORDER BY revenue DESC) AS rk FROM rev) SELECT category, name, revenue FROM r WHERE rk = 1 ORDER BY category, name;`,
    ['Tie in Fitness', 'Ties for first all appear.', `INSERT INTO orders VALUES (1018,9,'2026-04-12','completed',NULL); INSERT INTO order_items VALUES (1018,105,1,1199);`],
    ['Rank products, not order lines.', 'Total revenue per product first.', 'rev CTE (GROUP BY) → RANK() OVER (PARTITION BY category ORDER BY revenue DESC)'],
    'Ranking raw lines picks the biggest single line, not the best product.',
    `WITH r AS (SELECT p.category, p.name, oi.quantity * oi.unit_price AS revenue, RANK() OVER (PARTITION BY p.category ORDER BY oi.quantity * oi.unit_price DESC) AS rk FROM orders o JOIN order_items oi ON oi.order_id = o.order_id JOIN products p ON p.product_id = oi.product_id WHERE o.status = 'completed') SELECT category, name, revenue FROM r WHERE rk = 1 ORDER BY category, name;`, { patterns: ['top_n_per_group'] }),
  Q('P503', 'Third-highest salary', 'hr', ['w_ranking'], 'Medium', 'DENSE_RANK for the N-th distinct value',
    'What is the third-highest distinct salary in the company?', ['salary'], false,
    `SELECT DISTINCT salary FROM (SELECT salary, DENSE_RANK() OVER (ORDER BY salary DESC) AS dr FROM employees) t WHERE dr = 3;`,
    ['Tie at second place', 'Ties must not consume ranks.', `INSERT INTO employees VALUES (17,'Advik',1,1,'Architect',200000,'2026-04-01');`],
    ['"Third-highest" means third distinct value.', 'Which ranking function leaves no gaps?', 'DENSE_RANK() OVER (ORDER BY salary DESC) = 3'],
    'RANK leaves gaps after ties (1,2,2,4), so rank 3 may not exist. DENSE_RANK gives 1,2,2,3.',
    `SELECT DISTINCT salary FROM (SELECT salary, RANK() OVER (ORDER BY salary DESC) AS dr FROM employees) t WHERE dr = 3;`, { patterns: ['nth_highest'] }),
  Q('P504', 'Each rider\'s latest completed trip', 'rides', ['w_ranking'], 'Medium', 'ROW_NUMBER for latest per group',
    'For each rider, return their most recent completed trip (trip id and request time). Sort by rider id.', ['rider_id', 'trip_id', 'requested_at'], true,
    `WITH r AS (SELECT rider_id, trip_id, requested_at, ROW_NUMBER() OVER (PARTITION BY rider_id ORDER BY requested_at DESC, trip_id DESC) AS rn FROM trips WHERE status = 'completed') SELECT rider_id, trip_id, requested_at FROM r WHERE rn = 1 ORDER BY rider_id;`,
    ['Newer trip with a lower id', 'Latest means by time.', `INSERT INTO trips VALUES (521,1,11,'Bengaluru','2026-02-10 10:00','completed',200,6.0),(0,1,11,'Bengaluru','2026-02-11 10:00','completed',210,6.0);`],
    ['Order each rider\'s trips newest first.', 'Keep row number 1.', 'ROW_NUMBER() OVER (PARTITION BY rider_id ORDER BY requested_at DESC)'],
    'Sorting direction decides whether you get the first or the last row.',
    `WITH r AS (SELECT rider_id, trip_id, requested_at, ROW_NUMBER() OVER (PARTITION BY rider_id ORDER BY requested_at, trip_id) AS rn FROM trips WHERE status = 'completed') SELECT rider_id, trip_id, requested_at FROM r WHERE rn = 1 ORDER BY rider_id;`, { patterns: ['top_n_per_group'] }),
  Q('P505', 'First order per customer', 'shop', ['w_ranking'], 'Medium', 'ROW_NUMBER with a date, not an id',
    'For each customer, which was their first order (any status)? Return customer id, order id and status, sorted by customer id.', ['customer_id', 'order_id', 'status'], true,
    `WITH r AS (SELECT customer_id, order_id, status, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date, order_id) AS rn FROM orders) SELECT customer_id, order_id, status FROM r WHERE rn = 1 ORDER BY customer_id;`,
    ['Back-dated order with a higher id', 'First means by date.', `INSERT INTO orders VALUES (1018,1,'2025-12-01','cancelled',NULL);`],
    ['First by what?', 'Date, then id to break ties.', 'ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date, order_id)'],
    'Ids are not time; order by the date and add a tie-breaker so the result is deterministic.',
    `WITH r AS (SELECT customer_id, order_id, status, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_id) AS rn FROM orders) SELECT customer_id, order_id, status FROM r WHERE rn = 1 ORDER BY customer_id;`, { patterns: ['first_last_event'] }),
  Q('P506', 'Largest delivery per restaurant', 'food', ['w_ranking'], 'Medium', 'One row per group with a tie-breaker',
    'For each restaurant, the delivered order with the highest order value. If values tie, take the earliest delivery id. Return restaurant id, delivery id and value, sorted by restaurant id.', ['restaurant_id', 'delivery_id', 'order_value'], true,
    `WITH r AS (SELECT restaurant_id, delivery_id, order_value, ROW_NUMBER() OVER (PARTITION BY restaurant_id ORDER BY order_value DESC, delivery_id) AS rn FROM deliveries WHERE status = 'delivered') SELECT restaurant_id, delivery_id, order_value FROM r WHERE rn = 1 ORDER BY restaurant_id;`,
    ['Two equal maxima', 'Exactly one row per restaurant.', `INSERT INTO deliveries VALUES (21,1,113,'2026-03-10 20:00','2026-03-10 20:40','delivered',890,30,NULL,3.0,4);`],
    ['A tie must still give one row.', 'Add a tie-breaker.', 'ROW_NUMBER() OVER (PARTITION BY restaurant_id ORDER BY order_value DESC, delivery_id)'],
    'RANK would return both tied rows; ROW_NUMBER with a tie-breaker returns exactly one.',
    `WITH r AS (SELECT restaurant_id, delivery_id, order_value, RANK() OVER (PARTITION BY restaurant_id ORDER BY order_value DESC) AS rn FROM deliveries WHERE status = 'delivered') SELECT restaurant_id, delivery_id, order_value FROM r WHERE rn = 1 ORDER BY restaurant_id;`, { patterns: ['top_n_per_group'] }),
  Q('P507', 'Best course per student', 'campus', ['w_ranking'], 'Medium', 'RANK keeping ties per student',
    'For each student, which completed course(s) earned their highest grade? Include ties. Return student id, course id and grade, sorted by student id then course id.', ['student_id', 'course_id', 'grade'], true,
    `WITH r AS (SELECT student_id, course_id, grade, RANK() OVER (PARTITION BY student_id ORDER BY grade DESC) AS rk FROM enrollments WHERE status = 'completed') SELECT student_id, course_id, grade FROM r WHERE rk = 1 ORDER BY student_id, course_id;`,
    ['Two courses with the same top grade', 'Tied courses are both returned.', `INSERT INTO enrollments VALUES (8,'C101','2026S',9.0,'completed'),(8,'C203','2026S',9.0,'completed');`],
    ['Only completed rows have grades.', 'Keep ties.', 'RANK() OVER (PARTITION BY student_id ORDER BY grade DESC) = 1'],
    'RANK = 1 keeps every row tied for the best value.',
    `WITH r AS (SELECT student_id, course_id, grade, ROW_NUMBER() OVER (PARTITION BY student_id ORDER BY grade DESC) AS rk FROM enrollments WHERE status = 'completed') SELECT student_id, course_id, grade FROM r WHERE rk = 1 ORDER BY student_id, course_id;`, { patterns: ['top_n_per_group'] }),
  Q('P508', 'Events to keep', 'saas', ['w_ranking', 'x_dedup'], 'Medium', 'Dedupe with ROW_NUMBER on the right key',
    'The tracking pipeline sometimes writes the same event twice (same user, event name and exact time). Return the event ids to KEEP: one per distinct (user, event name, time), the lowest event id. Sorted.', ['event_id'], true,
    `SELECT event_id FROM (SELECT event_id, ROW_NUMBER() OVER (PARTITION BY user_id, event_name, event_time ORDER BY event_id) AS rn FROM events) t WHERE rn = 1 ORDER BY event_id;`,
    ['Same event name at different times', 'Only identical times are duplicates.', `INSERT INTO events VALUES (46,1,'login','2026-03-02 08:00','{}'),(47,1,'login','2026-03-02 08:00','{}');`],
    ['What makes two rows duplicates?', 'Partition by exactly that key.', 'PARTITION BY user_id, event_name, event_time ORDER BY event_id'],
    'Too small a key deletes legitimate repeats (two logins on different days).',
    `SELECT event_id FROM (SELECT event_id, ROW_NUMBER() OVER (PARTITION BY user_id, event_name ORDER BY event_id) AS rn FROM events) t WHERE rn = 1 ORDER BY event_id;`, { patterns: ['dedup'] }),
  Q('P509', 'Top three spenders', 'shop', ['w_ranking'], 'Medium', 'RANK on aggregated spend with ties',
    'Rank customers by completed spend and return those in the top three ranks (ties included). Return customer id, spend and rank, sorted by rank then customer id.', ['customer_id', 'spend', 'rnk'], true,
    `WITH s AS (SELECT customer_id, SUM(value) AS spend FROM (${OV}) ov GROUP BY customer_id), r AS (SELECT customer_id, spend, RANK() OVER (ORDER BY spend DESC) AS rnk FROM s) SELECT customer_id, spend, rnk FROM r WHERE rnk <= 3 ORDER BY rnk, customer_id;`,
    ['Tie for third', 'LIMIT 3 would cut a tied customer.', `INSERT INTO orders VALUES (1018,9,'2026-04-12','completed',NULL); INSERT INTO order_items VALUES (1018,101,1,5598);`],
    ['Total spend per customer first.', 'Then rank.', 'RANK() OVER (ORDER BY spend DESC) <= 3'],
    'LIMIT counts rows; RANK counts positions, so tied customers stay.',
    `WITH s AS (SELECT customer_id, SUM(value) AS spend FROM (${OV}) ov GROUP BY customer_id) SELECT customer_id, spend, ROW_NUMBER() OVER (ORDER BY spend DESC) AS rnk FROM s ORDER BY spend DESC LIMIT 3;`),
  Q('P510', 'Fare quartiles', 'rides', ['w_ranking'], 'Medium', 'NTILE buckets',
    'Split completed trips into four equal-sized fare quartiles (1 = cheapest; ties in fare broken by trip id). Return trip id, fare and quartile, sorted by trip id.', ['trip_id', 'fare', 'quartile'], true,
    `SELECT trip_id, fare, NTILE(4) OVER (ORDER BY fare, trip_id) AS quartile FROM trips WHERE status = 'completed' ORDER BY trip_id;`,
    ['Extra completed trip', 'Bucket sizes follow the row count.', `INSERT INTO trips VALUES (521,7,16,'Mumbai','2026-02-08 09:00','completed',100,3.0);`],
    ['Which trips are in scope?', 'NTILE(4) splits ordered rows into 4 buckets.', 'NTILE(4) OVER (ORDER BY fare, trip_id) with WHERE status = \'completed\''],
    'Window functions run after WHERE, so cancelled trips (NULL fares) must be filtered first or they distort the buckets.',
    `SELECT trip_id, fare, NTILE(4) OVER (ORDER BY fare, trip_id) AS quartile FROM trips ORDER BY trip_id;`),
  Q('P511', 'Runner-up per department', 'hr', ['w_ranking'], 'Medium', 'DENSE_RANK = 2 per group',
    'In each department, who has the second-highest distinct salary? (All people at that salary.) Ignore employees without a department. Return dept id, name, salary, sorted by dept id then name.', ['dept_id', 'name', 'salary'], true,
    `WITH r AS (SELECT dept_id, name, salary, DENSE_RANK() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS dr FROM employees WHERE dept_id IS NOT NULL) SELECT dept_id, name, salary FROM r WHERE dr = 2 ORDER BY dept_id, name;`,
    ['Tie at the top', 'The runner-up is the next distinct salary.', `INSERT INTO employees VALUES (17,'Advik',1,1,'Architect',300000,'2026-04-01');`],
    ['Second distinct salary.', 'Ties at the top must not take rank 2.', 'DENSE_RANK() OVER (PARTITION BY dept_id ORDER BY salary DESC) = 2'],
    'ROW_NUMBER = 2 would return a tied top earner as runner-up.',
    `WITH r AS (SELECT dept_id, name, salary, ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS dr FROM employees WHERE dept_id IS NOT NULL) SELECT dept_id, name, salary FROM r WHERE dr = 2 ORDER BY dept_id, name;`, { patterns: ['nth_highest'] }),

  // ── LAG / LEAD ──
  Q('P512', 'Days between orders', 'shop', ['w_offset'], 'Medium', 'LAG per customer',
    'For every completed order, show the number of days since the same customer\'s previous completed order (empty for their first). Return customer id, order id, date and days since previous; sort by customer id then date then order id.', ['customer_id', 'order_id', 'order_date', 'days_since_prev'], true,
    `SELECT customer_id, order_id, order_date, order_date - LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date, order_id) AS days_since_prev FROM orders WHERE status = 'completed' ORDER BY customer_id, order_date, order_id;`,
    ['Same-day orders', 'Gap is 0 for same-day orders.', `INSERT INTO orders VALUES (1018,1,'2026-04-02','completed',NULL);`],
    ['Look at the previous row of the same customer.', 'LAG restarts per partition.', 'order_date - LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date, order_id)'],
    'Without PARTITION BY, the "previous" order may belong to someone else.',
    `SELECT customer_id, order_id, order_date, order_date - LAG(order_date) OVER (ORDER BY customer_id, order_date, order_id) AS days_since_prev FROM orders WHERE status = 'completed' ORDER BY customer_id, order_date, order_id;`, { patterns: ['prev_next'] }),
  Q('P513', 'Minutes since the last event', 'saas', ['w_offset'], 'Medium', 'LAG over timestamps',
    'For every event, how many minutes (rounded) passed since the same user\'s previous event? Empty for a user\'s first event. Return event id, user id and minutes; sort by event id.', ['event_id', 'user_id', 'minutes_since_prev'], true,
    `SELECT event_id, user_id, ROUND(EXTRACT(EPOCH FROM event_time - LAG(event_time) OVER (PARTITION BY user_id ORDER BY event_time, event_id)) / 60) AS minutes_since_prev FROM events ORDER BY event_id;`,
    ['A user\'s first event', 'First rows have no previous.', `INSERT INTO users VALUES (13,'2026-03-25','IN','organic'); INSERT INTO events VALUES (46,13,'signup','2026-03-25 10:00','{}'),(47,13,'login','2026-03-25 10:30','{}');`],
    ['Per user, in time order.', 'Subtract timestamps, convert to minutes.', 'EXTRACT(EPOCH FROM t - LAG(t) OVER (PARTITION BY user_id ORDER BY t)) / 60'],
    'Subtracting timestamps gives an interval; EXTRACT(EPOCH …) turns it into seconds.',
    `SELECT event_id, user_id, ROUND(EXTRACT(EPOCH FROM event_time - LAG(event_time) OVER (ORDER BY event_time, event_id)) / 60) AS minutes_since_prev FROM events ORDER BY event_id;`, { patterns: ['prev_next'] }),
  Q('P514', 'Re-orders within 30 days', 'shop', ['w_offset'], 'Hard', 'LAG + filter on the gap (boundary inclusive)',
    'List completed orders placed 30 days or fewer after the same customer\'s previous completed order. Return customer id, order id and the gap in days, sorted by order id.', ['customer_id', 'order_id', 'days_gap'], true,
    `WITH g AS (SELECT customer_id, order_id, order_date - LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date, order_id) AS days_gap FROM orders WHERE status = 'completed') SELECT customer_id, order_id, days_gap FROM g WHERE days_gap <= 30 ORDER BY order_id;`,
    ['Exactly 30 days', 'The boundary is inclusive.', `INSERT INTO orders VALUES (1018,3,'2026-03-22','completed',NULL);`],
    ['Compute the gap, then filter.', 'A window result needs a wrapper to filter.', 'WITH g AS (SELECT …, order_date - LAG(order_date) OVER (…) AS days_gap …) … WHERE days_gap <= 30'],
    '"30 days or fewer" is <= 30; < 30 misses the boundary.',
    `WITH g AS (SELECT customer_id, order_id, order_date - LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date, order_id) AS days_gap FROM orders WHERE status = 'completed') SELECT customer_id, order_id, days_gap FROM g WHERE days_gap < 30 ORDER BY order_id;`, { patterns: ['prev_next'] }),
  Q('P515', 'Daily revenue change', 'rides', ['w_offset'], 'Medium', 'Day-over-day difference',
    'For each date with completed trips, total fare and the change versus the previous date in the list (empty for the first). Return day, revenue, change; sorted by day.', ['day', 'revenue', 'change'], true,
    `WITH d AS (SELECT requested_at::date AS day, SUM(fare) AS revenue FROM trips WHERE status = 'completed' GROUP BY 1) SELECT day, revenue, revenue - LAG(revenue) OVER (ORDER BY day) AS change FROM d ORDER BY day;`,
    ['A new day', 'The last row compares with its predecessor.', `INSERT INTO trips VALUES (521,7,16,'Mumbai','2026-02-08 09:00','completed',100,3.0);`],
    ['Daily totals first.', 'Compare with the previous day.', 'revenue - LAG(revenue) OVER (ORDER BY day)'],
    'LAG looks backwards; LEAD would compare with tomorrow and flip the sign.',
    `WITH d AS (SELECT requested_at::date AS day, SUM(fare) AS revenue FROM trips WHERE status = 'completed' GROUP BY 1) SELECT day, revenue, LEAD(revenue) OVER (ORDER BY day) - revenue AS change FROM d ORDER BY day;`, { patterns: ['prev_next'] }),
  Q('P516', 'Rating drops', 'food', ['w_offset'], 'Hard', 'LAG after removing NULLs',
    'For each customer, compare each rated order with their previous RATED order (by order time). List the orders where the rating dropped. Return customer id, delivery id, rating and previous rating, sorted by delivery id.', ['customer_id', 'delivery_id', 'rating', 'prev_rating'], true,
    `WITH r AS (SELECT customer_id, delivery_id, rating, LAG(rating) OVER (PARTITION BY customer_id ORDER BY ordered_at) AS prev_rating FROM deliveries WHERE rating IS NOT NULL) SELECT customer_id, delivery_id, rating, prev_rating FROM r WHERE rating < prev_rating ORDER BY delivery_id;`,
    ['Unrated order in between', 'Unrated orders must be skipped.', `INSERT INTO deliveries VALUES (21,7,106,'2026-03-02 10:00','2026-03-02 10:30','delivered',300,25,NULL,2.0,5),(22,7,106,'2026-03-09 10:00','2026-03-09 10:30','delivered',300,25,NULL,2.0,3);`, 'NULL handling'],
    ['NULL ratings must not be the "previous" rating.', 'Filter before the window runs.', 'WHERE rating IS NOT NULL inside the same query as LAG'],
    'WHERE is applied before window functions, so filtering NULLs there makes LAG skip them.',
    `WITH r AS (SELECT customer_id, delivery_id, rating, LAG(rating) OVER (PARTITION BY customer_id ORDER BY ordered_at) AS prev_rating FROM deliveries) SELECT customer_id, delivery_id, rating, prev_rating FROM r WHERE rating < prev_rating ORDER BY delivery_id;`, { patterns: ['prev_next'] }),
  Q('P517', 'Invite then upgrade', 'saas', ['w_offset'], 'Hard', 'LEAD to inspect the very next event',
    'Which users had an upgrade as the very NEXT event after inviting a teammate? Return user id, sorted.', ['user_id'], true,
    `WITH s AS (SELECT user_id, event_name, LEAD(event_name) OVER (PARTITION BY user_id ORDER BY event_time, event_id) AS next_event FROM events) SELECT DISTINCT user_id FROM s WHERE event_name = 'invite_teammate' AND next_event = 'upgrade' ORDER BY user_id;`,
    ['Login between invite and upgrade', 'Only the immediately next event counts.', `INSERT INTO events VALUES (46,1,'login','2026-01-10 10:00','{}');`],
    ['Next event per user, in order.', 'Compare it with the target.', 'LEAD(event_name) OVER (PARTITION BY user_id ORDER BY event_time, event_id)'],
    'LEAD exposes the following row; an EXISTS on "any later upgrade" would be a looser rule.',
    `SELECT DISTINCT i.user_id FROM events i WHERE i.event_name = 'invite_teammate' AND EXISTS (SELECT 1 FROM events u WHERE u.user_id = i.user_id AND u.event_name = 'upgrade' AND u.event_time > i.event_time) ORDER BY i.user_id;`, { patterns: ['prev_next'] }),
  Q('P518', 'Gap to the next higher salary', 'hr', ['w_offset'], 'Medium', 'LAG on a sorted partition',
    'In each department, order employees by salary (lowest first, ties by id). For each, show the salary gap to the next higher-paid colleague (empty for the highest). Ignore employees without a department. Return name, dept id, salary, gap; sort by dept id, salary, id.', ['name', 'dept_id', 'salary', 'gap_to_next_higher'], true,
    `SELECT name, dept_id, salary, LEAD(salary) OVER (PARTITION BY dept_id ORDER BY salary, emp_id) - salary AS gap_to_next_higher FROM employees WHERE dept_id IS NOT NULL ORDER BY dept_id, salary, emp_id;`,
    ['A new mid-salary hire', 'The gap moves with the data.', `INSERT INTO employees VALUES (17,'Advik',1,2,'Engineer',150000,'2026-04-01');`],
    ['Sort lowest first.', 'The next higher row is the following row.', 'LEAD(salary) OVER (PARTITION BY dept_id ORDER BY salary, emp_id) - salary'],
    'With ascending order the "next higher" colleague is the next row (LEAD).',
    `SELECT name, dept_id, salary, LEAD(salary) OVER (ORDER BY dept_id, salary, emp_id) - salary AS gap_to_next_higher FROM employees WHERE dept_id IS NOT NULL ORDER BY dept_id, salary, emp_id;`, { patterns: ['prev_next'] }),
  Q('P519', 'Plan changes', 'saas', ['w_offset'], 'Medium', 'LAG over a history table',
    'For every subscription that replaced an earlier one for the same user, show the user, the new plan and the previous plan. Sort by user id.', ['user_id', 'plan', 'prev_plan'], true,
    `SELECT user_id, plan, prev_plan FROM (SELECT user_id, plan, LAG(plan) OVER (PARTITION BY user_id ORDER BY start_date) AS prev_plan FROM subscriptions) t WHERE prev_plan IS NOT NULL ORDER BY user_id;`,
    ['Another upgrade path', 'More changes appear.', `INSERT INTO subscriptions VALUES (7,1,'team',90,'2026-04-01',NULL);`],
    ['Per user, in start order.', 'The first subscription has no previous plan.', 'LAG(plan) OVER (PARTITION BY user_id ORDER BY start_date)'],
    'Per-user history needs PARTITION BY user_id so one user\'s plan never becomes another\'s "previous".',
    `SELECT user_id, plan, prev_plan FROM (SELECT user_id, plan, LAG(plan) OVER (ORDER BY start_date) AS prev_plan FROM subscriptions) t WHERE prev_plan IS NOT NULL ORDER BY user_id;`, { patterns: ['prev_next'] }),

  // ── Running totals & shares ──
  Q('P520', 'Cumulative monthly revenue', 'shop', ['w_aggregate'], 'Medium', 'Running SUM',
    'Monthly completed revenue with a running total across months. Months are first-of-month dates. Return month, revenue, running revenue; sorted by month.', ['month', 'revenue', 'running_revenue'], true,
    `WITH m AS (SELECT date_trunc('month', o.order_date)::date AS month, SUM(oi.quantity * oi.unit_price) AS revenue FROM orders o JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' GROUP BY 1) SELECT month, revenue, SUM(revenue) OVER (ORDER BY month) AS running_revenue FROM m ORDER BY month;`,
    ['A new month', 'Running totals extend.', `INSERT INTO orders VALUES (1018,10,'2026-05-02','completed',NULL); INSERT INTO order_items VALUES (1018,105,1,2999);`],
    ['Aggregate to months first.', 'SUM … OVER (ORDER BY month) accumulates.', 'SUM(revenue) OVER (ORDER BY month)'],
    'ORDER BY inside OVER turns an aggregate into a running one; without it you get the grand total on every row.',
    `WITH m AS (SELECT date_trunc('month', o.order_date)::date AS month, SUM(oi.quantity * oi.unit_price) AS revenue FROM orders o JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' GROUP BY 1) SELECT month, revenue, SUM(revenue) OVER () AS running_revenue FROM m ORDER BY month;`, { patterns: ['running_total'] }),
  Q('P521', 'Share of the customer\'s spend', 'shop', ['w_aggregate'], 'Medium', 'Percent of a partition total',
    'For each completed order, what percent of that customer\'s total completed spend is it (1 decimal)? Return order id, customer id, value and the percent; sort by order id.', ['order_id', 'customer_id', 'value', 'pct_of_customer'], true,
    `WITH ov AS (${OV}) SELECT order_id, customer_id, value, ROUND(100.0 * value / SUM(value) OVER (PARTITION BY customer_id), 1) AS pct_of_customer FROM ov ORDER BY order_id;`,
    ['A new order for a customer', 'Shares re-balance.', `INSERT INTO orders VALUES (1018,1,'2026-04-12','completed',NULL); INSERT INTO order_items VALUES (1018,105,1,2999);`],
    ['Value per order first.', 'The denominator is per customer.', 'value / SUM(value) OVER (PARTITION BY customer_id)'],
    'A partitioned window total is the denominator for within-group shares.',
    `WITH ov AS (${OV}) SELECT order_id, customer_id, value, ROUND(100.0 * value / SUM(value) OVER (), 1) AS pct_of_customer FROM ov ORDER BY order_id;`, { patterns: ['pct_of_total'] }),
  Q('P522', 'Pay versus department average', 'hr', ['w_aggregate'], 'Easy', 'Window AVG per partition',
    'For every employee with a department, show their salary, the average salary of their department (2 decimals) and the difference (2 decimals). Return name, dept id, salary, dept_avg, diff; sorted by emp id.', ['name', 'dept_id', 'salary', 'dept_avg', 'diff'], true,
    `SELECT name, dept_id, salary, ROUND(AVG(salary) OVER (PARTITION BY dept_id), 2) AS dept_avg, ROUND(salary - AVG(salary) OVER (PARTITION BY dept_id), 2) AS diff FROM employees WHERE dept_id IS NOT NULL ORDER BY emp_id;`,
    ['A new high earner', 'Averages shift.', `INSERT INTO employees VALUES (17,'Advik',4,14,'Analyst',400000,'2026-04-01');`],
    ['Keep every row while computing a group average.', 'Window functions do not collapse rows.', 'AVG(salary) OVER (PARTITION BY dept_id)'],
    'Unlike GROUP BY, a window aggregate leaves every row in place.',
    `SELECT name, dept_id, salary, ROUND(AVG(salary) OVER (), 2) AS dept_avg, ROUND(salary - AVG(salary) OVER (), 2) AS diff FROM employees WHERE dept_id IS NOT NULL ORDER BY emp_id;`),
  Q('P523', 'Driver trip counter', 'rides', ['w_aggregate'], 'Medium', 'Running COUNT per partition',
    'For each completed trip, which number is it in the driver\'s sequence of completed trips (time order, ties by trip id)? Return trip id, driver id and the running count; sort by trip id.', ['trip_id', 'driver_id', 'n_so_far'], true,
    `SELECT trip_id, driver_id, COUNT(*) OVER (PARTITION BY driver_id ORDER BY requested_at, trip_id) AS n_so_far FROM trips WHERE status = 'completed' ORDER BY trip_id;`,
    ['A late trip for a busy driver', 'Counters keep increasing.', `INSERT INTO trips VALUES (521,7,11,'Bengaluru','2026-02-09 09:00','completed',100,3.0);`],
    ['Count rows up to and including this one.', 'Order inside OVER.', 'COUNT(*) OVER (PARTITION BY driver_id ORDER BY requested_at, trip_id)'],
    'Adding ORDER BY makes the default frame "start to current row", giving a running count.',
    `SELECT trip_id, driver_id, COUNT(*) OVER (PARTITION BY driver_id) AS n_so_far FROM trips WHERE status = 'completed' ORDER BY trip_id;`, { patterns: ['running_total'] }),
  Q('P524', 'Account balance after each transaction', 'bank', ['w_aggregate'], 'Medium', 'Running balance per account',
    'Show the running balance of each account after every transaction (time order, ties by txn id). Return txn id, account id, balance; sorted by txn id.', ['txn_id', 'account_id', 'balance'], true,
    `SELECT txn_id, account_id, SUM(amount) OVER (PARTITION BY account_id ORDER BY txn_time, txn_id) AS balance FROM transactions ORDER BY txn_id;`,
    ['A transaction on a quiet account', 'Accounts accumulate independently.', `INSERT INTO transactions VALUES (19,'A4','2026-03-01 10:00',500,'transfer','Deposit');`],
    ['Accumulate per account.', 'Order by time.', 'SUM(amount) OVER (PARTITION BY account_id ORDER BY txn_time, txn_id)'],
    'A running sum without PARTITION BY blends all accounts together.',
    `SELECT txn_id, account_id, SUM(amount) OVER (ORDER BY txn_time, txn_id) AS balance FROM transactions ORDER BY txn_id;`, { patterns: ['running_total'] }),
  Q('P525', 'Restaurant share of delivered value', 'food', ['w_aggregate', 'a_groupby'], 'Medium', 'Window over aggregated rows',
    'For delivered orders, each restaurant\'s total order value and its percent of the all-restaurant total (1 decimal). Return name, value, pct; biggest first, ties by name.', ['name', 'value', 'pct'], true,
    `SELECT r.name, SUM(d.order_value) AS value, ROUND(100.0 * SUM(d.order_value) / SUM(SUM(d.order_value)) OVER (), 1) AS pct FROM deliveries d JOIN restaurants r ON r.restaurant_id = d.restaurant_id WHERE d.status = 'delivered' GROUP BY r.name ORDER BY value DESC, r.name;`,
    ['A large cancelled order', 'Cancelled value is not part of the total.', `INSERT INTO deliveries VALUES (21,6,113,'2026-03-10 20:00',NULL,'cancelled',9000,0,NULL,6.0,NULL);`, 'Business logic'],
    ['The window runs after GROUP BY.', 'You can window over aggregates.', 'SUM(SUM(order_value)) OVER ()'],
    'Numerator and denominator must use the same filtered population; SUM(SUM(x)) OVER () guarantees it.',
    `SELECT r.name, SUM(d.order_value) AS value, ROUND(100.0 * SUM(d.order_value) / (SELECT SUM(order_value) FROM deliveries), 1) AS pct FROM deliveries d JOIN restaurants r ON r.restaurant_id = d.restaurant_id WHERE d.status = 'delivered' GROUP BY r.name ORDER BY value DESC, r.name;`, { patterns: ['pct_of_total'] }),
  Q('P526', 'Product share within category', 'shop', ['w_aggregate'], 'Medium', 'Partitioned share of total',
    'For each product with completed sales: its revenue and its percent of its category\'s revenue (1 decimal). Return name, category, revenue, pct_in_category; sort by category, revenue desc, name.', ['name', 'category', 'revenue', 'pct_in_category'], true,
    `WITH rev AS (SELECT p.name, p.category, SUM(oi.quantity * oi.unit_price) AS revenue FROM orders o JOIN order_items oi ON oi.order_id = o.order_id JOIN products p ON p.product_id = oi.product_id WHERE o.status = 'completed' GROUP BY p.name, p.category) SELECT name, category, revenue, ROUND(100.0 * revenue / SUM(revenue) OVER (PARTITION BY category), 1) AS pct_in_category FROM rev ORDER BY category, revenue DESC, name;`,
    ['A new product in a category', 'Shares re-balance within the category.', `INSERT INTO products VALUES (109,'Skipping Rope','Fitness',299,true); INSERT INTO orders VALUES (1018,9,'2026-04-12','completed',NULL); INSERT INTO order_items VALUES (1018,109,2,299);`],
    ['Revenue per product first.', 'Divide by the category total.', 'revenue / SUM(revenue) OVER (PARTITION BY category)'],
    'PARTITION BY category makes the denominator the category total instead of the grand total.',
    `WITH rev AS (SELECT p.name, p.category, SUM(oi.quantity * oi.unit_price) AS revenue FROM orders o JOIN order_items oi ON oi.order_id = o.order_id JOIN products p ON p.product_id = oi.product_id WHERE o.status = 'completed' GROUP BY p.name, p.category) SELECT name, category, revenue, ROUND(100.0 * revenue / SUM(revenue) OVER (), 1) AS pct_in_category FROM rev ORDER BY category, revenue DESC, name;`, { patterns: ['pct_of_total'] }),
  Q('P527', 'Payroll as the company grew', 'hr', ['w_aggregate'], 'Medium', 'Running total ordered by a date',
    'Order employees by hire date (ties by id) and show the cumulative payroll after each hire. Return name, hire date, salary, cumulative payroll; sort by hire date then id.', ['name', 'hire_date', 'salary', 'cumulative_payroll'], true,
    `SELECT name, hire_date, salary, SUM(salary) OVER (ORDER BY hire_date, emp_id) AS cumulative_payroll FROM employees ORDER BY hire_date, emp_id;`,
    ['Back-dated hire', 'The order is by date, not id.', `INSERT INTO employees VALUES (17,'Advik',1,2,'Engineer',100000,'2019-01-01');`],
    ['Order by the hire date.', 'Add the id as tie-breaker.', 'SUM(salary) OVER (ORDER BY hire_date, emp_id)'],
    'The window order, not the row order of the table, defines "so far".',
    `SELECT name, hire_date, salary, SUM(salary) OVER (ORDER BY emp_id) AS cumulative_payroll FROM employees ORDER BY hire_date, emp_id;`, { patterns: ['running_total'] }),
  Q('P528', 'Signup number within country', 'saas', ['w_aggregate'], 'Easy', 'Running COUNT by partition',
    'Number the users within each country in signup order (1 = first signup in that country; ties by id). Return user id, country, signup date and the number; sort by user id.', ['user_id', 'country', 'signup_date', 'country_signup_no'], true,
    `SELECT user_id, country, signup_date, COUNT(*) OVER (PARTITION BY country ORDER BY signup_date, user_id) AS country_signup_no FROM users ORDER BY user_id;`,
    ['A late signup in a new country', 'Each country counts separately.', `INSERT INTO users VALUES (13,'2026-03-25','SG','organic');`],
    ['Per country, in signup order.', 'Count rows up to now.', 'COUNT(*) OVER (PARTITION BY country ORDER BY signup_date, user_id)'],
    'Partition + order gives a per-group running counter.',
    `SELECT user_id, country, signup_date, COUNT(*) OVER (ORDER BY signup_date, user_id) AS country_signup_no FROM users ORDER BY user_id;`, { patterns: ['running_total'] }),

  // ── Frames ──
  Q('P529', 'Three-transaction moving average', 'bank', ['w_frames'], 'Medium', 'ROWS frame',
    'For each transaction, the average of this and the previous two transactions of the same account (time order, ties by txn id), 2 decimals. Return txn id, account id, moving average; sort by txn id.', ['txn_id', 'account_id', 'moving_avg'], true,
    `SELECT txn_id, account_id, ROUND(AVG(amount) OVER (PARTITION BY account_id ORDER BY txn_time, txn_id ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 2) AS moving_avg FROM transactions ORDER BY txn_id;`,
    ['An extra transaction', 'The window slides.', `INSERT INTO transactions VALUES (19,'A1','2026-02-10 10:00',-100,'card','Cafe');`],
    ['The window has a fixed size.', 'Define it with a frame.', 'ROWS BETWEEN 2 PRECEDING AND CURRENT ROW'],
    'Without an explicit frame the default is "all rows so far", i.e. a running average.',
    `SELECT txn_id, account_id, ROUND(AVG(amount) OVER (PARTITION BY account_id ORDER BY txn_time, txn_id), 2) AS moving_avg FROM transactions ORDER BY txn_id;`, { patterns: ['rolling_avg'] }),
  Q('P530', 'Trailing three-day revenue', 'rides', ['w_frames'], 'Medium', 'Moving average over daily totals',
    'Daily completed-trip revenue and the average of that day and the previous two days (2 decimals; first days use what is available). Return day, revenue, ma3; sorted by day.', ['day', 'revenue', 'ma3'], true,
    `WITH d AS (SELECT requested_at::date AS day, SUM(fare) AS revenue FROM trips WHERE status = 'completed' GROUP BY 1) SELECT day, revenue, ROUND(AVG(revenue) OVER (ORDER BY day ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 2) AS ma3 FROM d ORDER BY day;`,
    ['A new day', 'The trailing window moves.', `INSERT INTO trips VALUES (521,7,16,'Mumbai','2026-02-08 09:00','completed',500,3.0);`],
    ['Daily totals first.', 'Trailing means previous rows only.', 'ROWS BETWEEN 2 PRECEDING AND CURRENT ROW'],
    'A trailing window ends at the current row; a centred one (1 PRECEDING … 1 FOLLOWING) peeks into the future.',
    `WITH d AS (SELECT requested_at::date AS day, SUM(fare) AS revenue FROM trips WHERE status = 'completed' GROUP BY 1) SELECT day, revenue, ROUND(AVG(revenue) OVER (ORDER BY day ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), 2) AS ma3 FROM d ORDER BY day;`, { patterns: ['rolling_avg'] }),
  Q('P531', 'Distance from the top salary', 'hr', ['w_frames'], 'Medium', 'FIRST_VALUE per partition',
    'For each employee with a department: their salary, the highest salary in their department and the gap between them. Return name, dept id, salary, dept_top, gap_to_top; sorted by emp id.', ['name', 'dept_id', 'salary', 'dept_top', 'gap_to_top'], true,
    `SELECT name, dept_id, salary, FIRST_VALUE(salary) OVER (PARTITION BY dept_id ORDER BY salary DESC) AS dept_top, FIRST_VALUE(salary) OVER (PARTITION BY dept_id ORDER BY salary DESC) - salary AS gap_to_top FROM employees WHERE dept_id IS NOT NULL ORDER BY emp_id;`,
    ['A new top earner', 'The top salary moves.', `INSERT INTO employees VALUES (17,'Advik',4,14,'Analyst',400000,'2026-04-01');`],
    ['The first row of a descending order is the maximum.', 'FIRST_VALUE reads it.', 'FIRST_VALUE(salary) OVER (PARTITION BY dept_id ORDER BY salary DESC)'],
    'LAST_VALUE with the default frame stops at the current row, so it just returns the current salary.',
    `SELECT name, dept_id, salary, LAST_VALUE(salary) OVER (PARTITION BY dept_id ORDER BY salary) AS dept_top, LAST_VALUE(salary) OVER (PARTITION BY dept_id ORDER BY salary) - salary AS gap_to_top FROM employees WHERE dept_id IS NOT NULL ORDER BY emp_id;`, { patterns: ['first_last_event'] }),
  Q('P532', 'Running largest order', 'food', ['w_frames'], 'Medium', 'Running MAX per group',
    'For delivered orders, the largest order value seen so far at the same restaurant (time order, ties by id). Return delivery id, restaurant id, running max; sort by delivery id.', ['delivery_id', 'restaurant_id', 'running_max'], true,
    `SELECT delivery_id, restaurant_id, MAX(order_value) OVER (PARTITION BY restaurant_id ORDER BY ordered_at, delivery_id) AS running_max FROM deliveries WHERE status = 'delivered' ORDER BY delivery_id;`,
    ['A smaller later order', 'The running max does not drop.', `INSERT INTO deliveries VALUES (21,1,113,'2026-03-10 20:00','2026-03-10 20:40','delivered',100,30,NULL,3.0,4);`],
    ['"So far" needs an order.', 'Per restaurant.', 'MAX(order_value) OVER (PARTITION BY restaurant_id ORDER BY ordered_at, delivery_id)'],
    'Without ORDER BY the window covers the whole partition and every row shows the overall maximum.',
    `SELECT delivery_id, restaurant_id, MAX(order_value) OVER (PARTITION BY restaurant_id) AS running_max FROM deliveries WHERE status = 'delivered' ORDER BY delivery_id;`, { patterns: ['running_total'] }),
  Q('P533', 'New versus repeat orders', 'shop', ['w_frames', 'w_ranking'], 'Hard', 'ROW_NUMBER to classify, then conditional counts',
    'For each month, count completed orders that were the customer\'s first completed order (new) versus later ones (repeat). Return month (first-of-month), new_orders, repeat_orders; sorted by month.', ['month', 'new_orders', 'repeat_orders'], true,
    `WITH o AS (SELECT date_trunc('month', order_date)::date AS month, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date, order_id) AS rn FROM orders WHERE status = 'completed')
SELECT month, COUNT(*) FILTER (WHERE rn = 1) AS new_orders, COUNT(*) FILTER (WHERE rn > 1) AS repeat_orders FROM o GROUP BY month ORDER BY month;`,
    ['A customer\'s first order long after signup', '"New" means first order, not signup month.', `INSERT INTO orders VALUES (1018,10,'2026-04-12','completed',NULL); INSERT INTO order_items VALUES (1018,101,1,799);`],
    ['Number each customer\'s completed orders.', 'The first is new; others repeat.', 'ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date, order_id)'],
    'Classify rows with a window function, then aggregate with FILTER.',
    `SELECT date_trunc('month', o.order_date)::date AS month, COUNT(*) FILTER (WHERE date_trunc('month', c.signup_date) = date_trunc('month', o.order_date)) AS new_orders, COUNT(*) FILTER (WHERE date_trunc('month', c.signup_date) <> date_trunc('month', o.order_date)) AS repeat_orders FROM orders o JOIN customers c ON c.customer_id = o.customer_id WHERE o.status = 'completed' GROUP BY 1 ORDER BY 1;`),
  Q('P534', 'Requests in the last 24 hours', 'rides', ['w_frames'], 'Hard', 'RANGE frame with an interval',
    'For every trip request, how many requests (including itself) did the same rider make in the 24 hours up to and including that request? Return trip id, rider id and the count; sorted by trip id.', ['trip_id', 'rider_id', 'trips_last_24h'], true,
    `SELECT trip_id, rider_id, COUNT(*) OVER (PARTITION BY rider_id ORDER BY requested_at RANGE BETWEEN INTERVAL '24 hours' PRECEDING AND CURRENT ROW) AS trips_last_24h FROM trips ORDER BY trip_id;`,
    ['Exactly 24 hours earlier', 'The 24-hour boundary is inclusive.', `INSERT INTO trips VALUES (521,1,NULL,'Bengaluru','2026-02-06 08:00','cancelled_rider',NULL,NULL);`],
    ['A time-based window, not a row-count one.', 'RANGE can use intervals on timestamps.', 'RANGE BETWEEN INTERVAL \'24 hours\' PRECEDING AND CURRENT ROW'],
    'ROWS counts rows; RANGE measures distance in the ORDER BY value (here time).',
    `SELECT trip_id, rider_id, COUNT(*) OVER (PARTITION BY rider_id ORDER BY requested_at ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS trips_last_24h FROM trips ORDER BY trip_id;`, { patterns: ['rolling_avg'] }),
  Q('P535', 'Second-highest paid per department', 'hr', ['w_frames'], 'Hard', 'NTH_VALUE and the frame',
    'For each department with at least two employees, the name of the second-highest paid employee (ties broken by lower emp id first). Return dept id and name, sorted by dept id.', ['dept_id', 'second_name'], true,
    `SELECT dept_id, second_name FROM (SELECT DISTINCT dept_id, NTH_VALUE(name, 2) OVER (PARTITION BY dept_id ORDER BY salary DESC, emp_id ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS second_name FROM employees WHERE dept_id IS NOT NULL) t WHERE second_name IS NOT NULL ORDER BY dept_id;`,
    ['Department with one person', 'One-person departments are excluded.', `INSERT INTO departments VALUES (6,'Research','Pune'); INSERT INTO employees VALUES (17,'Advik',6,1,'Researcher',100000,'2026-04-01');`],
    ['Sort highest first.', 'NTH_VALUE(name, 2) reads the second row of the frame.', 'NTH_VALUE(name, 2) OVER (PARTITION BY dept_id ORDER BY salary DESC, emp_id ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)'],
    'The sort direction defines "second highest"; the explicit full frame makes every row see the same answer.',
    `SELECT dept_id, second_name FROM (SELECT DISTINCT dept_id, NTH_VALUE(name, 2) OVER (PARTITION BY dept_id ORDER BY salary, emp_id ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS second_name FROM employees WHERE dept_id IS NOT NULL) t WHERE second_name IS NOT NULL ORDER BY dept_id;`),
  Q('P536', 'Month-over-month growth', 'shop', ['w_frames', 'w_offset'], 'Hard', 'Percent change with LAG',
    'Monthly completed revenue with the previous month\'s revenue and the percent change versus the previous month (1 decimal; empty for the first month). Return month, revenue, prev_revenue, pct_change; sorted by month.', ['month', 'revenue', 'prev_revenue', 'pct_change'], true,
    `WITH m AS (SELECT date_trunc('month', o.order_date)::date AS month, SUM(oi.quantity * oi.unit_price) AS revenue FROM orders o JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' GROUP BY 1)
SELECT month, revenue, LAG(revenue) OVER (ORDER BY month) AS prev_revenue, ROUND(100.0 * (revenue - LAG(revenue) OVER (ORDER BY month)) / LAG(revenue) OVER (ORDER BY month), 1) AS pct_change FROM m ORDER BY month;`,
    ['A month with lower revenue', 'Negative growth is possible.', `INSERT INTO orders VALUES (1018,10,'2026-05-02','completed',NULL); INSERT INTO order_items VALUES (1018,107,1,349);`],
    ['Monthly totals, then LAG.', 'Percent change divides by the previous month.', '100 * (revenue - prev) / prev'],
    'Growth is relative to the starting value (the previous month), not the new one.',
    `WITH m AS (SELECT date_trunc('month', o.order_date)::date AS month, SUM(oi.quantity * oi.unit_price) AS revenue FROM orders o JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' GROUP BY 1) SELECT month, revenue, LAG(revenue) OVER (ORDER BY month) AS prev_revenue, ROUND(100.0 * (revenue - LAG(revenue) OVER (ORDER BY month)) / revenue, 1) AS pct_change FROM m ORDER BY month;`, { patterns: ['prev_next'] }),

  // ── Gaps & islands ──
  Q('P537', 'Activity streaks', 'saas', ['w_gaps'], 'Hard', 'Islands: date minus row number',
    'Using user_activity, list every streak of consecutive active days per user: user id, first day, last day and length in days. (A user can have several pings a day.) Sort by user id then start.', ['user_id', 'start_date', 'end_date', 'days'], true,
    `${ISL()} SELECT user_id, MIN(activity_date) AS start_date, MAX(activity_date) AS end_date, COUNT(*) AS days FROM g GROUP BY user_id, grp ORDER BY user_id, start_date;`,
    ['Duplicate pings', 'Several pings on one day are one active day.', `INSERT INTO user_activity VALUES (3,'2026-03-02'),(3,'2026-03-03'),(3,'2026-03-03');`],
    ['Dedupe days first.', 'Consecutive days share (date − row number).', 'activity_date - ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY activity_date)'],
    'Within a streak, date and row number rise together, so their difference is constant and labels the island.',
    `WITH g AS (SELECT user_id, activity_date, activity_date - (ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY activity_date))::int AS grp FROM user_activity) SELECT user_id, MIN(activity_date) AS start_date, MAX(activity_date) AS end_date, COUNT(*) AS days FROM g GROUP BY user_id, grp ORDER BY user_id, start_date;`, { patterns: ['gaps_islands'] }),
  Q('P538', 'Longest streak per user', 'saas', ['w_gaps'], 'Hard', 'Islands then MAX',
    'Each user\'s longest streak of consecutive active days (user_activity; several pings a day count once). Return user id and the longest streak; sort by user id.', ['user_id', 'longest_streak'], true,
    `${ISL()}, s AS (SELECT user_id, COUNT(*) AS days FROM g GROUP BY user_id, grp) SELECT user_id, MAX(days) AS longest_streak FROM s GROUP BY user_id ORDER BY user_id;`,
    ['A longer run for a quiet user', 'The longest of several streaks wins.', `INSERT INTO user_activity VALUES (3,'2026-03-10'),(3,'2026-03-11'),(3,'2026-03-12'),(3,'2026-03-13');`],
    ['Find the streaks first.', 'Then take the longest per user.', 'MAX(COUNT(*)) needs a second level'],
    'Two levels of aggregation: first group into islands, then take the maximum island size per user.',
    `SELECT user_id, COUNT(DISTINCT activity_date) AS longest_streak FROM user_activity GROUP BY user_id ORDER BY user_id;`, { patterns: ['gaps_islands'] }),
  Q('P539', 'Users with a three-day streak', 'saas', ['w_gaps'], 'Hard', 'Filter islands by length',
    'Which users were active on at least three consecutive days at some point (user_activity)? Return user id, sorted.', ['user_id'], true,
    `${ISL()} SELECT DISTINCT user_id FROM g GROUP BY user_id, grp HAVING COUNT(*) >= 3 ORDER BY user_id;`,
    ['Three scattered days', 'Active on three days is not the same as three in a row.', `INSERT INTO user_activity VALUES (3,'2026-03-10'),(3,'2026-03-12'),(3,'2026-03-14');`],
    ['Group into islands.', 'Keep islands with 3+ days.', 'GROUP BY user_id, grp HAVING COUNT(*) >= 3'],
    'Counting active days ignores whether they are consecutive.',
    `SELECT user_id FROM user_activity GROUP BY user_id HAVING COUNT(DISTINCT activity_date) >= 3 ORDER BY user_id;`, { patterns: ['gaps_islands'] }),
  Q('P540', 'Inactivity gaps', 'saas', ['w_gaps', 'w_offset'], 'Hard', 'Gaps via LEAD',
    'List every gap of inactive days between two active days of the same user in user_activity: user id, first inactive day and last inactive day. Sort by user id then start.', ['user_id', 'gap_start', 'gap_end'], true,
    `WITH d AS (SELECT DISTINCT user_id, activity_date FROM user_activity), x AS (SELECT user_id, activity_date AS prev_date, LEAD(activity_date) OVER (PARTITION BY user_id ORDER BY activity_date) AS next_date FROM d)
SELECT user_id, prev_date + 1 AS gap_start, next_date - 1 AS gap_end FROM x WHERE next_date - prev_date > 1 ORDER BY user_id, gap_start;`,
    ['A two-day gap', 'Gaps longer than one day are reported once.', `INSERT INTO user_activity VALUES (3,'2026-03-06');`],
    ['Compare each day with the next active day.', 'A gap exists when the difference exceeds 1.', 'LEAD(activity_date) OVER (PARTITION BY user_id ORDER BY activity_date)'],
    'Gaps are the mirror image of islands: look ahead and keep jumps bigger than one day.',
    `WITH d AS (SELECT DISTINCT user_id, activity_date FROM user_activity), x AS (SELECT user_id, activity_date AS prev_date, LEAD(activity_date) OVER (ORDER BY user_id, activity_date) AS next_date FROM d) SELECT user_id, prev_date + 1 AS gap_start, next_date - 1 AS gap_end FROM x WHERE next_date - prev_date > 1 ORDER BY user_id, gap_start;`, { patterns: ['gaps_islands'] }),
  Q('P541', 'Rider streak days', 'rides', ['w_gaps'], 'Hard', 'Islands over completed-trip days',
    'For each rider, list streaks of consecutive calendar days on which they completed at least one trip: rider id, first day, last day, number of days. Sort by rider, then first day.', ['rider_id', 'start_day', 'end_day', 'days'], true,
    `WITH d AS (SELECT DISTINCT rider_id, requested_at::date AS day FROM trips WHERE status = 'completed'), g AS (SELECT rider_id, day, day - (ROW_NUMBER() OVER (PARTITION BY rider_id ORDER BY day))::int AS grp FROM d)
SELECT rider_id, MIN(day) AS start_day, MAX(day) AS end_day, COUNT(*) AS days FROM g GROUP BY rider_id, grp ORDER BY rider_id, start_day;`,
    ['Two trips on one day', 'A day with two trips is still one day.', `INSERT INTO trips VALUES (521,1,11,'Bengaluru','2026-02-01 18:00','completed',100,3.0);`],
    ['One row per rider-day first.', 'Then the date-minus-row-number trick.', 'DISTINCT rider_id, requested_at::date'],
    'Duplicate days advance the row number without advancing the date and break the islands.',
    `WITH d AS (SELECT rider_id, requested_at::date AS day FROM trips WHERE status = 'completed'), g AS (SELECT rider_id, day, day - (ROW_NUMBER() OVER (PARTITION BY rider_id ORDER BY day))::int AS grp FROM d) SELECT rider_id, MIN(day) AS start_day, MAX(day) AS end_day, COUNT(*) AS days FROM g GROUP BY rider_id, grp ORDER BY rider_id, start_day;`, { patterns: ['gaps_islands'] }),
  Q('P542', 'Consecutive buying months', 'shop', ['w_gaps'], 'Very Hard', 'Islands over months',
    'For each customer, list runs of consecutive calendar months with at least one completed order: customer id, first month, last month, number of months. Months are first-of-month dates. Sort by customer, first month.', ['customer_id', 'start_month', 'end_month', 'months'], true,
    `WITH m AS (SELECT DISTINCT customer_id, date_trunc('month', order_date)::date AS month FROM orders WHERE status = 'completed'),
g AS (SELECT customer_id, month, (month - ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY month) * INTERVAL '1 month')::date AS grp FROM m)
SELECT customer_id, MIN(month) AS start_month, MAX(month) AS end_month, COUNT(*) AS months FROM g GROUP BY customer_id, grp ORDER BY customer_id, start_month;`,
    ['Two orders in one month', 'A month counts once.', `INSERT INTO orders VALUES (1018,4,'2026-02-20','completed',NULL),(1019,4,'2026-02-21','completed',NULL);`],
    ['Reduce to customer-month first.', 'Subtract one month per row number.', 'month - ROW_NUMBER() OVER (…) * INTERVAL \'1 month\''],
    'The same trick works on any evenly spaced series; the step must match the unit (here one month).',
    `WITH m AS (SELECT customer_id, date_trunc('month', order_date)::date AS month FROM orders WHERE status = 'completed'), g AS (SELECT customer_id, month, (month - ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY month) * INTERVAL '1 month')::date AS grp FROM m) SELECT customer_id, MIN(month) AS start_month, MAX(month) AS end_month, COUNT(*) AS months FROM g GROUP BY customer_id, grp ORDER BY customer_id, start_month;`, { patterns: ['gaps_islands'] }),
  Q('P543', 'Runs of debits', 'bank', ['w_gaps'], 'Very Hard', 'Islands by status change (two row numbers)',
    'For each account, find runs of consecutive DEBIT transactions (negative amounts, in time order with ties by txn id) not interrupted by a credit. Return account id, first txn id, last txn id and run length; sort by account, first txn.', ['account_id', 'first_txn', 'last_txn', 'run_length'], true,
    `WITH t AS (SELECT account_id, txn_id, amount, ROW_NUMBER() OVER (PARTITION BY account_id ORDER BY txn_time, txn_id) AS rn, ROW_NUMBER() OVER (PARTITION BY account_id, amount < 0 ORDER BY txn_time, txn_id) AS rn2 FROM transactions)
SELECT account_id, MIN(txn_id) AS first_txn, MAX(txn_id) AS last_txn, COUNT(*) AS run_length FROM t WHERE amount < 0 GROUP BY account_id, rn - rn2 ORDER BY account_id, first_txn;`,
    ['A credit splits a run', 'A credit ends the run.', `INSERT INTO transactions VALUES (19,'A1','2026-01-08 10:00',100,'transfer','Refund');`],
    ['Number all rows and number rows within each sign.', 'Their difference is constant inside a run.', 'ROW_NUMBER() OVER (PARTITION BY account_id ORDER BY …) − ROW_NUMBER() OVER (PARTITION BY account_id, amount < 0 ORDER BY …)'],
    'When the thing that changes is a state, subtract a per-state row number from the overall row number.',
    `SELECT account_id, MIN(txn_id) AS first_txn, MAX(txn_id) AS last_txn, COUNT(*) AS run_length FROM transactions WHERE amount < 0 GROUP BY account_id ORDER BY account_id, first_txn;`, { patterns: ['gaps_islands'] }),
  Q('P544', 'Long login gaps', 'saas', ['w_gaps', 'w_offset'], 'Hard', 'LAG on dates, filtered by gap length',
    'Find pairs of consecutive logins by the same user more than 30 days apart. Return user id, previous login date, next login date and gap in days; sort by user id then date.', ['user_id', 'prev_login', 'next_login', 'gap_days'], true,
    `WITH l AS (SELECT user_id, event_time::date AS d, LAG(event_time::date) OVER (PARTITION BY user_id ORDER BY event_time) AS prev_login FROM events WHERE event_name = 'login') SELECT user_id, prev_login, d AS next_login, d - prev_login AS gap_days FROM l WHERE d - prev_login > 30 ORDER BY user_id, d;`,
    ['A 31-day gap', 'The threshold is strictly more than 30.', `INSERT INTO events VALUES (46,1,'login','2026-04-02 08:00','{}');`],
    ['Per user, login events only.', 'Compare each login date with the previous one.', 'd - LAG(d) OVER (PARTITION BY user_id ORDER BY event_time)'],
    'Filter to logins before the window runs, otherwise other event types become the "previous" row.',
    `WITH l AS (SELECT user_id, event_time::date AS d, LAG(event_time::date) OVER (ORDER BY event_time) AS prev_login FROM events WHERE event_name = 'login') SELECT user_id, prev_login, d AS next_login, d - prev_login AS gap_days FROM l WHERE d - prev_login > 30 ORDER BY user_id, d;`, { patterns: ['prev_next'] }),
];
