// Level 0 — foundations, ordered roughly as a beginner meets them.
const P = (o) => ({ v: 1, timeTarget: 5, difficulty: 'Easy', patterns: [], ...o });

export const PROBLEMS_C = [
  // SELECT
  P({ id: 'P100', title: 'Product price list', dataset: 'shop', topics: ['f_select'], skills: 'SELECT columns', domain: 'E-commerce', timeTarget: 3,
    prompt: 'The catalogue team needs a simple list of every product with its category and price.',
    output: ['name', 'category', 'price'], orderMatters: false,
    solution: `SELECT name, category, price FROM products;`,
    tests: [{ name: 'New product added', category: 'Logic', why: 'The query must list every row, not specific ones.', patch: `INSERT INTO products VALUES (109,'Notebook','Stationery',199,true);` }],
    hints: ['Which table holds products? Which three columns are asked for?', 'SELECT col1, col2, col3 FROM table;', 'SELECT name, category, price FROM products;'],
    explain: 'SELECT picks columns, FROM picks the table. Without WHERE, every row is returned.',
    trap: `SELECT name, price FROM products;` }),
  P({ id: 'P101', title: 'Price with GST', dataset: 'shop', topics: ['f_select'], skills: 'Computed column + alias + ROUND', domain: 'E-commerce',
    prompt: 'Show every product\'s name, its price, and its price including 18% GST as `price_with_gst`, rounded to 2 decimals.',
    output: ['name', 'price', 'price_with_gst'], orderMatters: false,
    solution: `SELECT name, price, ROUND(price * 1.18, 2) AS price_with_gst FROM products;`,
    tests: [{ name: 'Price with paise', category: 'Logic', why: 'Rounding must be applied to the final value.', patch: `INSERT INTO products VALUES (109,'Cable','Electronics',999.99,true);` }],
    hints: ['Price including 18% tax is the price plus 18% of the price.', 'price * 1.18, then ROUND(…, 2) and name it with AS.', 'SELECT name, price, ROUND(price * 1.18, 2) AS price_with_gst FROM products;'],
    explain: 'price × 1.18 adds 18%. AS gives the computed column a readable name.',
    trap: `SELECT name, price, ROUND(price * 0.18, 2) AS price_with_gst FROM products;`, techniques: ['round'] }),
  P({ id: 'P102', title: 'Fare per kilometre', dataset: 'rides', topics: ['f_select'], skills: 'Arithmetic + NULL propagation', domain: 'Ride-sharing',
    prompt: 'For every trip request, show trip_id, fare, distance_km and the fare per kilometre (`fare_per_km`, rounded to 2 decimals). Trips without a fare or distance will naturally show nothing for fare per km — that\'s fine.',
    output: ['trip_id', 'fare', 'distance_km', 'fare_per_km'], orderMatters: false,
    solution: `SELECT trip_id, fare, distance_km, ROUND(fare / distance_km, 2) AS fare_per_km FROM trips;`,
    tests: [{ name: 'Long trip', category: 'Logic', why: 'Division order matters.', patch: `INSERT INTO trips VALUES (521,2,12,'Bengaluru','2026-02-08 09:00','completed',600,30.0);` }],
    hints: ['Per kilometre means dividing by distance.', 'fare / distance_km; ROUND(…, 2).', 'SELECT trip_id, fare, distance_km, ROUND(fare / distance_km, 2) AS fare_per_km FROM trips;'],
    explain: 'Any arithmetic with NULL returns NULL, so cancelled trips simply have no fare per km.',
    trap: `SELECT trip_id, fare, distance_km, ROUND(distance_km / fare, 2) AS fare_per_km FROM trips;` }),
  // DISTINCT / ORDER BY / LIMIT
  P({ id: 'P103', title: 'Cuisines we offer', dataset: 'food', topics: ['f_sort'], skills: 'DISTINCT + ORDER BY', domain: 'Food delivery',
    prompt: 'List each cuisine available on the platform once, in alphabetical order.',
    output: ['cuisine'], orderMatters: true,
    solution: `SELECT DISTINCT cuisine FROM restaurants ORDER BY cuisine;`,
    tests: [{ name: 'Another restaurant of an existing cuisine', category: 'Logic', why: 'Each cuisine must appear only once.', patch: `INSERT INTO restaurants VALUES (9,'Ambur Star','Biryani','Bengaluru',4.0,false,'2018-01-01');` }],
    hints: ['Several restaurants share a cuisine. How do you show each value once?', 'DISTINCT removes duplicate rows; ORDER BY sorts.', 'SELECT DISTINCT cuisine FROM restaurants ORDER BY cuisine;'],
    explain: 'DISTINCT collapses duplicate rows; ORDER BY makes the output predictable.',
    trap: `SELECT cuisine FROM restaurants ORDER BY cuisine;`, techniques: ['distinct|group\\s+by'] }),
  P({ id: 'P104', title: 'Three biggest orders', dataset: 'food', topics: ['f_sort'], skills: 'ORDER BY DESC + tie-breaker + LIMIT', domain: 'Food delivery',
    prompt: 'Show the three largest orders by order value (any status). If values tie, the lower delivery_id comes first.',
    output: ['delivery_id', 'order_value'], orderMatters: true,
    solution: `SELECT delivery_id, order_value FROM deliveries ORDER BY order_value DESC, delivery_id LIMIT 3;`,
    tests: [{ name: 'Tie for third place', category: 'Edge cases', why: 'A tie-breaker makes "top 3" deterministic.', patch: `INSERT INTO deliveries VALUES (21,3,113,'2026-03-10 12:00','2026-03-10 12:30','delivered',890,25,NULL,2.0,4);` }],
    hints: ['Largest first means descending order.', 'ORDER BY order_value DESC, then a second sort key for ties, then LIMIT.', 'ORDER BY order_value DESC, delivery_id LIMIT 3'],
    explain: 'Without a tie-breaker, which of two equal values appears in a "top 3" is undefined.',
    trap: `SELECT delivery_id, order_value FROM deliveries ORDER BY order_value LIMIT 3;`, techniques: ['limit'] }),
  P({ id: 'P105', title: 'Newest restaurants', dataset: 'food', topics: ['f_sort'], skills: 'ORDER BY multiple columns', domain: 'Food delivery',
    prompt: 'List restaurants from the most recently opened to the oldest, with ties broken alphabetically by name.',
    output: ['name', 'city', 'opened_on'], orderMatters: true,
    solution: `SELECT name, city, opened_on FROM restaurants ORDER BY opened_on DESC, name;`,
    tests: [{ name: 'Two openings on one day', category: 'Logic', why: 'The second sort key decides ties.', patch: `INSERT INTO restaurants VALUES (9,'Ambur Star','Biryani','Bengaluru',4.0,false,'2015-03-01');` }],
    hints: ['Most recent first = descending dates.', 'You can sort by more than one column.', 'ORDER BY opened_on DESC, name'],
    explain: 'Each ORDER BY column can have its own direction.',
    trap: `SELECT name, city, opened_on FROM restaurants ORDER BY opened_on, name;` }),
  // WHERE
  P({ id: 'P106', title: 'High-value deliveries', dataset: 'food', topics: ['f_filter'], skills: 'WHERE with two conditions', domain: 'Food delivery',
    prompt: 'Find delivered orders worth at least ₹600. Show the largest first.',
    output: ['delivery_id', 'restaurant_id', 'order_value'], orderMatters: true,
    solution: `SELECT delivery_id, restaurant_id, order_value FROM deliveries WHERE status = 'delivered' AND order_value >= 600 ORDER BY order_value DESC;`,
    tests: [{ name: 'Exactly ₹600', category: 'Edge cases', why: '"At least" includes the boundary.', patch: `INSERT INTO deliveries VALUES (21,3,113,'2026-03-10 12:00','2026-03-10 12:30','delivered',600,25,NULL,2.0,4);` }],
    hints: ['Two conditions must both hold.', '"At least 600" → >= 600. Combine with AND.', "WHERE status = 'delivered' AND order_value >= 600"],
    explain: 'AND requires both conditions. >= includes the boundary value.',
    trap: `SELECT delivery_id, restaurant_id, order_value FROM deliveries WHERE status = 'delivered' AND order_value > 600 ORDER BY order_value DESC;` }),
  P({ id: 'P107', title: 'Bengaluru picks', dataset: 'food', topics: ['f_filter'], skills: 'AND / OR precedence', domain: 'Food delivery',
    prompt: 'A Bengaluru campaign features restaurants in Bengaluru that are either vegetarian-only or rated 4.5 or higher. List their names and ratings, sorted by name.',
    output: ['name', 'rating'], orderMatters: true,
    solution: `SELECT name, rating FROM restaurants WHERE city = 'Bengaluru' AND (is_veg_only OR rating >= 4.5) ORDER BY name;`,
    tests: [{ name: 'Veg-only outside Bengaluru', category: 'Logic', why: 'The city condition applies to both options.', patch: `INSERT INTO restaurants VALUES (9,'Sattvam','South Indian','Chennai',4.8,true,'2019-01-01');` }],
    hints: ['Write the rule in words: city must match AND (one of two things).', 'AND is evaluated before OR — use parentheses.', "WHERE city = 'Bengaluru' AND (is_veg_only OR rating >= 4.5)"],
    explain: 'Without parentheses, a OR b AND c is read as a OR (b AND c), letting high-rated restaurants from other cities in.',
    trap: `SELECT name, rating FROM restaurants WHERE city = 'Bengaluru' AND is_veg_only OR rating >= 4.5 ORDER BY name;` }),
  P({ id: 'P108', title: 'Short cheap rides', dataset: 'rides', topics: ['f_filter'], skills: 'Strict vs inclusive comparisons', domain: 'Ride-sharing',
    prompt: 'Pricing is studying short rides: completed trips shorter than 5 km with a fare of at most ₹120. Sort by trip_id.',
    output: ['trip_id', 'distance_km', 'fare'], orderMatters: true,
    solution: `SELECT trip_id, distance_km, fare FROM trips WHERE status = 'completed' AND distance_km < 5 AND fare <= 120 ORDER BY trip_id;`,
    tests: [{ name: 'Exactly 5 km', category: 'Edge cases', why: '"Shorter than 5" excludes 5.0.', patch: `INSERT INTO trips VALUES (521,2,12,'Bengaluru','2026-02-08 09:00','completed',100,5.0),(522,2,NULL,'Bengaluru','2026-02-08 10:00','cancelled_rider',NULL,2.0);` }],
    hints: ['Three conditions. Check each boundary word: "shorter than", "at most".', '< for "shorter than", <= for "at most".', "WHERE status = 'completed' AND distance_km < 5 AND fare <= 120"],
    explain: 'Translating boundary words exactly is half of every analytics question.',
    trap: `SELECT trip_id, distance_km, fare FROM trips WHERE status = 'completed' AND distance_km <= 5 AND fare <= 120 ORDER BY trip_id;` }),
  // IN / BETWEEN / LIKE
  P({ id: 'P109', title: 'Cuisine shortlist', dataset: 'food', topics: ['f_match'], skills: 'IN', domain: 'Food delivery',
    prompt: 'List restaurants serving South Indian, Burgers or Desserts, sorted by name.',
    output: ['name', 'cuisine'], orderMatters: true,
    solution: `SELECT name, cuisine FROM restaurants WHERE cuisine IN ('South Indian', 'Burgers', 'Desserts') ORDER BY name;`,
    tests: [{ name: 'New dessert place', category: 'Logic', why: 'Every listed cuisine must match.', patch: `INSERT INTO restaurants VALUES (9,'Corner House','Desserts','Bengaluru',4.6,true,'1982-01-01');` }],
    hints: ['Matching one of several values.', 'IN (…) is shorter than chained ORs.', "WHERE cuisine IN ('South Indian', 'Burgers', 'Desserts')"],
    explain: "IN ('a', 'b', 'c') is equivalent to col = 'a' OR col = 'b' OR col = 'c'.",
    trap: `SELECT name, cuisine FROM restaurants WHERE cuisine IN ('South Indian', 'Burgers') ORDER BY name;`, techniques: ['\\bin\\s*\\(|\\bor\\b'] }),
  P({ id: 'P110', title: 'Mid-week orders', dataset: 'food', topics: ['f_match', 'f_dates'], skills: 'Safe timestamp ranges', domain: 'Food delivery',
    prompt: 'List all orders placed from 3 March to 5 March 2026, inclusive of the whole of 5 March. Sort by delivery_id.',
    output: ['delivery_id', 'ordered_at'], orderMatters: true,
    solution: `SELECT delivery_id, ordered_at FROM deliveries WHERE ordered_at >= DATE '2026-03-03' AND ordered_at < DATE '2026-03-06' ORDER BY delivery_id;`,
    tests: [{ name: 'Late on the last day', category: 'Dates/time', why: 'ordered_at is a timestamp: 5 March 23:30 must be included.', patch: `INSERT INTO deliveries VALUES (21,3,113,'2026-03-05 23:30','2026-03-06 00:05','delivered',300,25,NULL,2.0,4),(22,3,114,'2026-03-06 00:00','2026-03-06 00:30','delivered',300,25,NULL,2.0,4);` }],
    hints: ['ordered_at includes a time. What does "up to 5 March" mean for 5 March 20:00?', "BETWEEN '…' AND '2026-03-05' stops at midnight at the start of 5 March.", "WHERE ordered_at >= DATE '2026-03-03' AND ordered_at < DATE '2026-03-06'"],
    explain: 'A half-open range (>= start, < day after end) includes every moment of the last day and nothing after.',
    trap: `SELECT delivery_id, ordered_at FROM deliveries WHERE ordered_at BETWEEN '2026-03-03' AND '2026-03-05' ORDER BY delivery_id;` }),
  P({ id: 'P111', title: 'Find the burger brands', dataset: 'food', topics: ['f_match'], skills: 'ILIKE pattern matching', domain: 'Food delivery',
    prompt: 'List restaurants whose name contains the word "burger" in any capitalisation, sorted by name.',
    output: ['name'], orderMatters: true,
    solution: `SELECT name FROM restaurants WHERE name ILIKE '%burger%' ORDER BY name;`,
    tests: [{ name: 'Different capitalisation', category: 'Edge cases', why: 'User-entered names are not consistently capitalised.', patch: `INSERT INTO restaurants VALUES (9,'The Big BURGER Co','Burgers','Pune',4.0,false,'2020-01-01'),(10,'burgerman','Burgers','Pune',3.8,false,'2021-01-01');` }],
    hints: ['"Contains" means anything before and after.', '% matches any characters. LIKE is case-sensitive in PostgreSQL.', "WHERE name ILIKE '%burger%'"],
    explain: "ILIKE is case-insensitive LIKE (PostgreSQL). Portable alternative: LOWER(name) LIKE '%burger%'.",
    trap: `SELECT name FROM restaurants WHERE name LIKE '%Burger%' ORDER BY name;`, techniques: ['ilike|lower|upper'] }),
  // NULL
  P({ id: 'P112', title: 'Unrated restaurants', dataset: 'food', topics: ['f_null'], skills: 'IS NULL', domain: 'Food delivery',
    prompt: 'Quality ops wants restaurants that have no rating yet. Show name and city, sorted by name.',
    output: ['name', 'city'], orderMatters: true,
    solution: `SELECT name, city FROM restaurants WHERE rating IS NULL ORDER BY name;`,
    tests: [{ name: 'Another new restaurant', category: 'NULL handling', why: 'All unrated restaurants must be found.', patch: `INSERT INTO restaurants VALUES (9,'Ambur Star','Biryani','Bengaluru',NULL,false,'2026-03-01');` }],
    hints: ['A missing rating is NULL. Can = find NULLs?', 'Use IS NULL.', 'WHERE rating IS NULL'],
    explain: '= NULL is never true; IS NULL is the only test for missing values.',
    trap: `SELECT name, city FROM restaurants WHERE rating = NULL ORDER BY name;`,
    mistakes: [{ re: '=\\s*NULL', cat: 'NULL handling', msg: 'Compared with NULL using =', concept: 'Use IS NULL; = NULL is never true.' }] }),
  P({ id: 'P113', title: 'Tips with zeros', dataset: 'food', topics: ['f_null'], skills: 'COALESCE', domain: 'Food delivery',
    prompt: 'For delivered orders, show the tip — but show 0 instead of an empty value when no tip was recorded. Sort by delivery_id.',
    output: ['delivery_id', 'tip'], orderMatters: true,
    solution: `SELECT delivery_id, COALESCE(tip, 0) AS tip FROM deliveries WHERE status = 'delivered' ORDER BY delivery_id;`,
    tests: [{ name: 'Another untipped order', category: 'NULL handling', why: 'Every missing tip must show 0.', patch: `INSERT INTO deliveries VALUES (21,3,113,'2026-03-10 12:00','2026-03-10 12:30','delivered',300,25,NULL,2.0,4);` }],
    hints: ['You need a default value when tip is missing.', 'COALESCE returns the first non-NULL argument.', 'COALESCE(tip, 0) AS tip'],
    explain: 'COALESCE(tip, 0) replaces NULL with 0 for display.',
    trap: `SELECT delivery_id, tip FROM deliveries WHERE status = 'delivered' ORDER BY delivery_id;`, techniques: ['coalesce|case'] }),
  P({ id: 'P114', title: 'Everyone outside Engineering', dataset: 'hr', topics: ['f_null', 'f_filter'], skills: '<> and NULL', domain: 'HR', difficulty: 'Medium', timeTarget: 7,
    prompt: 'List every employee who is not in the Engineering department (dept_id 1) — including employees who have no department. Sort by name.',
    output: ['name', 'dept_id'], orderMatters: true,
    solution: `SELECT name, dept_id FROM employees WHERE dept_id <> 1 OR dept_id IS NULL ORDER BY name;`,
    tests: [{ name: 'Another unassigned employee', category: 'NULL handling', why: 'NULL <> 1 is not true, so the row is dropped.', patch: `INSERT INTO employees VALUES (17,'Advik',NULL,1,'Advisor',90000,'2025-01-01');` }],
    hints: ['What does dept_id <> 1 return when dept_id is NULL?', 'It returns NULL (not true), so WHERE drops the row. Add an explicit NULL case.', 'WHERE dept_id <> 1 OR dept_id IS NULL'],
    explain: 'Comparisons with NULL are unknown. "Not equal" filters silently drop missing values unless you include them explicitly. PostgreSQL also offers IS DISTINCT FROM 1.',
    trap: `SELECT name, dept_id FROM employees WHERE dept_id <> 1 ORDER BY name;` }),
  // CASE
  P({ id: 'P115', title: 'Distance bands', dataset: 'food', topics: ['f_case'], skills: 'CASE with boundaries', domain: 'Food delivery',
    prompt: 'Label each delivered order by distance: `short` under 2 km, `medium` from 2 km up to (but not including) 5 km, and `long` for 5 km or more. Sort by delivery_id.',
    output: ['delivery_id', 'distance_km', 'distance_band'], orderMatters: true,
    solution: `SELECT delivery_id, distance_km,
       CASE WHEN distance_km < 2 THEN 'short' WHEN distance_km < 5 THEN 'medium' ELSE 'long' END AS distance_band
FROM deliveries WHERE status = 'delivered' ORDER BY delivery_id;`,
    tests: [{ name: 'Exactly 2 km and 5 km', category: 'Edge cases', why: 'Boundaries belong to the higher band.', patch: `INSERT INTO deliveries VALUES (21,3,113,'2026-03-10 12:00','2026-03-10 12:30','delivered',300,25,NULL,2.0,4),(22,3,114,'2026-03-10 13:00','2026-03-10 13:30','delivered',300,25,NULL,5.0,4);` }],
    hints: ['Write the three ranges with < and >= before writing SQL.', 'CASE stops at the first true branch, so you can check < 2 then < 5.', "CASE WHEN distance_km < 2 THEN 'short' WHEN distance_km < 5 THEN 'medium' ELSE 'long' END"],
    explain: 'Ordered branches with strict upper bounds give clean, non-overlapping buckets.',
    trap: `SELECT delivery_id, distance_km, CASE WHEN distance_km <= 2 THEN 'short' WHEN distance_km <= 5 THEN 'medium' ELSE 'long' END AS distance_band FROM deliveries WHERE status = 'delivered' ORDER BY delivery_id;` }),
  P({ id: 'P116', title: 'Rating badges', dataset: 'food', topics: ['f_case', 'f_null'], skills: 'CASE + NULL branch', domain: 'Food delivery', difficulty: 'Medium', timeTarget: 7,
    prompt: 'Give each restaurant a badge: `new` if it has no rating, `excellent` for 4.5+, `good` for 4.0 to under 4.5, otherwise `average`. Sort by name.',
    output: ['name', 'rating', 'badge'], orderMatters: true,
    solution: `SELECT name, rating,
       CASE WHEN rating IS NULL THEN 'new' WHEN rating >= 4.5 THEN 'excellent' WHEN rating >= 4.0 THEN 'good' ELSE 'average' END AS badge
FROM restaurants ORDER BY name;`,
    tests: [{ name: 'Exactly 4.5 and 4.0', category: 'Edge cases', why: 'Boundaries are inclusive here.', patch: `INSERT INTO restaurants VALUES (9,'Ambur Star','Biryani','Bengaluru',4.0,false,'2018-01-01'),(10,'Rameshwaram Cafe','South Indian','Bengaluru',4.5,true,'2021-01-01');` }],
    hints: ['Where does a NULL rating end up if you only test numbers?', 'NULL fails every comparison and falls to ELSE. Test IS NULL first.', "CASE WHEN rating IS NULL THEN 'new' WHEN rating >= 4.5 THEN 'excellent' …"],
    explain: 'Handle NULL in its own branch before numeric comparisons, or it silently lands in ELSE.',
    trap: `SELECT name, rating, CASE WHEN rating >= 4.5 THEN 'excellent' WHEN rating >= 4.0 THEN 'good' ELSE 'average' END AS badge FROM restaurants ORDER BY name;` }),
  // Text
  P({ id: 'P117', title: 'Restaurant handles', dataset: 'food', topics: ['f_functions'], skills: 'LOWER + REPLACE', domain: 'Food delivery',
    prompt: 'Generate a URL handle for each restaurant: the name in lowercase with spaces replaced by hyphens (e.g. `burger-singh`). Sort by restaurant_id.',
    output: ['restaurant_id', 'handle'], orderMatters: true,
    solution: `SELECT restaurant_id, REPLACE(LOWER(name), ' ', '-') AS handle FROM restaurants ORDER BY restaurant_id;`,
    tests: [{ name: 'Capitalised words', category: 'Logic', why: 'Every character must be lowercase.', patch: `INSERT INTO restaurants VALUES (9,'The BIG Bowl','Asian','Pune',4.0,false,'2020-01-01');` }],
    hints: ['Two transformations: case and spaces.', 'LOWER(text) and REPLACE(text, from, to) can be nested.', "REPLACE(LOWER(name), ' ', '-')"],
    explain: 'Functions nest: the inner one runs first.',
    trap: `SELECT restaurant_id, REPLACE(name, ' ', '-') AS handle FROM restaurants ORDER BY restaurant_id;` }),
  P({ id: 'P118', title: 'Masked emails', dataset: 'shop', topics: ['f_functions', 'f_null'], skills: 'LEFT + SPLIT_PART + ||', domain: 'E-commerce', difficulty: 'Medium', timeTarget: 7,
    prompt: 'Support agents should see masked emails: the first character, then `***@`, then the domain (e.g. `a***@mail.com`). Only customers with an email. Sort by customer_id.',
    output: ['customer_id', 'masked_email'], orderMatters: true,
    solution: `SELECT customer_id, LEFT(email, 1) || '***@' || SPLIT_PART(email, '@', 2) AS masked_email
FROM customers WHERE email IS NOT NULL ORDER BY customer_id;`,
    tests: [{ name: 'Different domain', category: 'Logic', why: 'The domain must come from the email itself.', patch: `INSERT INTO customers VALUES (11,'Kiran Bose','kiran@work.in','Pune','2026-03-12',NULL);` }],
    hints: ['Three pieces glued together: first letter, a fixed text, the domain.', 'LEFT(email, 1), SPLIT_PART(email, \'@\', 2), joined with ||. Exclude missing emails.', "LEFT(email, 1) || '***@' || SPLIT_PART(email, '@', 2) … WHERE email IS NOT NULL"],
    explain: '|| concatenates text; anything || NULL is NULL, so filter missing emails out.',
    trap: `SELECT customer_id, LEFT(email, 1) || '***@' || SPLIT_PART(email, '@', 2) AS masked_email FROM customers ORDER BY customer_id;` }),
  // Math
  P({ id: 'P119', title: 'Fares rounded up', dataset: 'rides', topics: ['f_math', 'f_filter'], skills: 'CEIL', domain: 'Ride-sharing',
    prompt: 'For a cash-friendly display, show completed trips with the fare rounded UP to the next multiple of ₹50 (₹320 → ₹350, ₹450 stays ₹450). Sort by trip_id.',
    output: ['trip_id', 'fare', 'fare_rounded_up'], orderMatters: true,
    solution: `SELECT trip_id, fare, CEIL(fare / 50) * 50 AS fare_rounded_up FROM trips WHERE status = 'completed' ORDER BY trip_id;`,
    tests: [{ name: 'Just above a multiple', category: 'Edge cases', why: '₹451 rounds up to ₹500, not down.', patch: `INSERT INTO trips VALUES (521,2,12,'Bengaluru','2026-02-08 09:00','completed',451,15.0);` }],
    hints: ['Round up, not to the nearest.', 'Divide by 50, round up with CEIL, multiply back.', 'CEIL(fare / 50) * 50'],
    explain: 'Scale → CEIL → scale back is the standard way to round to any step.',
    trap: `SELECT trip_id, fare, ROUND(fare / 50) * 50 AS fare_rounded_up FROM trips WHERE status = 'completed' ORDER BY trip_id;`, techniques: ['ceil'] }),
  P({ id: 'P120', title: 'Tip as a percentage', dataset: 'food', topics: ['f_math', 'f_null'], skills: 'Percent calculation', domain: 'Food delivery',
    prompt: 'For orders where a tip was recorded, show the tip as a percentage of order value, rounded to 1 decimal. Sort by delivery_id.',
    output: ['delivery_id', 'tip_pct'], orderMatters: true,
    solution: `SELECT delivery_id, ROUND(100.0 * tip / order_value, 1) AS tip_pct FROM deliveries WHERE tip IS NOT NULL ORDER BY delivery_id;`,
    tests: [{ name: 'Small tip on a big order', category: 'Logic', why: 'Percentages must be scaled by 100.', patch: `INSERT INTO deliveries VALUES (21,6,113,'2026-03-10 20:00','2026-03-10 20:40','delivered',2000,50,15,5.0,5);` }],
    hints: ['Percentage = part ÷ whole × 100.', 'Keep only rows with a tip; multiply by 100.0.', 'ROUND(100.0 * tip / order_value, 1) … WHERE tip IS NOT NULL'],
    explain: 'Multiplying by 100.0 first also protects you from integer division with integer columns.',
    trap: `SELECT delivery_id, ROUND(tip / order_value, 1) AS tip_pct FROM deliveries WHERE tip IS NOT NULL ORDER BY delivery_id;` }),
  // Dates
  P({ id: 'P121', title: 'Delivery time in minutes', dataset: 'food', topics: ['f_dates'], skills: 'Interval → minutes', domain: 'Food delivery',
    prompt: 'For delivered orders, show how many whole minutes delivery took (delivered_at − ordered_at). Sort by delivery_id.',
    output: ['delivery_id', 'minutes_taken'], orderMatters: true,
    solution: `SELECT delivery_id, (EXTRACT(EPOCH FROM delivered_at - ordered_at) / 60)::int AS minutes_taken
FROM deliveries WHERE status = 'delivered' ORDER BY delivery_id;`,
    tests: [{ name: 'Order crossing midnight', category: 'Dates/time', why: 'Durations must work across dates.', patch: `INSERT INTO deliveries VALUES (21,1,113,'2026-03-10 23:50','2026-03-11 00:20','delivered',300,30,NULL,3.0,4);` }],
    hints: ['Subtracting timestamps gives an interval like "01:10:00".', 'EXTRACT(EPOCH FROM interval) gives total seconds. EXTRACT(MINUTE …) only gives the minutes part.', '(EXTRACT(EPOCH FROM delivered_at - ordered_at) / 60)::int'],
    explain: 'EPOCH converts the whole interval to seconds. Order 12 took 70 minutes — EXTRACT(MINUTE) would say 10.',
    trap: `SELECT delivery_id, EXTRACT(MINUTE FROM delivered_at - ordered_at)::int AS minutes_taken FROM deliveries WHERE status = 'delivered' ORDER BY delivery_id;`, techniques: ['epoch'] }),
  P({ id: 'P122', title: 'Customer tenure', dataset: 'shop', topics: ['f_dates'], skills: 'date − date', domain: 'E-commerce',
    prompt: 'As of 30 April 2026, how many days has each customer been signed up? Sort by customer_id.',
    output: ['customer_id', 'name', 'days_since_signup'], orderMatters: true,
    solution: `SELECT customer_id, name, DATE '2026-04-30' - signup_date AS days_since_signup FROM customers ORDER BY customer_id;`,
    tests: [{ name: 'Signed up on the as-of date', category: 'Edge cases', why: 'Same day = 0 days.', patch: `INSERT INTO customers VALUES (11,'Asha','asha@mail.com','Pune','2026-04-30',NULL);` }],
    hints: ['Use the stated date, not today.', 'date − date gives an integer number of days.', "DATE '2026-04-30' - signup_date"],
    explain: 'A fixed as-of date makes the answer reproducible; CURRENT_DATE changes every day.',
    trap: `SELECT customer_id, name, CURRENT_DATE - signup_date AS days_since_signup FROM customers ORDER BY customer_id;`,
    mistakes: [{ re: 'current_date|now\\s*\\(', cat: 'Dates/time', msg: 'Used today instead of the stated as-of date', concept: 'Use the date the question gives so results are reproducible.' }] }),
  P({ id: 'P123', title: 'Meal slots', dataset: 'food', topics: ['f_dates', 'f_case'], skills: 'EXTRACT(HOUR) + CASE', domain: 'Food delivery', difficulty: 'Medium', timeTarget: 8,
    prompt: 'Label every order by the hour it was placed: `breakfast` before 11:00, `lunch` from 11:00 until 16:00, `snack` from 16:00 until 19:00, `dinner` from 19:00. Sort by delivery_id.',
    output: ['delivery_id', 'meal'], orderMatters: true,
    solution: `SELECT delivery_id,
       CASE WHEN EXTRACT(HOUR FROM ordered_at) < 11 THEN 'breakfast'
            WHEN EXTRACT(HOUR FROM ordered_at) < 16 THEN 'lunch'
            WHEN EXTRACT(HOUR FROM ordered_at) < 19 THEN 'snack'
            ELSE 'dinner' END AS meal
FROM deliveries ORDER BY delivery_id;`,
    tests: [{ name: 'Orders exactly on the hour', category: 'Edge cases', why: '11:00 is lunch and 16:00 is a snack.', patch: `INSERT INTO deliveries VALUES (21,3,113,'2026-03-10 11:00','2026-03-10 11:30','delivered',300,25,NULL,2.0,4),(22,7,114,'2026-03-10 16:00','2026-03-10 16:30','delivered',300,25,NULL,2.0,4);` }],
    hints: ['First get the hour of each order.', 'EXTRACT(HOUR FROM ordered_at) gives 0–23. Then bucket with CASE using <.', "CASE WHEN EXTRACT(HOUR FROM ordered_at) < 11 THEN 'breakfast' WHEN … < 16 THEN 'lunch' …"],
    explain: 'Extract once, bucket with strict upper bounds — the same pattern as price bands.',
    trap: `SELECT delivery_id, CASE WHEN EXTRACT(HOUR FROM ordered_at) <= 11 THEN 'breakfast' WHEN EXTRACT(HOUR FROM ordered_at) <= 16 THEN 'lunch' WHEN EXTRACT(HOUR FROM ordered_at) < 19 THEN 'snack' ELSE 'dinner' END AS meal FROM deliveries ORDER BY delivery_id;` }),
  // Keys & grain
  P({ id: 'P124', title: 'One order, many attempts', dataset: 'shop', topics: ['f_model', 'f_filter'], skills: 'Reading grain', domain: 'Payments',
    prompt: 'Order 1009 had payment trouble. Show every payment attempt for it in time order — failures included.',
    output: ['payment_id', 'method', 'status', 'paid_at'], orderMatters: true,
    solution: `SELECT payment_id, method, status, paid_at FROM payments WHERE order_id = 1009 ORDER BY paid_at;`,
    tests: [{ name: 'Another retry', category: 'Logic', why: 'The table holds every attempt.', patch: `INSERT INTO payments VALUES (18,1009,'upi',3596.00,'2026-02-20 11:25','failed');` }],
    hints: ['One order can have several rows in payments. Which column links them?', 'Filter by order_id; sort by time.', 'WHERE order_id = 1009 ORDER BY paid_at'],
    explain: 'payments is at "attempt" grain: one order, many rows. Knowing that prevents double-counting later.',
    trap: `SELECT payment_id, method, status, paid_at FROM payments WHERE order_id = 1009 AND status = 'success' ORDER BY paid_at;` }),
  P({ id: 'P125', title: 'Who was referred', dataset: 'shop', topics: ['f_model', 'f_null'], skills: 'Foreign key + IS NOT NULL', domain: 'E-commerce',
    prompt: 'customers.referred_by holds the customer_id of the person who referred them. List customers who were referred, with their referrer\'s ID. Sort by customer_id.',
    output: ['customer_id', 'name', 'referred_by'], orderMatters: true,
    solution: `SELECT customer_id, name, referred_by FROM customers WHERE referred_by IS NOT NULL ORDER BY customer_id;`,
    tests: [{ name: 'New referral', category: 'NULL handling', why: 'All referred customers must appear.', patch: `INSERT INTO customers VALUES (11,'Lata','lata@mail.com','Pune','2026-03-20',9);` }],
    hints: ['Customers without a referrer have NULL in referred_by.', 'IS NOT NULL keeps rows that have a value.', 'WHERE referred_by IS NOT NULL'],
    explain: 'A foreign key can point back into the same table — here, customer to customer.',
    trap: `SELECT customer_id, name, referred_by FROM customers WHERE referred_by <> NULL ORDER BY customer_id;` }),
  P({ id: 'P126', title: 'Line totals', dataset: 'shop', topics: ['f_model', 'f_select', 'f_match'], skills: 'Row-level arithmetic at line grain', domain: 'E-commerce',
    prompt: 'Show the line items of orders 1001 and 1003 with each line\'s total (quantity × unit price). Sort by order_id, then product_id.',
    output: ['order_id', 'product_id', 'quantity', 'unit_price', 'line_total'], orderMatters: true,
    solution: `SELECT order_id, product_id, quantity, unit_price, quantity * unit_price AS line_total
FROM order_items WHERE order_id IN (1001, 1003) ORDER BY order_id, product_id;`,
    tests: [{ name: 'Extra line on one order', category: 'Logic', why: 'Each line is its own row.', patch: `INSERT INTO order_items VALUES (1003,101,2,799);` }],
    hints: ['order_items has one row per product within an order.', 'Filter two orders with IN; compute quantity × unit_price.', 'quantity * unit_price AS line_total … WHERE order_id IN (1001, 1003)'],
    explain: 'Line totals are computed at line grain; order totals come later by adding lines up (GROUP BY).',
    trap: `SELECT order_id, product_id, quantity, unit_price, quantity + unit_price AS line_total FROM order_items WHERE order_id IN (1001, 1003) ORDER BY order_id, product_id;` }),
];
